### ISSUE TITLE
wrong coment line in sw.js

### ISSUE THREAD

**Issue by Lovntola** [ampproject/amp-by-example#1009]
In the file
https://ampbyexample.com/sw.js
line 110:     `//console.log('ignore? ' + path + ' ' + url + ' -> ' + url.test(path));`
shows error in the console it should be with a space after //
`// console.log('ignore? ' + path + ' ' + url + ' -> ' + url.test(path));`

**Comment by sebastianbenz** [comment]
What do you mean by shows error in the console?

**Comment by Lovntola** [comment]
![error](https://user-images.githubusercontent.com/7427006/32748714-5c58a7de-c8bd-11e7-883f-c7c13e6eb6eb.JPG)
and:
`url.test is not a function` the log points to this line
it was fine after change the coment line

**but I can't reproduce it now.** 
Sorry may be a fault on my site.
Please close this ticket if you don't see this error.
Sorry for waste your time.

**Comment by sebastianbenz** [comment]
np. thanks for looking into this.
