### ISSUE TITLE
Issue in Firefox for amp-list

### ISSUE THREAD

**Issue by zhkuskov** [ampproject/amp-by-example#1024]
in this example: https://ampbyexample.com/samples_templates/product_browse_page/preview/ - in Firefox (mobile and desktop ) dinamic amp-list for "Bestsellers" doesn't work.
Why? Sorry for my english and Thank You!)

**Comment by kul3r4** [comment]
Thanks fo reporting, I actually can't see the network at all for that amp-list. Will take a look.
