### ISSUE TITLE
[AMP Components in Firefox][NF][components_amp] Blank space in example box for components_amp-ad

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1037]
Blank space in example box for amp-ad card in components section 
1. Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-ad and scroll to example box and observe blank space
Observed result:
Expected results: Audio or video should be in place of blank space
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/zS08ufTwG2y

**Comment by kul3r4** [comment]
Hi,
the sample has 2 cases: one for an existing ad and one for a non existing.
You are looking at the second sample, infact `data-slot=.../doesnt-exist`. So no ad is expected to be loaded here.
