### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp bind] Button non responsive in triggering updates box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1040]
Is this Intended?
Is it example for the button or responsive button
Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-bind and scroll to triggering box and click on set to bind and set to bird buttons
Observed result: Buttons are not responsive
Expected results: Buttons should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/drsdqmRZuT0
                     https://screenshot.googleplex.com/njLM2eN6j8q

**Comment by ampff** [comment]
Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-bind and scroll to triggering updates box and click on set to bind and set to cat buttons
Observed result:non responsive buttons
Expected results: buttons should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/drsdqmRZuT0
                    https://screenshot.googleplex.com/njLM2eN6j8q

**Comment by kul3r4** [comment]
Cannot reproduce
