### ISSUE TITLE
[AMP components in Firefox] [NF] 'Play' and 'Pause' buttons are working inconsistently in 'AMP-AUDIO' card

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1041]
Description: 'Play' and 'Pause' buttons are working inconsistently

Steps to Reproduce:
1. Launch Firefox.
2. Go to https://ampbyexample.com/
3. Click on 'Components' tab
4. Under components tap on 'AMP-AUDIO' card
5. Scroll down and observe audio-Play and Pause buttons under the examples

Observed Result: 'Play' and "Pause' buttons are inconsistently working.
Expected Result: 'Play' and 'Pause ' buttons should work as expected.

Environment:
Device: Nexus 4
Version: 5.1.1
Browser: Firefox
Version: 57.0.4

[play.mp4.tar.gz](https://github.com/ampproject/amp-by-example/files/1608194/play.mp4.tar.gz)

**Comment by srivelamala** [comment]
Observed the same issue in 
Desktop win10
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
@ericlindley-g FYI, this works on Chrome but on Firefox clicking on play or pause doesn't work.
