### ISSUE TITLE
[AMP components in Firefox] [NF] Merge of hamburger menu

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1042]
Description : Merge of hamburger menu.
Steps to reproduce:
1.Launch the Firefox browser 
2. Go to URL : 
a.https://ampbyexample.com/components/amp-accordion/
                       or
b.https://www.google.com/amp/s/ampbyexample.com/components/amp-accordion/
3.Observe

Environment:
Browser:Firefox
Build number:IMM76Q
Android version: 4.0.4

Observed results: Merge of hamburger menu
Screenshot:  https://screenshot.googleplex.com/y7usyd9aggW

Expected results:Hamburger menu should be as expected
Screenshot:  https://screenshot.googleplex.com/ktBujCiH9TK

**Comment by kul3r4** [comment]
Cannot replicate this.
