### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp bind_demo] set to bird button non responsive in triggering updates box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1044]
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-bind 
4.Tap on demo view and scroll down to  set to card and set to bird buttons
5.Click on set to bird and observe image and text to set to bird
6.Click on set to cat button and observe no change and still set to bird view.
Observed result: Buttons are not responsive
Expected results: Buttons should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/DKhcm4xzmFw
                     https://screenshot.googleplex.com/DEMawwWxpqF

**Comment by kul3r4** [comment]
Hi,
I think there is a misunderstanding of what the sample is supposed to do, in fact I think the view Demo here doesn't work very well and it's confusing.

If you look at [https://ampbyexample.com/components/amp-bind/](https://ampbyexample.com/components/amp-bind/) there are different samples here:

the button "SET TO CAT" is referred to the html tags using the `amp-state` named "allAnimals". So by clicking on that button the sample sections named: 

> Binding Text

, 

> Binding Styles

, 

> Binding Attribute

 values will change.

the button "SET TO BIRD" is referred to the html tags using the `amp-state` named "remoteAnimals". So by clicking on that button the section named 

> Load state remotely

 will change.

**Comment by kul3r4** [comment]
@ampff ping
