### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp form] Enable experiment button greyed out.

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1048]
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-form  and observe experiment button greyed out in experiment box
Observed result: Experiment button greyed out and non responsive
Expected results: Experiment button button should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/py8VfkqBpT0

**Comment by kul3r4** [comment]
Duplicates #1051
