### ISSUE TITLE
[AMP components in Firefox] Audio disabled under 'Components-AMP-IFRAME' card

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1049]
Description: Audio disabled under 'Components-AMP-IFRAME' card.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Under components,tap on AMP-IFRAME card
4. Tap on any of the videos

Observed Result: Audio disabled for AMP-IFRAME card
Expected Result: Video should play as expected with audio

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by srivelamala** [comment]
Observed same issue in
Device: iOS 11.0.3
Broser: Firefox

**Comment by kul3r4** [comment]
@srivelamala videos in the samples didn't have any audio, this is why you can't hear none.
