### ISSUE TITLE
[AMP components in Firefox] Audio disabled for second video_AMP-JWPLAYER

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1050]
Description: Audio disabled for second video_AMP-JWPLAYER

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'AMP-JWPLAYER' under Components
4. Tap on second video

Observed Result: Audio disabled for second video.
Expected Result: Audio should be audible as expected.

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
Actually those videos do not work on Firefox, I think it's a problem on the AMP extension.
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
Closing: filed in amphtml repo
