### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp selector] Clear selection button not responsive

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1051]
Clear selection button not responsive in Components for amp selector card.Is this intended?
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-form and observe experiment button greyed out in experiment box
Observed result: Experiment button greyed out and non responsive
Expected results: Experiment button button should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/YyrAmx69je9

**Comment by kul3r4** [comment]
yes, that's expected when the experiment is enabled. But your feedback is valuable, we could definitively improve the experience.
