### ISSUE TITLE
[AMP components in Firefox] UI distorted_AMP-pinterest card

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1052]
Description: UI distorted_AMP-pinterest card in Portrait view.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'AMP-PINTEREST' under components
4. Observe example under 'Pin It Button'

Observed Result: https://screenshot.googleplex.com/YUHbR6LqurL
Expected Result: https://screenshot.googleplex.com/5HG7bWj4CZy

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
solved by #1169
