### ISSUE TITLE
[AMP components in Firefox] 'Drop down' button cropped in portrait view_Advanced-COMBO BOX

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1054]
Description: 'Drop down' button cropped in portrait view_Advanced-COMBO BOX.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Combo box' card under Advanced section.
4. Observe drop drown box under example.

Observed Result: https://screenshot.googleplex.com/9QHi0qCxN4o
Expected Result: Drop down button should be visible as expected

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
Cannot reproduce this
