### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp-reach-player] Expand button isnt working in video demo

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1055]
Expand button isnt working for video in components section for amp-reach-player card
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-reach-player and observe video and try viewing video in full screen by clicking full screen icon and observe not expanding when click for full screen.
Observed result: Full screen button isnt working to view full screen
Expected results: Should work on click full screen
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https:https://screenshot.googleplex.com/5CRDySgeiMG

**Comment by kul3r4** [comment]
Same behaviour on Chrome.
@ericlindley-g FYI I think this is a AMPHTML bug

**Comment by ericlindley-g** [comment]
closing: opened bug in amphtml repo
