### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp-video] No audio and audio button is muted default in example box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1056]
No audio and audio button is muted default in Components amp video in example box
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-video and scroll down to example box and and observe audio button is muted by default and no audio
Observed result: No audio and audio button is muted default in Components amp video in example box
Expected results: audio should work and audio button should be enabled
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/69cUPND7qMn

**Comment by kul3r4** [comment]
this is a duplicate of #1081
