### ISSUE TITLE
[AMP components in Firefox] Image missing in the first example_Advanced-Image galleries with AMP carousel

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1057]
Description: Image missing in the first example_Advanced-Image galleries with AMP carousel

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Image galleries with AMP carousel' under Advacned tab.
4. Scroll down and observe image in first example.

Observed Result: https://screenshot.googleplex.com/H95HUURQhW4
Expected Result: https://screenshot.googleplex.com/VqKtqdsQ39t

Environment: 
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
Hi,
I cannot reproduce this bug.

Are you using a real device or an emulator? Would it be possible to see logs from Firefox to check if the problem is with a network call with the image?

**Comment by srivelamala** [comment]
Hi..

Checked it..Able to see image now.

Thanks
