### ISSUE TITLE
[AMP components in Firefox] [NF]_Dynamic AMP_How to Embed interactive elements on AMP pages-Blank space observed under example 2 and 3

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1058]
Description: Blank space observed under example 2 and 3 in 'How to Embed interactive elements on AMP pages' under 'Dynamic AMP'.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'How to Embed interactive elements on AMP pages' under 'Dynamic AMP'.
4. Scroll down and observe example 2 and 3.

Observed Result: https://screenshot.googleplex.com/U7PPJQbgXFV
                            https://screenshot.googleplex.com/2ZkQCponmKr
Expected Result: https://screenshot.googleplex.com/8qDpYU45zh7
                           file:///usr/local/google/home/velamala/Downloads/ex4.png

Environment: Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by srivelamala** [comment]
Expected Result: https://screenshot.googleplex.com/CMN3REKC6av

**Comment by kul3r4** [comment]
Hi,
I cannot reproduce this bug.
I tried with a Samsung Galaxy + Firefox and worked correctly. Are you trying with a real device or an emulator?

Thanks!

**Comment by srivelamala** [comment]
Hi..
Checked it again..This bug is not reproducing now.

Thanks
