### ISSUE TITLE
Add sample for amp-date-picker

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#1059]
This component is now available in canary. [Reference](https://github.com/ampproject/amphtml/issues/6469#issuecomment-356112911)

**Comment by kul3r4** [comment]
I am working on a first sample, published it [here](https://chiara-ampbyexample.appspot.com/components/amp-date-picker/). I had to use `position: static` otherwise the date picker and the clear button were covered by the code section.

@aghassemi I was wondering what is the reason behind having those with `position: absolute` at default? Moreover, why the input with the date (the ones on top of the date picker) is rendered twice?

**Comment by cvializ** [comment]
It looks like the second date rendered is the screen reader message. I think its styles to hide it visually while still being read by the screen reader are not working as expected on ABE. The position absolute allows the date picker calendar to overlay on top of content, instead of pushing content down the page.

**Comment by kul3r4** [comment]
thanks! So is the first problem (screen reader message) related to the default css or is this something I should solve hiding it manually?

Regarding the position absolute, when I tried it it was not overlaying the content and it was hidden behind the code. I agree it would be best overlaying than pushing the content below, but I think the overlaying is not working at the moment.

**Comment by cvializ** [comment]
I am not sure why the extra text is appearing. I think the CSS might be out of sync with the code, which would need to wait for a new release to go out that includes https://github.com/ampproject/amphtml/pull/12672 to fix it

I think the overlay was getting cut off because the preview area is `overflow: hidden`, so it clips anything within it that goes outside, and because the overlay is `position: absolute` it won't change the size of its container.

**Comment by kul3r4** [comment]
@cvializ Thanks! By removing the `overflow: hidden` I can see that now it opens as an overlay.

When using the Range Date picker, is it possible to access the start and end date? I was trying something like [this](https://github.com/ampproject/amp-by-example/blob/date-picker/src/20_Components/amp-date-picker.html#L151) but doesn't work. I was imaging to be able to use `startDate` or `endDate` from the state, but doesn't seem to work.

**Comment by cvializ** [comment]
Ah sorry for the current lack of documentation. `event.dates[0]` is `startDate`, and event.dates[event.dates.length-1] is `endDate`. Maybe it could be a good idea to alias those values with `startDate` and `endDate` properties on the event, like you were expecting.

**Comment by kul3r4** [comment]
@cvializ I managed to print the start date in the[sample](https://github.com/ampproject/amp-by-example/blob/date-picker/src/20_Components/amp-date-picker.html#L152) but only if outside the template. In my code you can see 2 spans: 

```
<amp-date-picker>
......
    <template type="amp-mustache" div info-template>
      <span [text]="'You picked ' + startDate + '.'">You will see your chosen dates here.</span>
    </template>
  </amp-date-picker>

  <span [text]="'You picked ' + startDate + '.'">You will see your chosen dates here.</span>
```

The `span` inside the date picker using the `template` does not print anything, while the one outside prints the `startDate` successful.

**Comment by cvializ** [comment]
Hmm bindings are supposed to work in the `info-template`. Does the first date picker in `examples/date-picker.amp.html` show the binding for you?

**Comment by kul3r4** [comment]
It's working now, false alarm!

**Comment by kul3r4** [comment]
@cvializ I think there is another problem with samples in `examples/date-picker.amp.html`. Some of the are using dates from the past, like for example 1/11/2017 for spooky dates. Unfortunately dates from the past do not seem clickable in the date picker. Is there a way of enabling those?

**Comment by cvializ** [comment]
Ah that could be a CSS styling issue, since the "disabled" dates outside of the default range look too similar to the enabled dates. By default the date picker has dates in the past disabled. To allow dates in the past, specify a min date

```html
<amp-date-picker ... min="2018-01-01" ...></amp-date-picker>
```

**Comment by lswang1618** [comment]
Can we possibly modify the example so that the dates with tacos on them still show the actual date as well?

**Comment by kul3r4** [comment]
I don't think it will fit the space this way.

**Comment by cvializ** [comment]
I could imagine something like an `opacity: .5` taco with the date number positioned on top of it, but it could also look cluttered

**Comment by lswang1618** [comment]
The date boxes expand though right? I think most implementations I've seen include the date still, so we should try and include on the public sample if possible.

**Comment by kul3r4** [comment]
@cvializ how could I modify the sample to recreate this scenario?

**Comment by cvializ** [comment]
You can render the date value using `{{D}}` in the day template, then use CSS to position it

**Comment by kul3r4** [comment]
Thanks!
@lswang1618 Take a look at the last sample on the [draft sample](https://chiara-ampbyexample.appspot.com/components/amp-date-picker/) (remember to enable the experiment on the top of the page). Is that better?

**Comment by lswang1618** [comment]
LGTM! Thanks Chiara :) I think we just need the template id in the json to match what's in the html ("spooky")?

**Comment by kul3r4** [comment]
@cvializ I noticed a strange behaviour with an error on the console.

- Go to [https://ampbyexample.com/components/amp-date-picker/](https://ampbyexample.com/components/amp-date-picker/)
- Click the date picker below the text like "In addition, you can also"
- Observe an error on the console and the date picker being cut. Error is: 

> bundle.js:1 Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null
>     at a.<anonymous> (bundle.js:1)

**Comment by cvializ** [comment]
Ah thanks, I have also observed that. I’m still investigating.

**Comment by cvializ** [comment]
The above issue should be fixed. The example needs to be updated with the new redesigned date picker format which now has improved documentation https://github.com/ampproject/amphtml/blob/master/extensions/amp-date-picker/amp-date-picker.md
