### ISSUE TITLE
[AMP Components in Firefox][NF]_[Advanced_Linked_dropdowns] demo showing blank instead of dropdown

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1063]
Demo showing blank in advanced section for linked dropdown cards
1.Go to https://ampbyexample.com/
2.Tap on Advanced
3.Tap on linked dropdown card and click on demo and observe no dropdown demo and screen is blank
Observed result: Demo showing blank in advanced section for linked dropdown cards
Expected results: Should show drop downs demo
Mac os desktop
Firefox :57.0.4 (64-bit)
Screen shot:https://screenshot.googleplex.com/8fCfoS6hfis

**Comment by srivelamala** [comment]
Observed the same issue in
Desktop win10
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
Thanks for reporting it!
