### ISSUE TITLE
[AMP Components in Firefox][NF] Feature becomes inaccessible after user presses on phone home button

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1064]
Description:
Feature is inaccessible when user is on the feature page, then taps on home button of the device and taps on Firefox browser again - black screen

STEPS:
1. Go to URL https://ampbyexample.com/ in Firefox browser
2. Wait for the page to load and press the device home button
3. Tap on the Firefox icon again

Actual result: Page is black and refreshing the page does not work; user is not able to continue using the feature. Workaround: kill the app and open the browser using the feature link 
https://screenshot.googleplex.com/QzFi08PxD40

Expected: Browser should open with the page displayed normally

ENVIRONMENT DETAILS:
- Firefox version: 57.0.4
- GoogleSearch versionName=7.17.28.21.arm64
- GMS versionName=11.9.51 (940-177350961)
- Device Model= Pixel XL
- Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
- Device Serial number= HT6C90201305
- Gmail Account on device: marfusha88888@gmail.com,

**Comment by kul3r4** [comment]
I cannot reproduce this, must be because the virtual machine you are using.
