### ISSUE TITLE
[AMP Components in Firefox][NF]_[Advanced_paged_list] demo distorted

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1065]
Demo distorted in amp components for paged list card demo is distorted
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on paged list and  and click on demo to observe distorted demo 
Observed result: distorted demo observed in demo
Expected results: demo should be good.
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screen shot:https://screenshot.googleplex.com/ogy704xXzzM

**Comment by kul3r4** [comment]
This has already been fixed.
