### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-google-rvview-image] Missing example images 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1067]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on AMP-google-rvview-image

Observer result: missing example images 
Expected result: display images

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
  ![missingimg](https://user-images.githubusercontent.com/35077268/34750675-261c0536-f55d-11e7-9ff3-259a4df7e90e.png)

**Comment by kul3r4** [comment]
Cannot reproduce this, maybe a network problem on your side?
