### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-ima-video] Missing example video 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1068]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on AMP-ima-video

Observer result: missing example video
Expected result: display video

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7
  
Attachment:
![missingvideo](https://user-images.githubusercontent.com/35077268/34750925-88a5e6e4-f55e-11e7-91e1-28c5b206fb56.png)

**Comment by srivelamala** [comment]
Observed same issue in 
Device: iOS(11.0.3)
Browser: Firefox

**Comment by kul3r4** [comment]
Hi, `amp-ima-video` is experimental, have you enabled the experiment as detailed on top of the page on [https://ampbyexample.com/components/amp-ima-video/](https://ampbyexample.com/components/amp-ima-video/)

**Comment by kul3r4** [comment]
I cannot reproduce this.
