### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-pinterest] Example image is misaligned 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1069]
Issue: image is misaligned and second image is out of container 

Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on AMP-ima-video

Observer result: 1st example image is misaligned and 2d image is out of the container
Expected result: display properly 

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
![misaligned](https://user-images.githubusercontent.com/35077268/34751508-ff843ea2-f561-11e7-80ec-63927d9db962.png)
![outof_cont](https://user-images.githubusercontent.com/35077268/34751511-04e49342-f562-11e7-8e18-3085a71cb300.png)

**Comment by kul3r4** [comment]
Thanks for reporting it.
