### ISSUE TITLE
[AMP components in Firefox][NF] Unable to play video_Advanced_Integrating videos in AMP an overview

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1071]
Description: Unable to play video_Advanced_Integrating videos in AMP an overview

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/ 
3. Tap on 'Integrating videos in AMP an overview' in Advanced tab
4. Scroll down and observe video under example.

Observed Result: Unable to play video.
Expected Result: Video should be playable.

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4
[video1.mp4.tar.gz](https://github.com/ampproject/amp-by-example/files/1619772/video1.mp4.tar.gz)

**Comment by kul3r4** [comment]
This looks a problem of AMPHTML as the video itself is playable on Firefox.
@ericlindley-g FYI

**Comment by aghassemi** [comment]
Just a path to video problem. https://github.com/ampproject/amp-by-example/pull/1187 will fix it.
