### ISSUE TITLE
[AMP Components in Firefox][NF]_[Advanced_show_more_button] Show more button is hiding when click on button

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1072]
Show more button hiding when click 
1.Go to https://ampbyexample.com/
2.Tap on Advanced
3.Tap on show more button card to click on show more button in example box and observe show more button hiding when click
Observed result: Show more button is hiding when on click
Expected results: Show more button shouldnt hide on click
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/69cUPND7qMn
<img width="899" alt="screen shot 2018-01-10 at 9 48 36 am" src="https://user-images.githubusercontent.com/35077268/34787881-aa7b5666-f5ed-11e7-9df2-c111b9caa5e8.png">
<img width="824" alt="screen shot 2018-01-10 at 9 49 11 am" src="https://user-images.githubusercontent.com/35077268/34787892-b1f7beac-f5ed-11e7-875f-d06f36a73ccd.png">

Expected results: audio should work and audio button should be enabled
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/69cUPND7qMn

**Comment by kul3r4** [comment]
This is intended when there is no more content.
