### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-reach-player] "Play" video button is misaligned 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1073]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on AMP-reach-player

Observer result: "Play" button is misaligned to the right lower corner 
Expected result: display in the middle of the video screen 

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment: 
![video_missalign](https://user-images.githubusercontent.com/35077268/34788394-4bcf1c54-f5ef-11e7-9a05-ee197294ec2c.png)

**Comment by ampff** [comment]
Also observed on:

FireFox 57.0.4
GMS versionName=11.9.51 (940-177350961)
Device Model= Pixel XL
Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
Device Serial number= HT6C90201305

See the screenshot:
https://screenshot.googleplex.com/pDBcekeK9Eh

**Comment by kul3r4** [comment]
It appears to me that the `layout=responsive` is not working correctly.
@mikepmtl  could you help?

**Comment by kul3r4** [comment]
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
Closing: Opened issue in amphtml github repo
