### ISSUE TITLE
[AMP Components in Firefox] [NF] 'Show less' Tab is Missing in the Example

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1076]
Description: 'Show less' Tab is Missing in the Example.

Steps to Reproduce:
1. Launch Firefox
2.Go to https://ampbyexample.com/components/amp-accordion/
3. amp accordion page opens
4.Scroll down the page
5.Go to Example 3 
6.Tap on the Show more

Observed: 'Show less' Tab is Missing.
Screenshot: https://screenshot.googleplex.com/ANPPUWhhc9C

Expected: 'Show less' Tab should present 
Screenshot: https://screenshot.googleplex.com/34zNMH72Pv8

**Comment by kul3r4** [comment]
@Vuppala12 Firefox on iOS works for me. Where does it happen for you?
