### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-carousel] Arrow hidden in carousel

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1077]
Issue: Arrow is hidden in carousel

Setup:
1. Device is connected to corp network.
2. Open https://ampbyexample.com/ in latest version of Firefox (57+).

Steps:
1. open hamburger menu
2. Go to [amp-carousel] in Components
3. Scroll down to the last paragraph (A good use case for amp-carousel are image galleries, here are some examples.
4. Click on 'here' link in that paragraph
5. Scroll to the example carousel of the section with title 'linking Carousels with amp-bind'

Observed: Right arrow is functional but is partially hidden on each image of the carousel
https://screenshot.googleplex.com/2xabYnWctGk
https://photos.app.goo.gl/yOMocHd8NzgBeWvp2
Expected: Right arrow should be fully visible

**Comment by ampff** [comment]
ENVIRONMENT DETAILS:
- GoogleSearch versionName=7.17.28.21.arm64
- GMS versionName=11.9.51 (940-177350961)
- Device Model= Pixel XL
- Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
- Device Serial number= HT6C90201305
- Gmail Account on device: marfusha88888@gmail.com,

**Comment by kul3r4** [comment]
Thanks for reporting it!
