### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-soundcloud] Redirection is in two steps instead of one

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1078]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on AMP-soundcloud
6.On Example tap on "Play on SoundCloud" button
7.Press "Back" device button 

Observer result: user should press twice back button in order to get back
Expected result: redirection should be in one press

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
![redirection](https://user-images.githubusercontent.com/35077268/34790329-56861024-f5f6-11e7-9a16-940d4d865360.png)

**Comment by kul3r4** [comment]
This is not related to AMP but how browsers are behaving
