### ISSUE TITLE
[AMP Components in Firefox][NF] [AMP-google-vrview-image] Round bracket should be removed from content

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1079]
Issue: Round bracket should be removed from content of Introduction section in [AMP-google-vrview-image] component

Setup:
1. Device is connected to corp network.
2. Open https://ampbyexample.com/ in latest version of Firefox (57+).

Steps:
1.Open https://ampbyexample.com/ in latest version of Firefox (57+).
2. Tap on the hamburger menu to select Components
3. Tap on [AMP-google-vrview-image]
4. Scroll to the bottom of introduction section to the bullet point 'yaw'

Observed: Round bracket in the content:
yaw: initial yaw rotation) of the viewer
https://screenshot.googleplex.com/V6jWPyT8CiH

Expected: Round bracket should be removed from content:
yaw: initial yaw rotation of the viewer

**Comment by ampff** [comment]
ENVIRONMENT DETAILS:
- GoogleSearch versionName=7.17.28.21.arm64
- GMS versionName=11.9.51 (940-177350961)
- Device Model= Pixel XL
- Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
- Device Serial number= HT6C90201305
- Gmail Account on device: marfusha88888@gmail.com,

**Comment by ampff** [comment]
ENVIRONMENT DETAILS:
- GoogleSearch versionName=7.17.28.21.arm64
- GMS versionName=11.9.51 (940-177350961)
- Device Model= Pixel XL
- Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
- Device Serial number= HT6C90201305
- Gmail Account on device: marfusha88888@gmail.com,

**Comment by kul3r4** [comment]
Thanks for reporting it!
