### ISSUE TITLE
[AMP Components in Firefox][NF]_[Advanced_using_the_google_amp_cache] Convert button is non responsive

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1080]
<img width="883" alt="screen shot 2018-01-10 at 11 22 45 am" src="https://user-images.githubusercontent.com/35077268/34791141-e8225522-f5f8-11e7-96ef-13c5530b0933.png">

Convert button is non responsive.Is it intended?
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on using_the_google_amp_cache and click on convert button .
    Observe button is non responsive
Observed result: Convert button is non responsive
Expected results: Button should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)

**Comment by kul3r4** [comment]
This is not a bug. If you change the URL then you can see that the text below is updated. If you click without changing anything, the default is already there then nothing happens.
