### ISSUE TITLE
[AMP Components in Firefox][NF]_[Advanced_video_carousels_with_amp-carousel/ No audio and audio button is muted default in example box 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1081]
Demo showing blank in advanced section for linked dropdown cards
1.Go to https://ampbyexample.com/
2.Tap on Advanced
3.Tap on video_carousels_with_amp-carousel card and scroll down to example box.
    observe audio muted and non responsive 
Observed result: Audio button is muted in example box for first video
Expected results: Audio should be enabled
Mac os desktop
Firefox :57.0.4 (64-bit)
<img width="1440" alt="screen shot 2018-01-10 at 11 44 11 am" src="https://user-images.githubusercontent.com/35077268/34792099-d34e1836-f5fb-11e7-9ea8-7b9e2694f917.png">

**Comment by kul3r4** [comment]
Video is muted because there is no audio on the video. I agree it doesn't work properly on Firefox.
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
I'm not sure I understand — what's the problem with the video? It sounds like the problem is that there's no audio, but that the video doesn't have any audio anyway.

**Comment by kul3r4** [comment]
@ericlindley-g does it work for you on Firefox? For me it was stopping after few seconds and was not playing correctly

**Comment by ericlindley-g** [comment]
Works for me — feel free to re-open w/ description if you can repro. Thanks!
