### ISSUE TITLE
[AMP components in Firefox][NF] Blank space observed in 'view Demo' button_Advanced-Linked Dropdowns

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1082]
Description: Blank space observed in 'view Demo' button_Advanced-Linked Dropdowns.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Linked Dropdowns' under Advanced tab
4. Tap on 'View Demo'

Observed Result: https://screenshot.googleplex.com/gNzjmh5Z3ai
Expected Result: Content should be displayed in 'Demo'

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

**Comment by ampff** [comment]
Also observed on:

FireFox 57.0.4
GMS versionName=11.9.51 (940-177350961)
Device Model= Pixel XL
Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
Device Serial number= HT6C90201305

**Comment by kul3r4** [comment]
`amp-form` with `type=select` doesn't work on Firefox. This can also be observed in the form [sample](https://ampbyexample.com/components/amp-form/).
@ericlindley-g FYI

**Comment by cramforce** [comment]
Was this closed because it was fixed?

**Comment by ericlindley-g** [comment]
Closed because I opened up a [new issue](https://github.com/ampproject/amphtml/issues/16613) to track directly in the AMPHTML repo :)
