### ISSUE TITLE
[AMP components in Firefox][NF] 'Buy now' button is not responding_Advanced/Payments in AMP

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1084]
Description: 'Buy now' button is not responding_Advanced/Payments in AMP

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Payments in AMP' under Advanced tab
4. Scroll down and tap on 'Buy now' button

Observed Result: 'Buy now ' button is not responding
Expected Result:  'Buy now'  button should work as expected

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0

**Comment by kul3r4** [comment]
The payment API is not supported on Firefox.
