### ISSUE TITLE
[AMP components in Firefox][NF] Element outline visible in hamburger menu

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1085]
Issue: Element outline visible in hamburger menu

Setup:
1. Device is connected to corp network.
2. Open https://ampbyexample.com/ in latest version of Firefox (57+).

Test Steps:
1. Go to https://ampbyexample.com/
2. Tap on hamburger menu icon
3. Tap on any section of the menu (Introduction, Components, etc.)

Observed: Element outline visible
https://screenshot.googleplex.com/VbqgFQQVuc7
https://screenshot.googleplex.com/BgLGZNemaTM
Expected: No outline around element
____________________________________________
ENVIRONMENT DETAILS:
- GoogleSearch versionName=7.17.28.21.arm64
- GMS versionName=11.9.51 (940-177350961)
- Device Model= Pixel XL
- Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
- Device Serial number= HT6C90201305
- Gmail Account on device: marfusha88888@gmail.com,

**Comment by kul3r4** [comment]
Cannot replicate this.
