### ISSUE TITLE
[AMP Components in Firefox][NF]_[dynamic_amp_multi_page_flow]/password is not masking in example sign in box for mac os

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1086]
Demo showing blank in advanced section for linked dropdown cards
1.Go to https://ampbyexample.com/
2.Tap on dynamic amp
3.Tap on multi page flow card and scroll down to example sign in box 
4.Enter email and click on next 
5.Enter Password and observe password is not masking and visible .
observe audio muted and non responsive
Observed result: Password is not masking and visible
Expected results: Password should be masked.
<img width="853" alt="screen shot 2018-01-10 at 12 19 20 pm" src="https://user-images.githubusercontent.com/35077268/34793674-10a1ea96-f601-11e7-9bc5-3b72501612ec.png">

Mac os desktop
Firefox :57.0.4 (64-bit)

**Comment by kul3r4** [comment]
This cannot be solved as type=password is not supported on AMP.
