### ISSUE TITLE
[AMP components in Firefox][NF] UI distorted when tapping on 'Show more' button

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1088]
Description: UI distorted when tapping on 'Show more' button

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Show more button' in Advanced tab
4. Tap on 'View Demo'
5. Tap on 'Show More ' button

Observed Result: UI distorted after tapping on 'show more' button
Expected Result: 'Show more' button should work as expected

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0
[button.mp4.tar.gz](https://github.com/ampproject/amp-by-example/files/1620370/button.mp4.tar.gz)

**Comment by kul3r4** [comment]
This has been fixed, thanks for reporting!
