### ISSUE TITLE
[AMP Components in Firefox][NF] [ComboBox] UI>Drop down arrow button is truncated 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1089]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Advanced"
5.Tap on ComboBox
a.scroll to the example form
b. do next step 6.
6.Tap "View Demo" button

Observer result: drop down arrow is truncated in portrait mode                   
Expected result: display properly

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
![portr_mode_dropdawn](https://user-images.githubusercontent.com/35077268/34794319-238763b4-f603-11e7-970c-1787619c62a9.png)

**Comment by kul3r4** [comment]
Cannot reproduce this
