### ISSUE TITLE
[AMP Components in Firefox][NF] [Custom Loading Indicators ] Example images are missing

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1090]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Advanced"
5.Tap on Custom Loading Indicators

Observer result: examples do not have images 
Expected result: display properly

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
![noimg](https://user-images.githubusercontent.com/35077268/34794852-de87a72c-f604-11e7-90f7-766d18524c95.png)

**Comment by kul3r4** [comment]
Cannot reproduce this, please note that in the sample there is a delay of 5 seconds which is part of the sample.
