### ISSUE TITLE
[AMP Components in Firefox][NF] [advanced/click-to-play_overlay_for_amp-video] video is not playing in "Markup" example box.

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1091]
Description: video is not playing in "Markup" example box.
                    https://screenshot.googleplex.com/8Eec87vwd2S
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on "advances"
4.Click on click-to-play_overlay_for_amp-video card.
5. Observe example for Markup .

Observed result: video is not playing in "Markup" example box.
                           https://screenshot.googleplex.com/8Eec87vwd2S
Expected result: Video should play.

Environment:
Devices: desktop_win7_firefox.
Browser: Mozilla Firefox 57.0.4(32
![screenshot-2018-1-10 click-to-play overlay for amp-video - amp by example](https://user-images.githubusercontent.com/35077268/34796873-dbdabbd4-f60b-11e7-9926-31f289daee70.png)
-bit)

**Comment by kul3r4** [comment]
@ampff Could you check if you see any errors in the console?

**Comment by kul3r4** [comment]
Cannot reproduce this
