### ISSUE TITLE
[AMP components in Firefox] [NF] Incomplete play button for the video

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1093]
Description:  Incomplete play button for the video.

Steps to Reproduce:
1.Launch Firefox
2.Go to https://ampbyexample.com/components/amp-springboard-player/
3.Scroll down the page 

Observed Result: Incomplete play button for the video
https://screenshot.googleplex.com/rUtfMJorcS1 

Expected Result: Should have complete play button for playing video

**Comment by Vuppala12** [comment]
Updated environment :
Browser: Firefox
Android version:7.0
Build number: NRD90M.G935FXXU1DQJ4

**Comment by ampff** [comment]
Also observed on:

FireFox 57.0.4
GMS versionName=11.9.51 (940-177350961)
Device Model= Pixel XL
Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
Device Serial number= HT6C90201305

**Comment by kul3r4** [comment]
Hi,
I don't think this is a bug but it's just the style of the button, in fact it behaves the same in Chrome.
I am closing this bug as there is nothing related to AMPByExample.
