### ISSUE TITLE
[AMP Components in Firefox][NF] [advanced/image_galleries_with_amp-carousel] Text cutoff in example box for dynamic test size.

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1094]
Description: Text cutoff in example box for dynamic test size.
https://screenshot.googleplex.com/w6vYpQrHqX0
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/
3. Observe example for "Dynamic Text Size" .

Observed result: Text cutoff in example box for dynamic test size.
                           https://screenshot.googleplex.com/w6vYpQrHqX0
![firefox_screenshot_2018-01-10t22-43-34 309z](https://user-images.githubusercontent.com/35077268/34799465-bbd370de-f614-11e7-99f4-f197633868b6.png)
Expected result: Text shouldn't cutoff.

Environment:
Devices: Desktop_linux_firefox
Browser: Mozilla Firefox for ubuntu 57.0.4(64-bit)

**Comment by kul3r4** [comment]
@ampff Cannot reproduce on Firefox 58 on mac machine.
Would you mind checking this on a different operating system to better understand where the problem is?

**Comment by kul3r4** [comment]
I cannot reproduce this.
