### ISSUE TITLE
[AMP components in Firefox] [NF] Incomplete YouTube Fullscreen button

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1095]
Description: YouTube Fullscreen button is incomplete

Steps to Reproduce:
1.Launch Firefox
2.Go to https://ampbyexample.com/components/amp-brid-player/
3.Scroll down the page and observed the Example

Observed Result: Incomplete YouTube Fullscreen button
https://screenshot.googleplex.com/1TtS3Aud8KE

Expected Result: Complete YouTube Fullscreen button should be there.

Environment:
Browser: Firefox
Android version:7.0
Build number: NRD90M.G935FXXU1DQJ4

**Comment by kul3r4** [comment]
@Vuppala12 I am able to reproduce it on Firefox while it works well on Chrome, so I don't think it's a problem with AMPByeExample code.
Please create an issue on AMPhtml github project.

**Comment by kul3r4** [comment]
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
For the record: this is just what the Brid player fullscreen button looks like, I think :)

**Comment by kul3r4** [comment]
Agree
