### ISSUE TITLE
[AMP Components in Firefox][NF] [integrating_videos_in_amp_an_overview/preview]Demo page looks blank.

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1097]
Description: Demo page looks blank.
https://screenshot.googleplex.com/w6vYpQrHqX0
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/advanced/integrating_videos_in_amp_an_overview/
3. Click on "View demo" button and observe.

Observed result: Demo page looks blank.
Expected result: Content should be there in demo page.
Environment:
Devices: Desktop_linux_firefox,desktop_win7_firefox.
Browser: Mozilla Firefox 57.0.4.
![firefox_screenshot_2018-01-10t23-14-28 508z](https://user-images.githubusercontent.com/35077268/34800596-5eb819e0-f619-11e7-8652-f0324c83fa8b.png)

**Comment by kul3r4** [comment]
Solved by #1126
