### ISSUE TITLE
[AMP components in Firefox] [NF] Unable to trigger Viewer page for AMP-Access Laterpay

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1098]
Description:  Unable to trigger Viewer page for 'AMP-Access Laterpay' card

Steps to Reproduce:
1. Launch Firefox
2. Go to https://www.google.com
3. Search for the card  'Amp-access laterpay'
4. Tap on the link 'amp-access-laterpay-AMP by Example'

Observed Result: https://screenshot.googleplex.com/M7HnqECg0g5
Expected Result: https://screenshot.googleplex.com/KMcW6jUMRKd

Environment:
Device: Nexus 4
Version: 5.1.1
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
This worked for me, attached snapshot.
![access-laterpay](https://user-images.githubusercontent.com/820891/34955583-10188aba-fa1d-11e7-92b6-e2cfc57c187a.png)
