### ISSUE TITLE
[AMP Components in Firefox][NF] [Payments in AMP ]  "Buy Now" button doesn't have a right border 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1099]
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Advanced"
5.Tap on "Payments in AMP"

Observer result: "Buy Now" button doesn't have a right border 
Expected result: display properly 

ENVIRONMENT DETAILS:
-FireFox 57.0.4
-Device Model= SM-G900H
-Android OS version = MMB29K.G900HXXS1CQD5
-Device Serial number= 4d0092b14eb721a7

Attachment:
![boarder](https://user-images.githubusercontent.com/35077268/34800771-289f3b80-f61a-11e7-97a3-955686080148.png)

**Comment by kul3r4** [comment]
Cannot reproduce on any device, button looks good as on snapshot attached.
![button](https://user-images.githubusercontent.com/820891/34955518-af5832ac-fa1c-11e7-8d31-a7f413f81769.png)
