### ISSUE TITLE
[AMP components in Firefox] [NF] [visual_effects/scroll_to_top] Upward arrow missing

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1101]
Description: Upward arrow missing

Steps to Reproduce:
1.Launch Firefox
2.Go to https://ampbyexample.com/visual_effects/scroll_to_top/
3.Scroll down the page 

Observed Result: Upward arrow missing 
 https://screenshot.googleplex.com/chySoccaJZP

Expected Result: Should have Upward arrow

Environment:
Browser: Firefox
Android version:4.4.2
Build number: KOT49H.1257UCU2BNK1

**Comment by kul3r4** [comment]
Not sure what is going on, I can see the icon clearly. Attached snapshot.
![arrow-up](https://user-images.githubusercontent.com/820891/34823261-a577aa8c-f6c1-11e7-8b02-b1c4fa316a59.png)

**Comment by Vuppala12** [comment]
The issue is observed only on the following Environment:

Browser: Firefox
Android version:4.4.2
Build number: KOT49H.1257UCU2BNK1

Observed Result: Upward arrow missing
https://screenshot.googleplex.com/chySoccaJZP
