### ISSUE TITLE
[AMP components in Firefox] [NF] Viewer: Topics missing from google search

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1102]
Here is the list of topics that are missing when searched through google.com

STEPS:
1. Open Firefox on Android O
2. Go to google.com
3. Search for the following:

amp-app-banner amp by example
amp-experiment amp by example
Click-to-play overlay for amp-video amp by example
Layout System amp by example
Linked Dropdowns amp by example
Paged List amp by example
Rich Media Notifications amp by example
Show More Button amp by example
Star Rating amp by example
How to embed interactive elements on AMP pages amp by example
Multi Page Flow amp by example
Recipes amp by example

Expected: Search term and result match: https://screenshot.googleplex.com/MfEvj6w6xeT
Observed: the above mentioned terms are missing from the SRP

**Comment by kul3r4** [comment]
Thanks for flagging this! For some of them, we were missing the correct canonical link, so I updated it. For others, I was actually able to trigger the result by using the queries you provided.
