### ISSUE TITLE
[AMP components in Firefox] [NF] [visual_effects/scroll_to_top] Missing 'Expand less' icon in the Code

### ISSUE THREAD

**Issue by Vuppala12** [ampproject/amp-by-example#1103]
Description: Missing 'Expand less' icon in the Code.

Steps to Reproduce:
1.Launch Firefox
2.Go to https://ampbyexample.com/visual_effects/scroll_to_top/
3.Scroll down the page

Observed Result: Missing 'Expand less' icon in the Code.
https://screenshot.googleplex.com/68Exj7vjoE0

Expected Result: 'Expand less' icon in the Code should present.
https://screenshot.googleplex.com/SSMnUYHFq84

Environment:
Browser: Firefox
Android version:4.4.2
Build number: KOT49H.1257UCU2BNK1

**Comment by kul3r4** [comment]
Please try this again, I can see the icon. I attached the snapshot.
![icon](https://user-images.githubusercontent.com/820891/34822291-50650100-f6be-11e7-812b-583dbd567ef6.png)

**Comment by Vuppala12** [comment]
The following issue is also observed only in the following Environment:
Environment:
Browser: Firefox
Android version:4.4.2
Build number: KOT49H.1257UCU2BNK1

Observed Result: Missing 'Expand less' icon in the Code.
https://screenshot.googleplex.com/68Exj7vjoE0

Expected Result:  'Expand less' icon in the Code should present.
Screenshot from Build Number: NRD9OM:   https://screenshot.googleplex.com/SSMnUYHFq84

**Comment by kul3r4** [comment]
Cannot reproduce this.
