### ISSUE TITLE
[AMP components in Firefox] [NF] Unable to trigger 'viewer' page for all the cards

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1105]
Description: Unable to trigger viewer page for all the cards.

Steps to Reproduce:
1. Launch Firefox
2. Go to https://www.google.com
3. Search for any of the cards under: Components, Advanced, Dynamic AMP, Visual Effects
4. Tap on card which has link ending with 'AMP by Example'

Observed Result: https://screenshot.googleplex.com/M7HnqECg0g5
Expected Result: https://screenshot.googleplex.com/KMcW6jUMRKd

Environment:
Device: Nexus 4
Version: 5.1.1
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
I don't understand this bug: what do you mean by 

> Go to https://www.google.com

?Which query are you using?

**Comment by kul3r4** [comment]
I just tried it now and i can see the viewer. Attached.
![viewer](https://user-images.githubusercontent.com/820891/34869264-3faa7c62-f77e-11e7-8175-d7c766c97d49.png)

**Comment by srivelamala** [comment]
Observed the same issue.
Tried using the same URL:  https://www.google.com/amp/s/ampbyexample.com/components/amp-accordion/
Observed Result: https://screenshot.googleplex.com/EaSB0H0urBX
[try1.mp4.tar.gz](https://github.com/ampproject/amp-by-example/files/1627706/try1.mp4.tar.gz)

**Comment by kul3r4** [comment]
I can see the viewer with the URL you provided.
