### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_analytics] [IOS 10.3.3 mobile] Hiding pagination arrows on click 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1108]
Pagination arrows hiding on click for components amp ap banner card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp ap banner"
6.Observe no audio for the video in example box

Observer result: Next page arrows are hiding on click
Expected result: Next page arrows to be enabled to navigate next page and shoudnt hide on clicking
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A  IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3
![img_0141](https://user-images.githubusercontent.com/35077268/34839826-da723cca-f6b7-11e7-95bc-c9f0eaa5a8cd.PNG)

**Comment by kul3r4** [comment]
Hi, the iframe is scrollable, so the info is available.
