### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_bind] [IOS 10.3.3 mobile] No audio for video in example box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1110]
No audio for video in example box components amp bind card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp  bind"
6.Observe no audio for the video in example box

Observer result: No audio for video in example box
Expected result: Audio should be enabled for video
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A  IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3

![img_0142](https://user-images.githubusercontent.com/35077268/34843299-e6461ed0-f6c2-11e7-991b-71e0cfcdd600.PNG)

**Comment by ampff** [comment]
Also observed on:

FireFox 57.0.4
GMS versionName=11.9.51 (940-177350961)
Device Model= Pixel XL
Android OS version = marlin-userdebug 8.0.0 OPR1.170620.001 4116128 dev-keys
Device Serial number= HT6C90201305

**Comment by srivelamala** [comment]
Observed same issue in:
iOS(11.0.3)
Model :MKR22LL/A
Browser: Firefox

**Comment by ampff** [comment]
Observed also in Components for card "amp i frame"
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3

**Comment by kul3r4** [comment]
Hi,
the cat video is an mp4 with no audio, this is why you don't hear any audio.
