### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_experiment] [IOS 10.3.3 mobile] Click here button filled with color

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1111]
Click here button filled with red color in  components for amp experiment card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp experiment"
6.Observe button filled with red color
Observer result: Click here button filled with red color
Expected result: Click here button shoudnt fill with color and able to see the text in the box
![img_0143](https://user-images.githubusercontent.com/35077268/34844857-adec5586-f6c7-11e7-8e45-36fe4cf7606d.PNG)

ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6S

**Comment by kul3r4** [comment]
Hi,
you are seeing the correct behaviour, as explained by "red for 30% of users"
