### ISSUE TITLE
[AMP components in Firefox][NF] Audio disabled for 'AMP-app-banner' card

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1112]
Description: Audio disabled for 'AMP-app-banner' card

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/ 
3. Tap on 'AMP-APP-Banner' card under Components
4. Scroll down and observe video under 'Demo'

Observed Result: https://screenshot.googleplex.com/7VnMpztJOsf
Expected Result: Video should be audible

Environment:
Device: iOS 11.0.3
Browser: Firefox

**Comment by kul3r4** [comment]
Hi, 
there is no audio for this video, this is why you don't hear anything.
