### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_experiment] Click here button should be gray

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1113]
Click here button is white in components for amp experiment card on Android O
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp experiment"
6.Observe button is not gray in the example for Basic Usage section

Observer result: Click here button is white
https://screenshot.googleplex.com/jWbGW6YnBWF

Expected result: Click here button should be gray as is stated in the description for the example

**Comment by kul3r4** [comment]
Strange, it's red for me (one of the variant).
What happens if you scroll down to the section 

> Development tip

and click on one of the variants?

**Comment by kul3r4** [comment]
@ampff checked this again and I can reproduce.
Please open a bug on AMPHTML project about this and use this sample as a way if showing the problem.

**Comment by kul3r4** [comment]
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
I think the default color is transparent instead of grey, so it would just be the copy that needs fixing. Is that right?

**Comment by kul3r4** [comment]
You are right, the default is #fff, which is white. I was trying to overwrite the background color to grey but it depends on css order. I think it's easier to keep the white as default as it is. I fixed this in #1178
