### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_form] [IOS 10.3.3 mobile] Enable experiment button greyed out

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1114]
Enable experiment button is greyed out in components for amp form card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp form"
6.Observe enable experiment button greyed out and unable to click
Observer result: Enable experiment button greyed out and non repsonsive
Expected result: Enable experiment should be enabled 
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A  IPhone 6S plus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3

![img_0144](https://user-images.githubusercontent.com/35077268/34849987-1721b21a-f6d9-11e7-95f2-7c7abe0c5a4e.PNG)

**Comment by kul3r4** [comment]
The button it's disabled because probably you have already enabled the sample.
If you clean your cookies and reload, the button should be clickable.
Could you try it and confirm?
