### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_form] [IOS 10.3.3 mobile] Week in example box is missing and unable to enter week

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1115]
Week in example box is missing and unable to enter week in other form input sample box in components for amp form card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp form"
6.Observe enable experiment button greyed out and unable to click
Observer result: Week in example box is missing and unable to enter week in other form input sample box 
Expected result: Week in example box should be enable
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6S plus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3
![img_0145](https://user-images.githubusercontent.com/35077268/34850329-3b45efe8-f6da-11e7-8944-b78aa8601774.PNG)

**Comment by kul3r4** [comment]
Support of type week is limited on Firefox. 

> The control's user interface varies from browser to browser; cross-browser support is currently a bit limited, with only Chrome/Opera and Microsoft Edge supporting it at this time. 

from [doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week).
@ericlindley-g FYI
