### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_form] [IOS 10.3.3 mobile] Unable to enter datetime in "Datetime -local box" 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1116]
Unable to enter datetime in "Datetime -local box" components for amp form card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp form"
6.Scorll down to datetime local example box and observe error out when enter date time
Observer result: Unable to enter datetime in "Datetime -local box"
Expected result: Should be able to enter date and time in datetime local box
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6S plus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3
![img_0146](https://user-images.githubusercontent.com/35077268/34852174-2a88948c-f6e2-11e7-9e51-d38da1c7de6c.PNG)

**Comment by kul3r4** [comment]
This is working for me, I attached a snapshot.

Could you try it again?
![date](https://user-images.githubusercontent.com/820891/34949913-7ba705b8-fa09-11e7-8bde-42726660d4aa.png)

**Comment by ampff** [comment]
Verified and working as expected
