### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp_google-vrview-image] [IOS 10.3.3 mobile] Image is not loading in example box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1117]
Image not loading in example box in  components for amp google vrview image card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp google virview image card"
6.Scorll down to example box and observe image is not loading in example box
Observer result: Image is not loading in example box
Expected result: Image should load in example box
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6S plus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3
![img_0147](https://user-images.githubusercontent.com/35077268/34853475-c0e212f4-f6e8-11e7-9578-2e8bd3094860.PNG)

**Comment by kul3r4** [comment]
Hi,
the image is loading for me, I cannot reproduce this.
