### ISSUE TITLE
[AMP components in Firefox] [NF] Blank screen appears in 'Amp-fx-flying-carpet' under Advertising example

### ISSUE THREAD

**Issue by srivelamala** [ampproject/amp-by-example#1118]
Description: Blank screen appears under Advertising example

Steps to Reproduce:
1. Launch Firefox
2. Go to https://ampbyexample.com/
3. Tap on 'Amp-fx-flying-carpet' under Components tab
4. Scroll down and observe advertising example

Observed Result: https://screenshot.googleplex.com/daaWFj0n9Uf
Expected result: https://screenshot.googleplex.com/EDoaDFp78kx

Environment:
Desktop_win10
Browser: Firefox
Version: 57.0.4

**Comment by kul3r4** [comment]
The sample works fine for me, I can see from your screenshot that you are using a VMWare station. Could it be that it's taking a lot of time to load the ad? Could you check if you see any errors?

**Comment by kul3r4** [comment]
I verified this again and works well for me.
I am gonna close this issue as i can't replicate.
