### ISSUE TITLE
[P1] Update access and notification examples to always include amp-analytics script

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amp-by-example#112]
Here are some of the affected examples:

- https://ampbyexample.com/components/amp-access/
- https://ampbyexample.com/components/amp-user-notification/
- https://ampbyexample.com/advanced/amp-user-notification_with_server_endpoint/

See: 
- https://github.com/ampproject/amphtml/issues/2701
- https://github.com/ampproject/amphtml/pull/2726

**Comment by sebastianbenz** [comment]
Updated examples have been deployed as well.
