### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp-kaltura-player] [IOS 10.3.3 mobile] video buffering forever and not playing

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1122]
Video buffering forever and not playing in  components amp kaltura player  card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp kaltura player"
6.Observe buffering video forever in example box and not playing
Observer result: Next page arrows are hiding on click
Expected result: Next page arrows to be enabled to navigate next page and shoudnt hide on clicking
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3
![img_0150 2](https://user-images.githubusercontent.com/35077268/34898624-011f1cde-f7a9-11e7-9286-24c90d3975f1.PNG)

**Comment by kul3r4** [comment]
Just tried this and works fine for me. Could you try this again? Was it maybe a network problem?

**Comment by ampff** [comment]
Tried after clearing  cache and still issue exists.

**Comment by kul3r4** [comment]
You are right and I could see this happening.
I think this could be a problem with AMP and Firefox on iOS. I suggest to create a bug on AMPHTML project.

**Comment by kul3r4** [comment]
Closing this as should be solved on AMPHTML project.

**Comment by kul3r4** [comment]
@ericlindley-g FYI

**Comment by ericlindley-g** [comment]
closing: Filed in amphtml repo
