### ISSUE TITLE
[AMP Components in Firefox][NF] [Components_amp-ima-video] [IOS 10.3.3 mobile] back button functionality isnt working 

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1123]
Back button functionality isnt working  in components amp ima video player card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp ima video"
6.Click on enable dev channel button 
and Observe unable to navigate back and sticking on the dev channel page
Observer result: Unable to navigate to back using back button
Expected result: Back button functionality should work to go back 
Environment details:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3

![img_0148](https://user-images.githubusercontent.com/35077268/34899110-c37c5984-f7ab-11e7-8b9a-96269b4effb9.PNG)

**Comment by kul3r4** [comment]
This is not a bug: a new tab is open because this is an external link (cdn.ampproject....) and it does not stay inside ampbyexample.com.
