### ISSUE TITLE
[AMP Components in Firefox][NF] [dynamic_amp-how_to_embed_interactive_elements] [IOS 10.3.3 mobile] Best picture video is missing in example box

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1130]
Best picture video is missing in example box in dynamic_amp-how_to_embed_interactive_elements on amp pages card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "dynamic amp"
5.Tap on "how to embed interactive elements on amp pages card"
6.Observe best picture video is missing in example box
Observer result: best picture video is missing in example box
Expected result: best picture video should be displayed in example box
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6Splus
-Android OS version = 10.3.3
-Device Serial number= F2LS21A8HFM3

![img_0151](https://user-images.githubusercontent.com/35077268/35016346-fe336b02-facc-11e7-9a70-ee39d77d4721.PNG)

**Comment by kul3r4** [comment]
I cannot reproduce this.
