### ISSUE TITLE
It is any way to start with AJAX or custome event ??

### ISSUE THREAD

**Issue by hetalvarshaaweb** [ampproject/amp-by-example#114]
Hello,

I am starting with AMP for my site Need to know that we can not use AJAX ??

AND one more issue which i am getting on development 

If i am adding script like this
`<script async src=https://cdn.ampproject.org/v0.js></script>` -IT's fine
But If i download that script and try to add like,`<script async src=folderPAth/v0.js></script>`
AMP Validation ERROR Why ??

**Comment by sebastianbenz** [comment]
Please ask these questions via stackoverflow.com. 

Quick comments:

* you can't use ajax 
* you have to use the officially hosted amp-runtime to make sure that sites doesn't tinker with the runtime.
