### ISSUE TITLE
is there a AMP cdn instead of cdn.ampproject.org?

### ISSUE THREAD

**Issue by minicase** [ampproject/amp-by-example#1140]
is there a amp cdn instead of cdn.ampproject.org?
because of  china 's great firewall ,my website users can't reach google's servers.

how to get https://cdn.ampproject.org/v0.js with a mirror cdn server?

**Comment by kul3r4** [comment]
Hi @minicase 
this is a project hosting AMP samples.
For general questions about AMP please use [amp support](https://www.ampproject.org/support/)
