### ISSUE TITLE
Playground is applying amphtml validator to amp4ads

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amp-by-example#1146]
Please check this amp ad example. It seems playground is applying amphtml validator instead of amp ad validator. 
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Famp-ads%2Fbasic_ads%2Fbanner_ad%2Fsource%2F

**Comment by sebastianbenz** [comment]
This is fixed since the re-launch at AMPConf.
