### ISSUE TITLE
¿BUG in AMP-IMAGE-LIGHTBOX ? shows "activate: Unsupported element: IMG​​​ _reported_"

### ISSUE THREAD

**Issue by CarlosSola** [ampproject/amp-by-example#1158]
Hi,
Suddenly the AMP-IMAGE-LIGHTBOX fails, even in the Playground:
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-image-lightbox%2Fsource%2F

¿is this a bug?
The console shows:

service.js:255 Unsupported element:  IMG
ce @ service.js:255
(anonymous) @ viewer-impl.js:178
f.assert @ log.js:324
push.f.g.activate @ amp-image-lightbox.js:804
f.executeAction @ performance-impl.js:141
Cg.b.Pe @ custom-element.js:738
Cg.b.enqueAction @ layout.js:311
hh @ ampdoc-impl.js:176
k @ shadow-embed.js:173
(anonymous) @ shadow-embed.js:188
gh @ web-components.js:103
f.trigger @ v0.js:233
(anonymous) @ v0.js:231

12:53:10.113 log.js:318 Uncaught Error: Action execution failed: AMP-IMAGE-LIGHTBOX activate: Unsupported element: IMG​​​ _reported_
    at oa.f.assert (log.js:318)
    at Z.push.f.g.activate (amp-image-lightbox.js:804)
    at Z.f.executeAction (performance-impl.js:141)
    at HTMLElement.Cg.b.Pe (custom-element.js:738)
    at HTMLElement.Cg.b.enqueAction (layout.js:311)
    at hh (ampdoc-impl.js:176)
    at k (shadow-embed.js:173)
    at shadow-embed.js:188
    at Array.forEach (<anonymous>)
    at gh (web-components.js:103)

**Comment by sebastianbenz** [comment]
This looks like a bug in the AMP runtime. //cc @aghassemi

**Comment by aghassemi** [comment]
@cathyxz , could you take a look? Looks like a P0 regression.

**Comment by cathyxz** [comment]
Ack
