### ISSUE TITLE
Example not working.

### ISSUE THREAD

**Issue by TagCommander** [ampproject/amp-by-example#1176]
I have absolutely no idea why exactly, but the example as is doesn't work for me. I have to change the notification id by *any other* name for it to work.

**Comment by kul3r4** [comment]
Hi,
which sample specifically doesn't work for you?

**Comment by TagCommander** [comment]
This one: https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-user-notification%2Fsource%2F

**Comment by TagCommander** [comment]
My bad I just understood what I did wrong. It was simply saved in the local storage several days ago and I forgot about it.

Not enough sleep :(
