### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by AsimTariq** [ampproject/amp-by-example#1190]
Hi Shopping Cart example is not working in playground. 
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2F%2Fshopping_cart%2Fsource%2F

**Comment by kul3r4** [comment]
@sebastianbenz to be honest, I think the Shopping cart should not be opened on a playground, as it is not meant to be a sample by itself. Is there a way to disable the playground for certain pages?

**Comment by sebastianbenz** [comment]
```
<!---{
  "disablePlayground": true
}--->
```

Should do the trick.
