### ISSUE TITLE
Menu item highlights sometimes wrong

### ISSUE THREAD

**Issue by alankent** [ampproject/amp-by-example#1201]
When I go to some pages, such as https://ampbyexample.com/introduction/hello_world/, I get a red underling for BOTH the "AMPHTML" and "AMPHTML ads" top level menu items. (There are two `<li>` tags with the `www-current-page` CSS class name added.) Some submenu pages only underline one, but others underline more than one. 

![image](https://user-images.githubusercontent.com/5702163/37547519-63e0a704-292f-11e8-82cb-a7eb81cc222b.png)

Going to a different page in the same submenu gets it right, such as https://ampbyexample.com/introduction/how_to_publish_amps/

![image](https://user-images.githubusercontent.com/5702163/37547542-8bf4bfd2-292f-11e8-88f0-155e13730e55.png)

I am on a Mac running Chrome.

**Comment by sebastianbenz** [comment]
Fixed by #1376. Thanks for reporting Alan!
