### ISSUE TITLE
Amp Video: Add Video Source Later?

### ISSUE THREAD

**Issue by casbboy** [ampproject/amp-by-example#1208]
The biggest issue I'm having with Amp Video is that it exposes your Video URLs to scrapers. My other pages add the urls through obfuscated code later, but can't find a way here, since no javascript is allowed on the page.

Any way to better hide the video sources?

Cheers!
Ryan

**Comment by sebastianbenz** [comment]
This is the wrong place for AMPHTML feature requests. Please open an issue
here: https://github.com/ampproject/amphtml/issues/new
