### ISSUE TITLE
Create a sample that shows multiple languages of the same document

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#122]

**Comment by sebastianbenz** [comment]
What is the recommended approach for this in AMP?

**Comment by jmadler** [comment]
I'm not totally sure, but as I understand it, the recommended approach is multiple documents with distinct URLs using link tags with "rel=alternate hreflang=XX", and html tags with "lang=XX".

**Comment by kul3r4** [comment]
@tcmg can you take a look if this is covered by your sample

**Comment by kul3r4** [comment]
Fixed by #1189
