### ISSUE TITLE
[good first issue] Add default styling examples to `amp-social-share`

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amp-by-example#1225]
### What you need to know
- Some familiarity with CSS
- How to [run and test this repository](https://github.com/ampproject/amp-by-example#creating-a-new-sample)

### The feature

A common request/question I've observed at hackathons is more examples for common styling for amp-social-share components. For example: 
- round icons
- rounded corners with text
- mono-colored icons
Add more examples similar to this: https://codepen.io/cathyxz/pen/mxYVbY

The AMP By Example page for `<amp-social-share>` lives [here](https://github.com/ampproject/amp-by-example/blob/708098d591d15ff515e8ea9c9ec178fc969452f5/src/20_Components/amp-social-share.html). Feel free to add them at the bottom of the page. 

### Step by Step
- [ ] Claim this issue by commenting under this issue here. 
- [ ] Setup [Github](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github)
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Sign the [Contributor's License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement). 
- [ ] Commit your changes and push them to github. 
- [ ] Create a pull request and tag @cathyxz, @sebastianbenz for review.

**Comment by sebastianbenz** [comment]
Nice - we definitely should add these!

**Comment by fstanis** [comment]
@cathyxz anything else you feel needs to be added or can we close this issue?

**Comment by cathyxz** [comment]
Feel free to close.
