### ISSUE TITLE
AMP basic

### ISSUE THREAD

**Issue by Osama1122** [ampproject/amp-by-example#1235]
Hello EveryOne , I want to work on amp , can anyone help me out , i am confused , about a thing , that can we build a whole ecommerce website on AMP , purely? kindly guide me with.
if yes , how can we set data dynamically , like we use services etc in Angular like technologies.

**Comment by kul3r4** [comment]
Hi, please use [AMP developer support channels](https://www.ampproject.org/support/developer/) for general questions.
