### ISSUE TITLE
Create a metadata sample for ImageGalleries that are also NewsArticles

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#125]

**Comment by sebastianbenz** [comment]
How is this different to a normal NewsArticle?

**Comment by jmadler** [comment]
The key bit here is that there are two schema.org blocks: one for a NewsArticle and one for an ImageGallery

**Comment by sebastianbenz** [comment]
Should both blocks be present at the same time? Do we have an existing example for this? I'm currently working on a [NewsArticle Sample](https://github.com/sebastianbenz/amp-by-example/blob/samples/src/60_Sample_AMPs/News_Article.html) which also includes an image gallery.

**Comment by jmadler** [comment]
I think the best way is to create a JSON block that is an array of dictionaries
