### ISSUE TITLE
(Newbie Question) Please Help - How to install on shared hosting

### ISSUE THREAD

**Issue by sri1985** [ampproject/amp-by-example#1261]
I downloaded the zip file and uploaded the contents of the zip file to my shared hosting.
My site is:  www . bejitarian . com
The star rating comes, but its not working.

Kindly help

I am a newbie. I uploaded to my shared hosting via ftp.

Is there anything to be done?

Thanks

**Comment by kul3r4** [comment]
Hi,
http://www.bejitarian.com/ doesn't seem to be an AMP page.
For general questions about AMP please use [support channels](https://www.ampproject.org/support/).
If you have a question about a specific sample hosted on AMPbyExample please specify the name of the sample and the problem you are encountering.

**Comment by sri1985** [comment]
@kul3r4 Thanks a lot for your reply.
Sorry, its now available at: http://bejitarian.com/star.html (takes some time to load). If you see, the rating are not registered. Everytime I refresh , only the default rating comes.

Thanks a lot for your help.

**Comment by kul3r4** [comment]
Hi,
that is exactly the same behaviour of the example.
If you want to save/persist the ratings, you will have to implement the backend. At the moment your form is posting to `/samples_templates/rating/set` which I guess you haven't implemented. Also, you will have to read the status from the server when you load the ratings, for example [favorite button sample](https://ampbyexample.com/advanced/favorite_button/) does that: if you click on the heart button and then reload, the state is persisted.
