### ISSUE TITLE
Create a sample with a desktop-only column

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#129]

**Comment by juliantoledo** [comment]
Hi, Jordan, could you explain this a bit further?

Thanks!

**Comment by juliantoledo** [comment]
Sebastian just added Show Preview:
https://ampbyexample.com/advanced/how_to_create_interactive_amp_pages/

Does that help?

**Comment by jmadler** [comment]
That isn't precisely what I was going for -- sorry for the lack of context.  

The intent here is to illustrate a pattern by which certain UI elements can be made visible on devices of certain screen sizes.  You can, for example, have more ads on desktop than on mobile due to the increased screen size.

**Comment by sebastianbenz** [comment]
I don't really see the need for a sample. This is basic CSS. BTW AMP by Example already does this - on mobile examples will be collapsed into a single column.

**Comment by jmadler** [comment]
I agree that it's basic CSS, but it may be worth illustrating explicitly to show how AMP is mobile-first but not mobile-only.

**Comment by jmadler** [comment]
Following-up on this -- I think we can close this one for now since it's pretty much covered by ABE itself.  I haven't heard any demand for a sample that illustrates this clearly, despite my expectations.

Thoughts?

**Comment by sebastianbenz** [comment]
sgtm
