### ISSUE TITLE
Consent granularity

### ISSUE THREAD

**Issue by TagCommander** [ampproject/amp-by-example#1302]
Hello !

I have a lot of demands from client who would like to use amp and the consent form. But all of them would like to keep the behaviour we offer on our web product which is being able to consent to only part of the data usage.

For example allowing to collect data for analytics purpose but not for personalised ads. Or sometimes even going down to the vendor level in each categories.

From the tests I've done until now, I can display details, but I understood that we can only have 1 Consent instance and that you can only accept/refuse/dismiss it.
Thus I can't have granularity this way.

My main job is not web dev, so I might have missed something obvious somewhere :)
Is there a way to allow a user to consent to only part of the data collection ?
Also keeping in mind that we have to be able to have access to what was authorised so we can use it in our custom amp-analytics component.

Thanks a lot.

**Comment by sebastianbenz** [comment]
Please use the official AMP developer support channels for questions.
