### ISSUE TITLE
Create Samples & Templates section

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amp-by-example#131]
We will create a metadata section that includes an example of each @type

Including these:
#126  #125 #124

**Comment by jmadler** [comment]
I think it makes sense to incorporate this as the 'Samples & Templates' section referenced in #238.

I'd like to propose that the samples displayed in this section would forego the [3 column layout](https://ampbyexample.com/advanced/video_carousels_with_amp-carousel/) that currently exists and instead show the AMP article exactly as-is.

Supporting media (images, videos) would be stored in a directory with the same name as the amp document.

**Comment by sebastianbenz** [comment]
@jmadler each vertical sample has already a preview mode which hides all ABE related styling. Is this what you want? Besides, I think especially for these samples the annotated source view is really valuable.

**Comment by sebastianbenz** [comment]
The section exists now.
