### ISSUE TITLE
Unable to get AMP on mailer 

### ISSUE THREAD

**Issue by swap17** [ampproject/amp-by-example#1310]
Hi,

i am send AMP form to gmail account.Now on receiving email its displaying the code.I have attached the snapshot.Please help to rectify
![amp-mailer](https://user-images.githubusercontent.com/663704/41352310-c75066c4-6f36-11e8-8712-9ece8c344b9f.png)
.

**Comment by kul3r4** [comment]
Hi,
this is a project for AMP samples.
Please use [developer support](https://www.ampproject.org/support/developer/) channels for questions.
