### ISSUE TITLE
Geolocation-based Consent Flow

### ISSUE THREAD

**Issue by MarcellusMusic** [ampproject/amp-by-example#1313]
## What's the issue?

I am working with the Geolocation-based Consent Flow found here: https://ampbyexample.com/user_consent/geolocation-based_consent_flow 

The issue is that the geolocation-based consent message is displaying on both US & EU browsers rather than only EU.

## How do we reproduce the issue?

1. Append custom country codes to the url:

- EU: https://ampbyexample.com/user_consent/geolocation-based_consent_flow/#amp-geo=de

- non-EU: https://ampbyexample.com/user_consent/geolocation-based_consent_flow/#amp-geo=us

Similarly, when I added a Geolocation-based Consent Flow to my own website, I have the same issue:

- EU: https://marcelluslong.com/amp/#amp-geo=de

- non-EU: https://marcelluslong.com/amp/#amp-geo=us

HTML: http://jsbin.com/cixoruliko/edit?html,output

## What browsers are affected?

Safari, Chrome, and Firefox.

## Which AMP version is affected?

Version 1528841168349

**Comment by sebastianbenz** [comment]
I can't reproduce this. Make sure to enable the dev channel via https://cdn.ampproject.org/experiments.html.
