### ISSUE TITLE
Reponsive width doesn't work

### ISSUE THREAD

**Issue by makayjozsef** [ampproject/amp-by-example#1315]
Responsive layout parameter doesn't work. Facebook Page Plugin loaded in 340px width every time :(

**Comment by kul3r4** [comment]
Hi,
are you reporting a problem with a sample hosted on [ampbyexample.com](https://ampbyexample.com) or a general problem?
If it's a sample then please add the link to the sample, for general questions or bugs on AMPHTML please use AMP support [channels](https://www.ampproject.org/support/developer/).

**Comment by kul3r4** [comment]
Closing this as I haven't received more details.
