### ISSUE TITLE
Basic User Consent Flow Problem 

### ISSUE THREAD

**Issue by wustzdd** [ampproject/amp-by-example#1333]
For GDPR, the Facebook pixel needs to be revoked before receiving the consent. Once accepted by customer, the Facebook pixel needs to be granted, How can I deal with it in the amp project? You can see the Facebook document:https://developers.facebook.com/docs/facebook-pixel/events-advanced-use-cases/v3.0

**Comment by kul3r4** [comment]
Hi,
please use [stackoverflow channel ](https://stackoverflow.com/questions/tagged/amp-html) for general question about AMP.
