### ISSUE TITLE
amp_story_hello_world warns 'AMP-STORY (beta)' is deprecated

### ISSUE THREAD

**Issue by andrewspy** [ampproject/amp-by-example#1342]
**Describe the bug**
amp validator warns `The tag 'AMP-STORY (beta)' is deprecated - use 'AMP-STORY' instead` in https://ampbyexample.com/stories/introduction/amp_story_hello_world/

**To Reproduce**

Go to [validator.ampproject.org](https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fstories%2Fintroduction%2Famp_story_hello_world%2Fpreview%2Fembed)

**Expected behavior**
No warning

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome v67

**Additional context**
N/A

**Comment by andrewspy** [comment]
I have checked again on my desktop, and I'm still getting the same warning, attached screenshot:

![amp-story-beta-is-deprecated](https://user-images.githubusercontent.com/3106425/42512768-081f193c-8488-11e8-8e41-8f3b3074cb3a.PNG)

**Comment by kul3r4** [comment]
Strange, this is what I get:
![story-error](https://user-images.githubusercontent.com/820891/42512978-c23a9e44-844d-11e8-8a9e-f2c7ae510657.png)

**Comment by kul3r4** [comment]
Now I see that you are using /preview/embed.  Any particular reason?

**Comment by andrewspy** [comment]
@kul3r4 

I think you are validating a different URL, try this:-

https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fstories%2Fintroduction%2Famp_story_hello_world%2Fpreview%2Fembed

**Comment by andrewspy** [comment]
I am using that because that's an direct link in ampbyexample.com -> AMPHTML stories -> Introduction -> AMP Story Hello World navigation. And I have amp validator chrome extension installed, and it shows me that error in the extension the other day.

**Comment by kul3r4** [comment]
It seems to me that the migration from 0.1 to 1.0 wasn't done correctly. I was looking at the PR #1036 and according https://www.ampproject.org/docs/reference/components/amp-story#migrating-from-0.1-to-1.0 the src should be in its own tag `amp-story-bookend`. 
@ithinkihaveacat Would you be able to help here?

**Comment by ithinkihaveacat** [comment]
@kul3r4 I think you mean https://github.com/ampproject/amp-by-example/pull/1306?

But yes I agree, the existing amp-story hello world is broken. #1344 should fix that page, though just noticed that the other examples under AMPHTML stories will still be broken. (Will create a PR to fix them shortly.)

**Comment by andrewspy** [comment]
I think the https://ampbyexample.com/json/bookend.json is not a marked `"bookendVersion": "v1.0"`, which trigger the beta deprecation warning. "AMP Story Hello World" should properly be migrated to v1.0 as it serve as a "Hello World" example for `<amp-story>`.

**Comment by kul3r4** [comment]
Fixed by #1344
