### ISSUE TITLE
Navigation menu appears in different font on different pages

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-by-example#1346]
The top level navigation ("AMPHTML", "AMPHTML ads", etc.) appears in a different font depending on which section is selected:

https://ampbyexample.com:

![screen shot 2018-07-11 at 12 46 26 pm](https://user-images.githubusercontent.com/51244/42569551-c24b1ef2-8508-11e8-9f47-bddc01c34b19.png)

https://ampbyexample.com/stories/introduction/amp_story_hello_world/:

![screen shot 2018-07-11 at 12 46 36 pm](https://user-images.githubusercontent.com/51244/42569558-c8f7d1f0-8508-11e8-9024-845b8c09fe1b.png)

**Comment by kul3r4** [comment]
Interesting! were you able to debug what is the core reason? A css rule probably being overwritten somewhere?

**Comment by ithinkihaveacat** [comment]
I'm not sure, I haven't really investigated it, sorry!

But it looks like styles are missing, rather than being overwritten. (In the "bad" case, no font is set and the default font is used.)

**Comment by fstanis** [comment]
It's not just navigation - the font of the whole doc is different on e.g. https://ampbyexample.com/amp-ads/introduction/hello_world/ compared to https://ampbyexample.com/stories/introduction/amp_story_hello_world/

**Comment by fstanis** [comment]
Well, this was straightforward, I should've read the sample code first, it's overring `font-family` of the `<body>` tag:

https://github.com/ampproject/amp-by-example/blob/e98f6fb9c8b87c9931fb670c30e80138e5ed4b98/src/stories/10_Introduction/_AMP_Story_Hello_World.html#L23-L25

Same issue with *Hotel* sample:

https://github.com/ampproject/amp-by-example/blob/a7555868be23f1954ce9c32d55e7141c97d6d83b/src/60_Samples_%2526_Templates/Hotel.html#L54-L56

@ithinkihaveacat do you think we can drop the styling on `body` or narrow down the selector?

**Comment by kul3r4** [comment]
For the hotel sample you can remove the overriding of the font for sure!
