### ISSUE TITLE
amp-fx="parallax fade-in-scroll" is not validated anymore

### ISSUE THREAD

**Issue by websitegenii** [ampproject/amp-by-example#1360]
On your page https://ampbyexample.com/components/amp-fx-collection/ the last example is combining Parallax and Fade-in-Scroll. This works and works fluidly on a website. It is showing in the validator as not valid. So I assume this was valid at one point and now is not. Though having a fade in parallax is a great animation to have and is a real shame it's not allowed.

**Comment by nainar** [comment]
Hi @websitegenii - I'm taking a look into this. This should be valid.

**Comment by nainar** [comment]
Uploaded a fix - https://github.com/ampproject/amphtml/pull/16957. 

Closing this issue since we are tracking the issue on the amphtml repo (where the fix lies) here: https://github.com/ampproject/amphtml/issues/16956
