### ISSUE TITLE
FR: demo for dynamic pricing dependent on city-level geo

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#1365]
This issue was surfaced to me by someone looking for such a sample, since it is common enough in e-commerce use cases that it would be useful to make clear.

This implementation would use amp-list, as opposed to amp-geo, because amp-geo isn't granular enough.

Could be a standalone sample, but could also just be integrated into an existing demo (e-comm) or component (amp-list)

WDYT?  

What we'd want to avoid is advocating a pattern that doesn't have a good fallback (should encourage reasonable content at load time or if server fails), or has too much of the UI depend on server call (should just be small bits like price, as opposed to large sections of content in the viewport).

**Comment by sebastianbenz** [comment]
We already have a sample covering this use case: https://ampbyexample.com/advanced/geolocation_with_amp-list/.

**Comment by ericlindley-g** [comment]
Sorry about that—looks great!
