### ISSUE TITLE
Add link rel=canonical tags to examples

### ISSUE THREAD

**Issue by Gregable** [ampproject/amp-by-example#14]
Currently none of the examples fully validate due to missing `<link rel=canonical>` tags.
https://www.ampproject.org/docs/reference/spec.html#canon

**Comment by sebastianbenz** [comment]
Every page should contain a canonical link to itself, e.g. 

`<link rel="canonical" href="Hello_World.html">`

in https://amp-by-example.appspot.com/Hello_World.html

**Comment by jkingyens** [comment]
I'm seeing this in my "gulp validate" task branch as well. However, the example html files appear fine according to the spec. The odd thing is Hello_World.html is passing for me. It looks significantly different from the other examples. Is there something different about its conformance?

**Comment by jkingyens** [comment]
The cause for me was a typo/bug in my validator task. @Gregable are you trying to validate the html files in "src" directory? These are templates that need to be expanded in order to validate correctly.

**Comment by Gregable** [comment]
Sorry I must have missed your reply.

The pages themselves contain a rel=canonical link, but the example that is rendered in the page does not. Consider for example:
https://ampbyexample.com/components/amp-access/
This document itself contains:
<link rel="canonical" href="https://ampbyexample.com/components/amp-access/" >

So if I view-source:https://ampbyexample.com/components/amp-access/ and control+f for `canonical`, I find it.

However the actual example doesn't contain rel=canonical. So, if I'm looking at the rendered example doc, and not the source,and control+f for `canonical`, I don't find it. https://ampbyexample.com/introduction/hello_world/ has a canonical in the example:
`&lt;<span class="hljs-name">link</span> <span class="hljs-attr">rel</span>=<span class="hljs-string">"canonical"</span> <span class="hljs-attr">href</span>=<span class="hljs-string">"https://ampbyexample.com/Introduction/Hello_World"</span>&gt;`

Does this make sense?

**Comment by sebastianbenz** [comment]
Yeah - you're right. The canonical link is automatically generated to make authoring samples easier. We should add it to the code sections as well.
