### ISSUE TITLE
Only one menu item should show selected state at a time

### ISSUE THREAD

**Issue by spacedino** [ampproject/amp-by-example#1412]
**Describe the bug**
 AMPHTML / AMPHTML Ads / AMPHTML email are all selected

**To Reproduce**
1. Go to https://ampbyexample.com/amphtml-email/introduction/hello_world/

**Expected behavior**
Only AMPHTML Email should be selected

**Screenshots**
<img width="1424" alt="screen shot 2018-07-27 at 11 31 31 am" src="https://user-images.githubusercontent.com/7339798/43340330-d072a556-9190-11e8-8d34-59a71701000f.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version lastest

**Additional context**

**Comment by sebastianbenz** [comment]
Thanks for reporting - fixed that one [yesterday](https://github.com/ampproject/amp-by-example/pull/1376
) (deploying right now).
