### ISSUE TITLE
amp-lightbox-gallery is too much buggy

### ISSUE THREAD

**Issue by rajat304** [ampproject/amp-by-example#1429]
amp-lightbox-gallery not working properly.
See the video: https://www.useloom.com/share/39698b3f22564e3091ee3430df21ab66

1. Go to 'https://ampbyexample.com/components/amp-lightbox-gallery/' 
2. Click on 'https://ampbyexample.com/components/amp-lightbox-gallery/#basic-usage the image and then close'
3. Then Open Again. See it doesn't open. Sometimes it opens. Try again and again.

Chrome version: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sebastianbenz** [comment]
Thanks for reporting! @cathyxz can you take a look? I can reproduce the problem in desktop safari as well.

**Comment by rajat304** [comment]
And after that, it removes the browser scroller,
see the video
https://www.useloom.com/share/3bddf9ea551f43efaddb4290bc651882

**Comment by cathyxz** [comment]
Yup, we had a regression https://github.com/ampproject/amphtml/issues/17044, which was fixed by https://github.com/ampproject/amphtml/pull/17145. Waiting for the change to land in production.

**Comment by sebastianbenz** [comment]
Closing this issue. Feel free to reopen in case problems persist.
