### ISSUE TITLE
Example ad in amp-fx-flying-carpet playground is broken 

### ISSUE THREAD

**Issue by CrystalFaith** [ampproject/amp-by-example#1441]
Example advertisement isn't displaying in the [amp-fx-flying-carpet playground ](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-fx-flying-carpet%2Fsource%2F)

1. Navigate to the [amp-fx-flying-carpet playground ](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-fx-flying-carpet%2Fsource%2F)
2. Notice how the advertisement doesn't display - only the image. 
![screen shot 2018-08-06 at 4 14 47 pm](https://user-images.githubusercontent.com/23297417/43745527-10956ed8-9994-11e8-9cbb-fee4d4093555.png)

Desktop:
 - OS: iOS
 - Browser: Chrome 
 - Version: 70.0.3510.0

**Comment by kul3r4** [comment]
Thanks for reporting!
it's mostly because the "<amp-fx-flying-carpet> elements must be positioned after the 75% of first viewport" and with the playground there is not the doc content.

We could add some more text, @sebastianbenz would that be ok for you?

**Comment by sebastianbenz** [comment]
SGTM - can you also add "Scroll down" somewhere

**Comment by kul3r4** [comment]
I would avoid to add a scroll down to this sample to not make it too difficult as this is a component sample

**Comment by sebastianbenz** [comment]
I just meant adding something like '<strong>Scroll Down to the
amp-fx-carpet in action<strong> into the code (without comment so that it's
only displayed in the playground / preview.
