### ISSUE TITLE
amp-3d-gltf example is blank

### ISSUE THREAD

**Issue by lannka** [ampproject/amp-by-example#1446]
According to [PR's description](https://github.com/ampproject/amp-by-example/pull/1298#issuecomment-398709097) and error message, I believe it's a CORS issue:

> Failed to load https://ampbyexample.com/glTF/DamagedHelmet.glb: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://d-17903745583975110301.ampproject.net' is therefore not allowed access.

**Comment by sebastianbenz** [comment]
Yes, this has already been fixed [here](https://github.com/ampproject/amp-by-example/pull/1438) and is live since yesterday. Thanks for reporting.
