### ISSUE TITLE
Don't show broken examples

### ISSUE THREAD

**Issue by jakearchibald** [ampproject/amp-by-example#1463]
https://ampbyexample.com/components/amp-image-slider/

By default, all the examples on this page are broken. Instead of showing broken examples, either:

* Allow them to work. In the try-before-you-buy model, I shouldn't have to buy before I try.
* Explain to the user that the example is broken on purpose. This is less-good, but a contextual message would be better than a broken example. Ideally the button to fix the issue should accompany every deliberately-broken example.

**Comment by kul3r4** [comment]
Hi Jake,
do you mean that "enable experiment" is not clear for users to understand?
I am referring to the first bit of the page, where it says:

Experimental Mode
This example uses the following experimental feature: [amp-image-slider]. Enable the experiment via the button below. Some components require the AMP Dev Channel to be enabled as well. Learn more here.

**Comment by sebastianbenz** [comment]
Thanks Jake - I agree, this would be good to have. 

@matthiasrohmer @pbakaus this is something would should keep in our mind for the ampproject.org re-design.
