### ISSUE TITLE
Can't bind input value to string

### ISSUE THREAD

**Issue by jilt** [ampproject/amp-by-example#1481]
**Describe the bug**
I'm trying to bind some input values and paste them on a string joining an url set through a json state (named "roomType", that works fine); the bind expression seems to work (no error in the console) but the result is always null, I tried with the input-throttled action also (as stated on this example: https://ampbyexample.com/components/amp-bind/#triggering-updates ) but the result seems the same.
`
<input class="block relative p0 z1" 
type="date" 
placeholder="yyyy-mm-dd" 
pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" 
title="yyyy-mm-dd" 
name="arrive" 
id="arrive"
               on="change:AMP.setState({date: event.value})">
            <div class="travel-date-input-label">
              Check-in
            </div>
<a class="ampstart-btn travel-input-big center bold white block col-12" [href]="roomType[roomType.currentRoom].bookingUrl + '&checkin=' + date" 
  role="button"
  tabindex="0">Book Now</a>`

**To Reproduce**
1. Go to 'https://ampbyexample.com/components/amp-bind/#triggering-updates' Please specify the link to an AMPByExample sample.
2. Click on 'triggering updates'
3. Scroll down to 'input bind example'
4. In my code you can see I'm trying to concatenate the json Url string to the date for checkin but the resulting url is:
https://www.beds24.com/booking2.php?propid=22011&referer=iframe&lang=en&roomid=52827&checkin=null

**Expected behavior**
I expected a date in default format yyyy-mm-dd to be displayed after '&checkin=' in the link's url
The string concatenation follows the guidelines in the same amp-bind page example.
Can you please tell me what's wrong with my code?

**Desktop (please complete the following information):**
 - chromeOS
 - Chrome
 - 67.0.3396.99

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kul3r4** [comment]
Hi,
I cannot find  'input bind example' anywhere in the page. 

Could you reproduce your case by using the playground https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-bind%2Fsource%2F?

**Comment by jilt** [comment]
I've had a try with the playground but neither the json nor the input bindings work there (the json url is not recognised)...
Here is the code:

`<body>
  
  <amp-state id="roomType">
    <script type="application/json">
      {
        "currentRoom": "single",
        "single": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52827"]
        },
        "double": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52828"]
        },
        "triple": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52829"]
        }
      }
    </script>
  </amp-state>
  <label class="travel-date-input relative bold flex-auto" [class]="'travel-date-input relative bold flex-auto' + (fields_departure ? ' travel-date-input-touched' : '')">
    <input class="block relative p0 z1" type="date" placeholder="yyyy-mm-dd" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" title="yyyy-mm-dd" name="date" id="date" on="change:AMP.setState({date: event.value})">
  </label>
  <a class="ampstart-btn travel-input-big center bold white block col-12" [href]="roomType[roomType.currentRoom].bookingUrl + '&checkin=' + date" role="button" tabindex="0">Book Now
  </a>


</body>`

Hope it helps

**Comment by jilt** [comment]
The example is on the [triggering updates](https://ampbyexample.com/components/amp-bind/#triggering-updates) paragraph

**Comment by kul3r4** [comment]
Hi,
I copied that on the playground and worked correctly.

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>amp-bind</title>
  <link rel="canonical" href="https://ampbyexample.com/components/amp-bind/">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <script async src="https://cdn.ampproject.org/v0.js"></script>

  <!-- ## Setup -->
  <!--
  Import the amp-bind component in the header.
  -->
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

</head>
<body>
  <!-- ## Configuring initial state -->
  <amp-state id="roomType">
    <script type="application/json">
      {
        "currentRoom": "single",
        "single": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52827"]
        },
        "double": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52828"]
        },
        "triple": {
          "bookingUrl": ["https://www.beds24.com/booking2.php?propid=xxxxx&referer=iframe&lang=en&roomid=52829"]
        }
      }
    </script>
  </amp-state>
  <label class="travel-date-input relative bold flex-auto" [class]="'travel-date-input relative bold flex-auto' + (fields_departure ? ' travel-date-input-touched' : '')">
    <input class="block relative p0 z1" type="date" placeholder="yyyy-mm-dd" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" title="yyyy-mm-dd" name="date" id="date" on="change:AMP.setState({date: event.value})">
  </label>
  <a class="ampstart-btn travel-input-big center bold white block col-12" [href]="roomType[roomType.currentRoom].bookingUrl + '&checkin=' + date" role="button" tabindex="0">Book Now
  </a>


</body>
</html>
```

I can see the date being sent correctly

**Comment by jilt** [comment]
OMG you're right... I lost my mind on this monitor today, thanks a lot for your time Chiara! I'm the italian designer you met in Amsterdam by the way.. thanks again and sorry if I wasted your time ;)

**Comment by kul3r4** [comment]
don't worry about it, glad it works.
