### ISSUE TITLE
Make the mobile UI great again

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#149]
Current status of the mobile UI:

* hide code column
* hide docs for header elements
* shows preview inline with doc

This results in the mobile version being mostly unusable. The main problems are:

* introduction is missing
* comments aimed at code don't make sense without source code

Goals:

* Show full doc
* Show code (maybe make it expandable via accordion)
* Clearly separate code, doc and preview sections

@juliantoledo @kul3r4 @adewale feel free to suggest any ideas.

**Comment by kul3r4** [comment]
Another thing to consider is that if you want to break the code in different sections. At the moment the code is all in one column (the central one) when you are on desktop.
On mobile we could break it in different sections and showing the code section after each documentation section. We could also show the first line of the code section and make it expandable with a carousel. 

For example:

"Import the libraries"
<script async custom-element="amp-accordion" .....

where "<script async custom-element="amp-accordion" ....." is clickable and it's gonna open the rest of the code in an accordion.

**Comment by sebastianbenz** [comment]
Sounds good. How about:

* only showing code sections which have a comment
* make code sections longer than 10 lines expandable (once amp-accordion has been released)

**Comment by sebastianbenz** [comment]
The following has been added by e93cb7f2e702d53cee490fed1ebef1a406c88b13:

    * show code sections if they have a comment
    * show preview sections if they have a comment
    * hide sections with empty docs
    * show single column view for screen < 1024px

**Comment by sebastianbenz** [comment]
Fixed with e93cb7f.
