### ISSUE TITLE
AMP Story previews missing

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-by-example#1497]
https://ampbyexample.com/stories/introduction/amp_story_hello_world/preview/embed/ 404s. It previously existed, and is the "view story" link from https://ampbyexample.com/stories/introduction/amp_story_hello_world/.

Not sure what happened here. Some of the code around this was fiddled with recently (in #1490 and #1489) but everything works as expected when building from a fresh checkout locally.

**Comment by sebastianbenz** [comment]
https://github.com/ampproject/amp-by-example/pull/1489 is the culprit. Will fix.
