### ISSUE TITLE
How to use Shamsi date or others types of calendars on date picker ?

### ISSUE THREAD

**Issue by aladaghlou** [ampproject/amp-by-example#1533]
Hi.
How to use Shamsi date or Hijri date or  others types of calendars on date picker component ?
Are there solution for this problem?
This is not small problem !

Best regards.

**Comment by kul3r4** [comment]
Hi,
this repository provides samples for amp components. For general questions please use Stackoverflow[https://stackoverflow.com/questions/tagged/amp-html]
