### ISSUE TITLE
amp-form xhr amp-mustache not displaying returned json vars

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amp-by-example#1549]
**Describe the bug**
amp-form xhr amp-mustache not displaying returned json vars

**To Reproduce**
On page https://www.ampproject.org/docs/reference/components/amp-form#success/error-response-rendering the first example under "Success/error response rendering" was coded.
See here for code: https://codepen.io/iamalta/pen/vVyErX

The returned json is 
[{"name":"Jane Miller","interests":[{"name":"Basketball"},{"name":"Swimming"},{"name":"Reading"}],"email":"email@example.com"}]

**Expected behavior**
Should get the following for the above example with the mustaches completed.
Success! Thanks {{name}} for subscribing! Please make sure to check your email {{email}}
		to confirm! After that we'll start sending you weekly articles on {{#interests}}<b>{{name}}</b> {{/interests}}.

This is what is displayed - missing name and start date.
Success! Thanks for subscribing! Please make sure to check your email to confirm! After that we'll start sending you weekly articles on . 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser chrome, firefox dev
 - Version most recent

**Smartphone (please complete the following information):**
Didn't test.

**Additional context**
n/a

**Comment by kul3r4** [comment]
Hi,
this project is ampbyexample.com while you are referencing code from https://www.ampproject.org which is a separate repo. I suggest to file an issue on https://github.com/ampproject/docs.

**Comment by IamAlta** [comment]
Got it. I thought amp was amp regardless of amp project or my example. I now know. Thank you for the clarification.

**Comment by IamAlta** [comment]
@Kul3r4,
This ampbyexample page has the same issue.
https://ampbyexample.com/components/amp-form/

It says "You can use amp-mustache templates to show custom success or error messages, using data sent by the server endpoint as JSON." and gives an example that we tried. It didn't work.

**Comment by kul3r4** [comment]
I just tried the sample and it prints the result from the json. Attached the snapshot.
Can you provide the code you are using and the setup?
![name](https://user-images.githubusercontent.com/820891/46674457-1889f600-cbd4-11e8-9f61-74d56441dd4f.png)

**Comment by IamAlta** [comment]
Hi Chiara @kul3r4 ,

I spend hours on a problem and when I ask for help, I then see the problem.
This is solved.
The problem was the returned json had too many dimensions in the array. It was created as for amp-list with "items" as the parent array.

So sorry but thanks for the kick to get this solved :)

Make it a nice day. You deserve it.
