### ISSUE TITLE
Make an amp-sidebar sample that uses amp-list

### ISSUE THREAD

**Issue by adewale** [ampproject/amp-by-example#155]
When https://github.com/ampproject/amphtml/issues/3083 is implemented please provide a sample that uses amp-list to populate an amp-sidebar.

One possibility would be to create a CORS-compliant resource that provides a list of the components then use amp-list to consume that and generate an amp-sidebar.

**Comment by juliantoledo** [comment]
This is not possible as today: "The <amp-sidebar> may not contain any AMP Elements except for amp-accordion, amp-img and amp-fit-text"
