### ISSUE TITLE
Can I Check Server side code of this amp Mortgage Calculator

### ISSUE THREAD

**Issue by scarlett1012** [ampproject/amp-by-example#1588]
https://ampbyexample.com/samples_templates/housing/
I want to work on amp sites so can i see backend code of above page Mortgage Calculator request query & which platform we use For Form Actions like php or jquery ?

**Comment by sebastianbenz** [comment]
You can find the server-side generated code here: https://github.com/ampproject/amp-by-example/blob/master/backend/housing.go#L37

Nowadays, I'd recommend implementing something like this client-side using amp-bind.
