### ISSUE TITLE
Add a sample showing the "flying carpet" effect on a variety of components

### ISSUE THREAD

**Issue by adewale** [ampproject/amp-by-example#159]
https://github.com/ampproject/amphtml/issues/3126 requests a "flying carpet" visual effect.

Make a nice looking sample showing this effect being applied to:
- amp-ad
- any other components that are supported

**Comment by kul3r4** [comment]
Currently working on it: https://github.com/kul3r4/amp-by-example/tree/amp-flying-carpet.
