### ISSUE TITLE
AMP Dynamic CSS Classes | Google AMP Viewer Link Broken

### ISSUE THREAD

**Issue by hadidotj** [ampproject/amp-by-example#1620]
**Describe the bug**
On the AMP Dynamic CSS Classes page, the 'Google AMP Viewer' link in the 'Viewer' section does not properly load the page in the Google AMP Viewer as suggested. This is due to the current link being wrong (see expected behavior).

**To Reproduce**
1. Go to 'https://ampbyexample.com/components/amp-dynamic-css-classes/'
2. Scroll down to 'Viewer' (last) section
3. Click on 'Google AMP Viewer' link
4. Receive a 'Redirect Notice' that links back to the original 'AMP Dynamic CSS Classes' page instead of loading in the Google AMP Viewer

**Expected behavior**
Should direct you to https://www.google.com/amp/s/ampbyexample.com/components/amp-dynamic-css-classes/

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6 (High Sierra)
 - Browser: Chrome
 - Version: 70.0.3538.102

**Comment by sebastianbenz** [comment]
Thanks for reporting. This is actually a documentation problem as the viewer works only on mobile.

**Comment by hadidotj** [comment]
Hi @sebastianbenz ,

Sorry, I failed to mention I was in the "mobile emulation mode" as iPhone 6/7/8. I just checked on my iPhone 7 as well. I was aware the viewer only works on Mobile. However, the link takes you to the "Redirect Notice", even when on Mobile. It is missing the "/s" after "/amp".

Current Incorrect Link (missing /s): https://www.google.com/amp/ampbyexample.com/components/amp-dynamic-css-classes/

Results in:
![image](https://user-images.githubusercontent.com/5050953/48572194-ba3ceb00-e8d6-11e8-8ac6-63aba9b239fe.png)

Corrected Link (with /amp/s): https://www.google.com/amp/s/ampbyexample.com/components/amp-dynamic-css-classes/

Results in:
![image](https://user-images.githubusercontent.com/5050953/48572245-ebb5b680-e8d6-11e8-8c45-614574f55c10.png)

Thanks,
