### ISSUE TITLE
Have a canonical invalid AMP and point AMP Cache documentation to it

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-by-example#163]
Was just playing around with the Cache page on ampbyexample.com and noticed a small issue.

It looks like the invalid AMP example actually points to a broken link (404): https://cdn.ampproject.org/c/s/ampbyexample.com/invalid_amp_page.html.

Would it be possible to introduce an actual invalid AMP to point to?

**Comment by kul3r4** [comment]
The invalid amp page should point here: https://cdn.ampproject.org/c/s/ampbyexample.com/invalid_amp.html

**Comment by kul3r4** [comment]
It has been fixed [here](https://github.com/ampproject/amp-by-example/commit/c83086c6ba3a456db50d4db7c229aa3eb48dac84#diff-82c351c337e38470b570858928f6ef8c), but not deployed yet.

**Comment by sebastianbenz** [comment]
Deployed.
