### ISSUE TITLE
amp-story demos don't work

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#1635]
All "demo" links in amp-story related tutorials seem to be broken.

https://ampbyexample.com/stories/features/animations/preview/embed/ for instance.

Normal amp-story outside of ABE are fine.

@sebastianbenz @newmuis

**Comment by sebastianbenz** [comment]
Looks like we broke it as part of the amp-consent change. Will take a look.

**Comment by ithinkihaveacat** [comment]
This might be #1590 (`amp-story-1.0.js` being missing is at least part of the problem).
