### ISSUE TITLE
rel=0&showinfo=0 in amp-youtube?

### ISSUE THREAD

**Issue by TomLeeMS** [ampproject/amp-by-example#1663]
Hey!

Is it possible to use amp-youtube and do not show other movies in the end?
Usualy there wos  a varialbe rel=0 and showinfo=0, you could add to the iframe container that wos blocking related movies etc...

so how to do it in amp-youtube?

**Comment by sebastianbenz** [comment]
You can use data-param-* to pass custom parameters, e.g. `data-param-rel="0"`.
