### ISSUE TITLE
Issue when setting up AMP project

### ISSUE THREAD

**Issue by vetri02** [ampproject/amp-by-example#170]
Am getting the following error when installing the amp project

when I run 'npm i' getting the following error. PFA the log file
[npm-debug.log.zip](https://github.com/ampproject/amp-by-example/files/291854/npm-debug.log.zip)

**Comment by jkingyens** [comment]
Hi Verti02, I was able to perform the full instructions from master without error. This issue might be with your npm/node install given the error is related to file ownership. Double-check your permissions on your install path vs. node binaries.

**Comment by vetri02** [comment]
Hi I have tried the same command with sudo still getting the same error

**Comment by sebastianbenz** [comment]
Please try again after updating your NPM installation:

$ npm update
$ npm clean cache
$ rm -rf node_modules
$ npm i
