### ISSUE TITLE
Broken Amp Story Introduction Example

### ISSUE THREAD

**Issue by bramanudom** [ampproject/amp-by-example#1800]
**Describe the bug**
The Amp Story "Hello World" example in [the live link](https://ampbyexample.com/stories/introduction/amp_story_hello_world/preview/embed/).

**To Reproduce**
1. Go to the [live example on either mobile or desktop](https://ampbyexample.com/stories/introduction/amp_story_hello_world/preview/embed/).
2. Notice how the screen consists of full-bleed dog images that scroll down as opposed to pages,

**Expected behavior**
The text and images should be in the story format.

**Screenshots**
![broken example](https://cdn.pbrd.co/images/HWTfSed.png).

**Desktop (please complete the following information):**
 - OS: Linux/Debian
 - Browser:Chrome
 - Version: 71.0.3578.98 (Official Build)

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android 9
 - Browser: Chrome

**Additional context**
I've forked the repo and locally run it locally on my machine per the instructions. When locally run, the example seems to be working.

**Comment by sebastianbenz** [comment]
Thanks for reporting! The bug is already fixed (but not yet deployed). The problem is that the live button links to the wrong document.
