### ISSUE TITLE
Using hreflang with two amp documents

### ISSUE THREAD

**Issue by devignerforhire** [ampproject/amp-by-example#1810]
I'm investigating providing translated versions of our top posts and after a bit of digging, I see AMP supports hreflang, but the examples provided don't cover a native amp implementation where multiple versions of a post (french, spanish, etc) are full amp docs. Would it just be a case of adding the hreflang meta and a canonical meta on the translated posts? TIA!

**Comment by kul3r4** [comment]
Hi, 
for general questions please use [AMP stackoverflow](https://stackoverflow.com/questions/tagged/amp-html)
