### ISSUE TITLE
amp-bind [class] 

### ISSUE THREAD

**Issue by zhuozhang19911122090807** [ampproject/amp-by-example#1816]
When using amp-bind to bind the [class] attribute, the initialization page reports an error: %s: "%s" is not a valid result for [class]. amp-bind null. What should I do with this problem? I also saw an error in the template page. You can see the console at this address is reporting an error: https://ampbyexample.com/components/amp-bind/source/#development=1

**Comment by sebastianbenz** [comment]
Thanks for reporting. The class state doesn't get initialised correctly.
Will fix this.

>

**Comment by zhuozhang19911122090807** [comment]
Thank you for your answer! How is the class state initialized correctly? I have not found a relevant method. Can there be an example?

**Comment by kul3r4** [comment]
I believe the problem is that the variable used to initialize [class] is null. I sent #1824 that should fix it.

**Comment by zhuozhang19911122090807** [comment]
Thank you for providing samples! The problem is solved perfectly, thank you very much!
