### ISSUE TITLE
Allow seatmap multiple seat selection with one click

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#1819]
Add the capability to the seatmap sample to select more than a seat at once.

**Comment by sebastianbenz** [comment]
Can you file this on ampproject/docs instead?

>

**Comment by kul3r4** [comment]
I was thinking about updating the sample, would ampproject/docs be still the best place?

**Comment by sebastianbenz** [comment]
If you do it today, ampbyexample is still the best place ;-)
