### ISSUE TITLE
Old Browser Warning

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amp-by-example#185]
Unfortunately, my business is in Taiwan/China and there are still quite a few customers (like half) that use  old browsers, particularly IE. 

Really need a way to detect browsers and return a special page for visitors on unsupported browsers. Used JS before. Anyway to do this with AMP HTML, and if not, can we create something simple, quickly?

**Comment by sebastianbenz** [comment]
Which versions are problematic?

@cramforce do we any recommendations how to handle these cases in AMP?

**Comment by 88kbbq** [comment]
My issues were more about HTML5 and CSS3 support, not just JS and AMP specifications. Need to redirect old browsers to an HTML4 page. Don't cry, but many local companies here still run XP. It's employee abuse.

**Comment by cramforce** [comment]
AMP will not support it. I'd recommend to do this using server side user agent detection.
