### ISSUE TITLE
Placeholder missing url

### ISSUE THREAD

**Issue by vegagame** [ampproject/amp-by-example#1855]
In this page 
https://ampbyexample.com/playground/#url=https://ampbyexample.com/components/amp-video-iframe/source/

Wrong:
`<amp-img placeholder src="/img/amp-video-iframe-sample-placeholder.png" layout="fill">`

OK:
`<amp-img placeholder src="/img/amp-video-iframe-sample-placeholder.jpg" layout="fill">`

**Comment by kul3r4** [comment]
Thanks for reaching out, I have sent #1856 to fix this
