### ISSUE TITLE
Split examples into sections

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#19]
To give a better overview over the samples, we could split the samples into sections in the overview page, e.g.:

1. Introduction
    * Hello World
    * ...
2. Components
   * amp-img
   * amp-carousel
   * ....
3. Getting more out of AMP
   * Video Carousel
   * How to cope with the fixed carousel height?
   * User notifications with server end-point
   * ...

Implementation wise this is simple by moving the samples into respective directories. 

//cc @adewale @juliantoledo @jkingyens @ymotongpoo  @kul3r4 what do you think?

**Comment by kul3r4** [comment]
LGTM

**Comment by adewale** [comment]
LGTM
