### ISSUE TITLE
Turn experiment activation into button

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp-by-example#196]
I suppose this might be problematic in terms of AMP validity, but it would be super nice if the experiment instructions on https://ampbyexample.com/components/amp-fx-flying-carpet/ would just run the code instead of asking to paste it into the console. Maybe the button could use an iframe :)

Something like `<button onclick="AMP.toggleExperiment('amp-fx-flying-carpet')">Activate experiment</button>`

**Comment by sebastianbenz** [comment]
That'd be nice indeed. Does it work via iframe if it is on a subdomain? Otherwise, experimental examples usually don't validate anyway...

**Comment by cramforce** [comment]
Good point that they don't validate. Just do it inline then. I think it is a god trade off.
