### ISSUE TITLE
Side-by-side preview broken by comment in amp-carousel

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#197]
1. Get the [Recipe sample](https://github.com/dandv/amp-by-example/blob/bf3c51483456aa0ea33ec1db4fe66ef68b2c4226/src/50_Sample_AMPs/Recipe.html)
2. Move [line 370](https://github.com/dandv/amp-by-example/blob/bf3c51483456aa0ea33ec1db4fe66ef68b2c4226/src/50_Sample_AMPs/Recipe.html#L370) above the `address` tag it explains.
3. Run `gulp`.
4. Open http://localhost:8000/sample_amps/recipe/ and scroll down.

Notice how the carousel rendering is broken.

![image](https://cloud.githubusercontent.com/assets/33569/16028484/9f37e806-3194-11e6-94c4-791277d6afa9.png)

**Comment by sebastianbenz** [comment]
Nested comments are not supported (this is also explained in the readme). Correctly aligning doc, code and preview for nested comments is not trivial as each comment section is it's own DIV.   

Closing as WAI
