### ISSUE TITLE
Facebook Pixel does not appear on the AMP

### ISSUE THREAD

**Issue by rodrigocarlos** [ampproject/amp-by-example#1971]
Hello guys,

I have inserted in the pages of my site the pixel codes of Facebook. And I use the Chrome extension developed by Facebook to know if the pixel is actually installed on the pages: https://screenshot.net/pt/7q372hn?

But I realized that when I activate the AMP version, the extension shows that the pages on my site do not have active Facebook pixel: https://screenshot.net/pt/7z07qf0?

However, I check the source code of AMP pages and see that a slightly different Facebook pixel code appear:

https://screenshot.net/pt/78x7jcd?

`<!-- Facebook Pixel Code --><!--noscript--><amp-img height="1" width="1" src="https://www.facebook.com/tr?id=9999999999999&amp;ev=PageView&amp;noscript=1" class="amp-wp-enforced-sizes amp-wp-cb45893" layout="intrinsic"></amp-img><!--/noscript--><!-- End Facebook Pixel Code -->`

But the extension is not identifying that pixel. So I was wondering if even the extension did not identify the pixel, the pixel is loading properly and tracking the visits on my pages?

Thank you,
Rodrigo

**Comment by zhouyx** [comment]
Hello @rodrigocarlos Thank you for filing the issue. 

There are a few things that I can clarify here
1. AMP runtime schedule layout of all AMP elements on the page. `<amp-img>` is lazily loaded. If it is placed at the bottom of the page, it is possible that the pixel is not loaded properly and not track the visit.
2. AMP provides two components specifically for tracking purpose. They are [`<amp-pixel>`](https://www.ampproject.org/docs/reference/components/amp-pixel) and [`<amp-analytics>`](https://www.ampproject.org/docs/analytics/analytics-vendors#facebook-pixel). Both components support facebook pixel. Unlike `<amp-img>`, AMP runtime treats these tracking components differently and will always load them. 
You can embed them like
```
<amp-pixel src="https://www.facebook.com/tr?id=9999999999999&amp;ev=PageView&amp" layout="nodisplay"></amp-pixel>
```
or
```
<amp-analytics type="facebookpixel">
  // your configuration
</amp-analytics>
```
3. I don't have enough context on the Chrome extension. But with `<amp-pixel>` and `<amp-analytics>` the pixel should be loaded and track the visit on your site. You can verify that in the browser's Network tab.

**Comment by zhouyx** [comment]
@kristoferbaxter brought up a great point, that AMP should provide better guidance on this kind of usage. Technically it's invalid, but not what we would recommend as best approach. 

@honeybadgerdontcare is there a way to embed this kind of check to AMP validator. I know we have validator warnings, would that be a good fit? For example we can throw warning when `<amp-img>` has `width= 1, height= 1` and recommend `<amp-pixel>` as the alternative component.

**Comment by honeybadgerdontcare** [comment]
@zhouyx 	we try to avoid adding warnings unless absolutely necessary as we don't want developers to have fatigue from too many messages. are we sure that 100% of the cases where someone puts a height/width of 1 that it really should be amp-pixel?

**Comment by zhouyx** [comment]
Most of the time I think so, unless someone want to resize the image later? That's also why we think it should be a warning not an error. 
We do have this client side width=1 height=1 check for `<amp-iframe>`, but we don't want to add it to `<amp-img>` because it's a builtin element. Also that requires one to run the page to find out. 

@kristoferbaxter also suggests that we can maybe check for the image src so that it's not one of the common tracking endpoint.

**Comment by honeybadgerdontcare** [comment]
If it's not 100% of the time then that means some use cases do not necessitate the message and that means the message would always be there. This can lead to validator message fatigue and I'd like to avoid that.

**Comment by zhouyx** [comment]
@honeybadgerdontcare I see that. Thank you. Do you think what are the good places to perform these type of check? To me it sounds like an AMP optimized tool and can be a special version of validator.

**Comment by honeybadgerdontcare** [comment]
There has been some discussions around a linter for AMP pages and I think this would be an excellent fit for that. I've filed #21418 and will include your suggestion there.

**Comment by zhouyx** [comment]
Thank you for linking to the issue. Linter for AMP pages sounds a perfect fit for this type of check!

**Comment by rodrigocarlos** [comment]
Hello @zhouyx 

My Facebook pixel code in amp-img format is being loaded inside `<head>` `</ head>` (https://screenshot.net/pt/gwn03f1?). Does this mean that Facebook will normally be tracking the accesses of the AMP pages?

Thank you.

**Comment by zhouyx** [comment]
@rodrigocarlos AMP components are only allowed in document body. Could you please double check if your page is a valid AMP page?

See the example below

![image](https://user-images.githubusercontent.com/5419904/54553532-c28e5b00-4988-11e9-8d36-a1125793a1b9.png)
