### ISSUE TITLE
amp-next-page playground example does not load next page

### ISSUE THREAD

**Issue by ericandrewlewis** [ampproject/amp-by-example#2011]
The [amp-next-page playground example](https://playground.amp.dev/?referrer=ampbyexample.com&url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-next-page) does not load the next page.

I see errors in my JavaScript console:

```
Experiment amp-next-page disabled
qd @ cdn.ampproject.org/v0/amp-next-page-0.1.js:70
log.js:343 Uncaught (in promise) Resource: failed to build: amp-next-page#1: Experiment amp-next-page disabled
```

**Comment by sebastianbenz** [comment]
Yes, experiments are not yet supported. I've just filed: https://github.com/ampproject/docs/issues/2083
