### ISSUE TITLE
Add an AMP CSS Tips & Tricks Sample

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#209]
I've just learned about `.amp-mode-touch` for touch-device specific styling. I'm sure there are more such treasures buried in AMP. Let's create a sample for these. 

@dvoytenko @pbakaus @cramforce @mkhatib have you got more suggestions for things we should include?

//cc @kul3r4 @juliantoledo  @adewale

**Comment by adewale** [comment]
There are examples that can be taken from:
- https://www.ampproject.org/roadmap/ which shows some of the stuff @pbakaus talked about in his blog post: https://paulbakaus.com/tutorials/css/flexbox-freebie-auto-growing-list-for-amp-roadmap/
- https://amphtml.wordpress.com/2016/05/24/menus-sharing-and-dynamic-css-classes-in-amp/ which talks about features like amp-dynamic-css-classes: https://github.com/ampproject/amphtml/blob/master/extensions/amp-dynamic-css-classes/amp-dynamic-css-classes.md that can be used to hide or show things based on various variables.

**Comment by jmadler** [comment]
Have a look at #352, #353, and #250, which I think cover most of these cases, except flex-box specifically (somewhat covered in #251).   

Is there anything else that would be helpful?

Would it be helpful to have an additional "best practices in responsive design with AMP" sample?  Would something like that be within scope for ABE?
