### ISSUE TITLE
Support copy/pasting of code snippets

### ISSUE THREAD

**Issue by jkingyens** [ampproject/amp-by-example#214]
Currently when you try to highlight a code snippet to copy/paste, it also highlights the narrative/instructional text:

![image](https://cloud.githubusercontent.com/assets/1118200/16277297/34dad570-3867-11e6-8745-36df631e99fe.png)

It would be great if just the code was highlighted.

**Comment by sebastianbenz** [comment]
Yeah - that would be nice, but I don't see a way how we could support this.
This is why we have the link to the sample on Github.

Have you got any idea how we could solve this?

**Comment by jkingyens** [comment]
Could we use this? https://css-tricks.com/almanac/properties/u/user-select/
I'd like to get copy pastes added to the analytics so we can track usage/value from this

**Comment by sebastianbenz** [comment]
The analytics idea is great! I'm not a fan of the idea of making the doc text non-selectable though.

**Comment by jkingyens** [comment]
Okay, may I ask the reason? Is this not best practices or something?

**Comment by sebastianbenz** [comment]
Personally I hate when websites do this. Scenario: I want to quickly copy a sentence in the doc to paste it into a chat. This wouldn't work anymore. 

How about adding a copy/paste icon which opens another window only showing the code without comments?

**Comment by jkingyens** [comment]
yes, this would be a good solution

**Comment by kul3r4** [comment]
Code snippets can now be selected and copied.
