### ISSUE TITLE
Menu headers don't provide a visual cue that they're expandable

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#218]
![nzz2esbrxgw](https://cloud.githubusercontent.com/assets/435158/16351292/69fa2e50-3a19-11e6-8111-893c41dffd39.png)

**Comment by juliantoledo** [comment]
Any ideas on how to improve it?
We used this design: https://material.google.com/

**Comment by sebastianbenz** [comment]
We could also expand the first accordion on the homepage. Would this be enough?

**Comment by jmadler** [comment]
Some possible solutions could be:

* Expand all by default
* Expand current by default (e.g. first on index page)
* Use some icon as a cue that it's a header (e.g. plus or caret)
* Use some background color as a cue that it's a header

**Comment by jmadler** [comment]
Obsolete following restyle
