### ISSUE TITLE
experimental icon in menu doesn't render after a few reloads

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#220]
![tfuetryu099](https://cloud.githubusercontent.com/assets/435158/16351383/0d4b5e1c-3a1a-11e6-867b-da95f9df741a.png)

**Comment by juliantoledo** [comment]
Known issue in amphtml:
https://github.com/ampproject/amphtml/issues/3586

**Comment by juliantoledo** [comment]
We may need to investigate further, it seems to be live and the issues is still happening.

**Comment by jmadler** [comment]
Obsolete following restyle
