### ISSUE TITLE
AMP experiments launches errors sometimes

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#229]
From time to time, when opening a page which is using experimental component, I get an error, snapshot [here](https://www.dropbox.com/s/ceh2o2bzd1wx2it/error-experiment.png?dl=0). It normally solves just refreshing the page.

**Comment by sebastianbenz** [comment]
Where does the exception happen? Can you debug?

**Comment by sebastianbenz** [comment]
@kul3r4 Is this still happening?

**Comment by kul3r4** [comment]
Haven't seen this in a while, I will close it.
