### ISSUE TITLE
Video Players samples

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#252]
amp-brid-player
amp-jwplayer
amp-kaltura-player
amp-reach-player
amp-springboard-player
amp-vimeo

**Comment by jmadler** [comment]
Would it make sense also to have a separate video player section now that there's so many?

**Comment by sebastianbenz** [comment]
Yeah -  things start getting messy. I've proposed new categories here [here](#238)  .

**Comment by sebastianbenz** [comment]
I think we now have samples for all.
