### ISSUE TITLE
Sample for amp-mustache

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#254]

**Comment by jmadler** [comment]
Looking at amp-mustache -- is there a meaningful use case we could highlight?  It seems useful as a primitive for other amp tags (e.g. amp-list), but I'm having trouble coming up with a standalone use case.

**Comment by sebastianbenz** [comment]
There's no standalone use case, but it would be could to highlight the
templating possibilities.

**Comment by jmadler** [comment]
I took a crack at it and submitted a PR.  Let me know what you think about this approach.
