### ISSUE TITLE
Sample for Product Detail Page

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#255]

**Comment by borisf** [comment]
Already have a PR https://github.com/ampproject/amp-by-example/pull/240

**Comment by ithinkihaveacat** [comment]
Quite a few [validation errors](https://validator.ampproject.org/#url=https%3A%2F%2Famp-ecommerce-analyics.firebaseapp.com%2FProduct_Listing_Sample.html) at the moment. (Most related to the search form?) Do I need to turn on an experiment or something?

**Comment by kul3r4** [comment]
Yes, amp-form is experimental.
[https://amp-ecommerce-analyics.firebaseapp.com/Product_Listing_Sample.html](https://amp-ecommerce-analyics.firebaseapp.com/Product_Listing_Sample.html) is not ready yet to be moved to ampbyexample: in that page we extracted a lot of css which shouldn't leave in the sample itself.
