### ISSUE TITLE
Can not apply padding to social share button

### ISSUE THREAD

**Issue by ardianta** [ampproject/amp-by-example#263]
When I try to apply `padding` to social share button the icons is following the element's size.
![](http://i.imgur.com/jNwA5Dv.png)

**Comment by kul3r4** [comment]
Hi, thanks for your feedback.
This doesn't seem to be related to ampbyexample but to the amp-social-share component itself.
Please file a bug on [https://github.com/ampproject/amphtml](https://github.com/ampproject/amphtml).
