### ISSUE TITLE
Google fonts have a massive impact on page load

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#299]
Latest lighthouse reports show that google fonts have a massive impact on page load:

<img width="848" alt="screen shot 2016-08-01 at 13 58 43" src="https://cloud.githubusercontent.com/assets/380472/17294725/5dc2a6d6-57f0-11e6-9774-06cb00f211e8.png">

How can we avoid this?

//cc @adewale

**Comment by ithinkihaveacat** [comment]
There's quite a lot of [font variants specified](https://github.com/ampproject/amp-by-example/blob/5066129987cc2f9dd56149617342cde466bee980/templates/head.html#L13) (regular,bold,italic,thin,light,bolditalic,black,medium)--are all of those needed?

Also, which page was this? I tried loading <https://ampbyexample.com> on a machine without Roboto installed, and it seemed to only load 3 font files, at just under 40k (514k total). (Wondering if Lighthouse is accounting for font loads correctly.)

**Comment by cramforce** [comment]
If you want actually fast pages, get rid of the fonts. 4 seconds seems like a bit of a outlier, though. I'd question the cache methodology of lighthouse.

**Comment by addyosmani** [comment]
cc @brendankenny @paulirish

**Comment by crhym3** [comment]
@sebastianbenz how did you test it, using the chrome extension?

@cramforce I think the point is to also test with cold cache, in which case lighthouse wouldn't have any cache methodology.

@ithinkihaveacat even if you don't have the font installed, it could be already in your browser cache if you previously visited other sites using the same font + variants.

**Comment by sebastianbenz** [comment]
@crhym3 I used the chrome extension. The result usually varies between 1-5s for Google fonts.
@ithinkihaveacat thanks for the suggestion, I removed some of the unused fonts in 37ab9b1c6c5178358ae85d4c8c1b8d4e974db302

**Comment by crhym3** [comment]
@sebastianbenz this is what I get for https://ampbyexample.com:

![screenshot from 2016-08-02 12 29 25](https://cloud.githubusercontent.com/assets/25405/17325616/cf7acbc0-58ac-11e6-98b0-7e305c3dab92.png)

**Comment by ithinkihaveacat** [comment]
@sebastianbenz Did removing fonts make a difference? If so, Lighthouse is probably doing the wrong thing and (for example) loading all referenced fonts, because an incognito browser on a system with no Roboto installed only loads (and hence only uses) 3 fonts totaling 40k for <https://amybyexample.com>.

**Comment by brendankenny** [comment]
> I'd question the cache methodology of lighthouse.

Lighthouse does currently test using an empty cache. Benchmarking load with a warm cache is certainly something that could be added. It also only tests network loading with a simulated 3G connection, which can obviously make requests take a while, especially dependent chains of requests.

That said, Lighthouse doesn't do any loading itself. It just sets those network conditions in Chrome, lets Chrome load the page as it will, and then Lighthouse analyzes Chrome's network log. You should get approximately the same numbers by disabling the cache and throttling the network to "Regular 3G" in DevTools and checking the Network panel for load times.

If you get radically different numbers, that's a bug in Lighthouse, not some deeper loading insight it's giving you :)

**Comment by paulirish** [comment]
I was unable to reproduce the 3000ms for the google fonts css above. In my runs, it typically takes about as much time as the pngs on the page.  I think it might have been a temporary network snafu, unless @sebastianbenz can reproduce this reliably.

**Comment by sebastianbenz** [comment]
@paulirish, @brendankenny Ok - might have been a network thing then. My various tries running lighthouse report anything between 8x-100. Would it make sense to check the network connection before running tests? e.g. warn if ping to google.com takes to long?

Thanks for looking into this!
