### ISSUE TITLE
Extract all references to ampbyexample.com from samples

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#309]
This enables running ABE on different hosts, e.g. staging or for demoing two different PWA concepts. 

Question: how should we treat the canonical reference, should it always go to ambyexample.com?

Depends on #300 

//cc @kul3r4 @jkingyens

**Comment by jkingyens** [comment]
ampbyexample is just standalone amp right? shouldnt the canonicals point to the subdomains to keep everything sandboxed isolated? what is the advantage of pointing these canonicals back to the root domain?

**Comment by sebastianbenz** [comment]
Having the canonicals point to the subdomains is OK as long as we make sure that all other subdomains and instances can't be accessed by the GoogleBot to avoid duplicate results in Search.
