### ISSUE TITLE
`src/video/*` static assets are not deployed.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#321]
I get `404` for https://ampbyexample.com/video/tokyo.mp4 (Noticed from https://ampbyexample.com/components/amp-video/ example). The file is in the source, I think just not deployed.

Problem does _NOT_ exist for other assets like images in `src/img/*` so https://ampbyexample.com/img/Hovawart.jpg works fine.

**Comment by sebastianbenz** [comment]
Thanks for reporting!
