### ISSUE TITLE
Mark experimental samples

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#33]
[] append `[experimental]` to example name in overview page
[] inject src/templates/experiment.html into example template if experimental flag is set (see #32)

**Comment by juliantoledo** [comment]
@sebastianbenz PTAL?

**Comment by juliantoledo** [comment]
[] inject src/templates/experiment.html into example template if experimental flag is set (see #32)
fixed by https://github.com/ampproject/amp-by-example/pull/73.

We need to work on:
[] append [experimental] to example name in overview page
