### ISSUE TITLE
Curly brackets in amp-list and amp-mustache conflict with Golang template

### ISSUE THREAD

**Issue by devilbags** [ampproject/amp-by-example#331]
I see you guys are using Go as your backend. How do you resolve the problem that they both uses curly brackets in templates?
For example, in the amp-list example, I am able to avoid the problem by using this 
```
<ul>
            <amp-list width=auto
                height=100
                layout=fixed-height
                src="//localhost:8080/comments.json">
            <template type="amp-mustache">
                <li>                   
                <p>{{`{{textDisplay}}`}}</p>
                </li>
            </template>
            </amp-list>
</ul> 
```
The above code reads and display information from JSON file correctly. However, amp-img tag doesn't seem to work
```
<ul>
            <amp-list width=auto
                height=100
                layout=fixed-height
                src="//localhost:8080/comments.json">
            <template type="amp-mustache">
                <li>   
                <amp-img src="{{`{{imageUrl}}`}}"
                width="48"
                height="48"
                layout="responsive"
                alt="an image"></amp-img>                   
                </li>
            </template>
            </amp-list>
</ul> 
```
The resulting image src is always `http://localhost:8080/%7b%7imageUrl%7d%7d"` instead of reading the image url in the JSON file

**Comment by sebastianbenz** [comment]
We change the template delimiters for our GO templates. [Here](https://github.com/ampproject/amp-by-example/blob/master/backend/product-listing.go#L80) is an example. It might make sense to [create an issue](https://github.com/ampproject/amphtml/issues/new) for amp-list to support changing the template delimiters.
