### ISSUE TITLE
Image resizing in lightbox on click

### ISSUE THREAD

**Issue by abeck000** [ampproject/amp-by-example#340]
Expected behavior:
- As the user, I should be able to click the image, trigger the lightbox to make the image bigger, and the image should load once and keep the same proportions in the lightbox. 

Actual behavior:
- As the user, I click the image, trigger the lightbox to make the image bigger, and the image that loads is vertically condensed, then the image reloads and adjusts itself to the correct proportions. 

++ I'm not sure if this is an actual component issue or implementation on Amp by example issue....++

Link: https://ampbyexample.com/components/amp-image-lightbox/

FYI @sebastianbenz @aghassemi @ericlindley-g

**Comment by aghassemi** [comment]
Thanks for reporting. This is a component bug. Moved it to https://github.com/ampproject/amphtml/issues/4716, please subscribe to that issue for updates.

**Comment by sebastianbenz** [comment]
Closing this as it is tracked in another component.
