### ISSUE TITLE
Social Share component - how to create more?

### ISSUE THREAD

**Issue by ScotsScripts** [ampproject/amp-by-example#344]
I haven't had much luck creating new social sharing components but a project I'm working on "needs" instagram and vimeo sharing buttons. I'd like to stick with amp components. Are there any pre-made components out there, in addition the one provided by amp-by-example? 

Thanks.

**Comment by sebastianbenz** [comment]
All pre-configered social providers are listed [here](https://github.com/ampproject/amphtml/blob/a40eb97b841d94c9ba0e0eae950c2ccf3465c334/extensions/amp-social-share/amp-social-share.md).
