### ISSUE TITLE
Amp-Accordion content when opening is not pushing page up

### ISSUE THREAD

**Issue by ScotsScripts** [ampproject/amp-by-example#347]
If an accordion item at the bottom of the page, opening it does not display it's content unless the user scrolls, but there's nothing that gives the user a hint that more content appeared. Is there any way around this?

**Comment by sebastianbenz** [comment]
You can show different icons depending on the accordion state.

**Comment by ScotsScripts** [comment]
Nice! I didn't notice that before (kind of new at the AMP game), thanks.
