### ISSUE TITLE
ABE munging some CSS classes

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#355]
ABE seems to be munging some CSS classes, such as those in #354

**Comment by sebastianbenz** [comment]
Can you please provide samples for the conflicts.

**Comment by jmadler** [comment]
I'm not sure that it's a rule in style.css that's munging -- it might be part of the templating process.  

Have a look at the "helper css class" sample from PR #354 and compare to [this gist](https://gist.github.com/jmadler/e9182dcf202dc4ec9058784d6dbf4bdb)

I'm unfamiliar with the templating process but if you'd like I can dive into this deeper to address it.

**Comment by jmadler** [comment]
Closed as unreproducible as of now.
