### ISSUE TITLE
Upgrade node and nvm version for Travis

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#365]
Builds are failing on the CI - [example](https://travis-ci.org/ampproject/amp-by-example/jobs/158655574) when running 'gulp lint test validate && gulp clean build' and can't reproduce locally, would like to give it a go to upgrade to newest versions of node and nvm.
@rowan-m @sebastianbenz Any thoughts?

**Comment by sebastianbenz** [comment]
Yup - upgrading node seems like the way to go. Just realised we are still using 4.1 on travis.
