### ISSUE TITLE
AMP Live List Example not Updating?

### ISSUE THREAD

**Issue by randallbpotter15** [ampproject/amp-by-example#368]
https://ampbyexample.com/components/amp-live-list/

I don't see new cards being added or the score updating.

**Comment by kul3r4** [comment]
Hi,
could you check the following:

- Do you have a cookie named "ABE_AMP_LIVE_LIST_STATUS" created?If yes what is the value? If it's greater than 10, please try to delete the cookie and reload the page. The sample stops after 10 cards.
- Does the button "YOU HAVE UPDATES" appear? It should be on the right column around where the text "Implementing a live blog" is.

**Comment by randallbpotter15** [comment]
Thank you!  It was cookie related and it would help if I read the documentation in the left column telling me to delete them :)

_(It might be good to reformat or highlight that section or provide a "restart example" button?)_
