### ISSUE TITLE
"Add to Cart" functionality using amp-form

### ISSUE THREAD

**Issue by jasti** [ampproject/amp-by-example#369]
Show a sample page showing a bunch of items that have number input fields. Preferably using the existing e-commerce examples.

User can edit the items on the input field (either increment or decrement) and press "add to cart" to land on another page . (The non-amp that will display the state of the cart (for v1 this page doesn't itself need to be interactive)

**Comment by sebastianbenz** [comment]
Have you got a non-AMP sample page?

**Comment by jasti** [comment]
This is just from Amazon.com on mWeb. They have DD instead of an increment/ decrement and then "add to cart".
<img width="318" alt="screen shot 2016-09-21 at 6 10 21 pm" src="https://cloud.githubusercontent.com/assets/2366341/18734199/bdc141a6-8026-11e6-9155-36e1966009be.png">

Submitting results in updating the cart. 
<img width="336" alt="screen shot 2016-09-21 at 6 11 14 pm" src="https://cloud.githubusercontent.com/assets/2366341/18734205/e1738ae6-8026-11e6-8e8f-0f3f4fcf28ff.png">

**Comment by sebastianbenz** [comment]
Thanks. DD makes it a lot easier.

**Comment by jasti** [comment]
Cool, DD sounds good.

**Comment by sebastianbenz** [comment]
Do we want a lightbox showing a dialog with two buttons: Go to Cart | Continue Shopping?

**Comment by jasti** [comment]
That would be nice. I was thinking of something simple like navigating to the next page (AMP or non-AMP) showing the number of items added to the cart but yeah, lightbox sounds great.

**Comment by mkhatib** [comment]
@sebastianbenz 

> Do we want the add to cart button to trigger a lightbox showing a dialog with two buttons: Go to Cart | Continue Shopping? (if that's possible)

That's possible. See our `forms.amp.html` for an example `on=submit-success:lightbox`. 

> simple like navigating to the next page

This is currently not supported for `POST` but can be done for `GET` requests. We're discussing adding a way to redirect user to another page after a submission but still not in.

**Comment by sebastianbenz** [comment]
Lightbox is currently not possible as we can't implement a continue shopping functionality via the AMP Cache. On iOS, 3P cookies might be disabled, which means the seller can't create cookies to store a user id. 

A possible solution would be to support variable substitutions for amp-form actions. Then the seller could associate a shopping cart with the CLIENT_ID.

**Comment by kul3r4** [comment]
This is also related to https://github.com/ampproject/amphtml/issues/5937

**Comment by mkhatib** [comment]
var substitution is now allowed in forms hidden inputs (including `CLIENT_ID`) under experiment `amp-form-var-sub` in Canary. See `examples/form.amp.html` for an example as we haven't documented this yet.

**Comment by sebastianbenz** [comment]
Thanks for letting us know! @kul3r4 can you update the sample?

**Comment by kul3r4** [comment]
Thanks for letting me know, will take a look.

**Comment by kazi-shahin** [comment]
Do you can leave a sample code for Amazon Ad script with AMP compatible ?
