### ISSUE TITLE
Poll sample using amp-form

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-by-example#372]
- a single question with 4 options or so
- our server could store responses anonymously, so the results displayed would just show the aggregate totals to-date
- would be awesome to have an option to just see the results without casting a vote

**Comment by mkhatib** [comment]
> a single question with 4 options or so

Checkout the `examples/form.amp.html` for a sample poll I created to get started on this.

**Comment by kul3r4** [comment]
@rudygalfi we deployed the [sample](https://ampbyexample.com/samples_templates/poll/preview/).

**Comment by rudygalfi** [comment]
Awesome!

**Comment by rudygalfi** [comment]
cc @ericlindley-g

**Comment by mkhatib** [comment]
@kul3r4 this is pretty cool! Thanks for putting it out there! If you guys have a simple datastore on the ampbyexample server it would be cool to actually collect and store results 😄 - I played around the example to see if my voting is changing the result.

Can we get more examples like these, specifically an example that uses `amp-slidescroll.goToSlide` action to advance to the next question when the current one is answered - so a multi-step quiz/poll. Something like the following:

```html
<amp-carousel id="quiz" type="slides" >
<form id=q1 ... on="submit:quiz.goToSlide(index=1)">
   ... fields for the first question with on=change:q1.submit ...
</form>
<form id=q2 ... on="submit:quiz.goToSlide(index=2)">
   ... fields for the second question with on=change:q2.submit ...
</form>
<form id=q3 ...on="submit:quiz.goToSlide(index=3)">
   ... fields for the third question with on=change:q3.submit ...

  ... templates to render results for the entire quiz ...
</form>
</amp-carousel>
```

I have not tried this but it should work in theory.

**Comment by rudygalfi** [comment]
We should discuss quiz in #371. :)

**Comment by kul3r4** [comment]
@mkhatib the results are already stored, this is how you are able to see the percentage of answers increasing.

**Comment by kul3r4** [comment]
Close via #510
