### ISSUE TITLE
Make "View on Github" button more discoverable on component pages

### ISSUE THREAD

**Issue by spacedino** [ampproject/amp-by-example#373]
Use case:
As a developer who is looking to directly copy and paste the examples, given I cannot highlight the source code because it is in a table, I need another way to get it. 

Current behavior:
I don't notice "View on Github" button is in the top right corner of the page. I have to ask someone. 

Expected behavior:
Make the CTA more prominent and closer to the source code where a user would be looking for it. Maybe change the text as well to something like "download source code from Github" ; "get source code" ; etc. 

I've attached what it could look like on a large screen and small.
![getcode_cta_lg](https://cloud.githubusercontent.com/assets/7339798/18652145/d4913038-7e84-11e6-9f98-40015a1bbac1.png)
![getcode_cta_sm](https://cloud.githubusercontent.com/assets/7339798/18652144/d4900258-7e84-11e6-916c-055e9e3f6548.png)

**Comment by sebastianbenz** [comment]
@abeck000 I've (hopefully) improved the UI to make it easier to get to the full source code: there is now a "Edit in Playground" button. Sample: https://amp-by-example-staging.appspot.com/advanced/how_to_create_interactive_amp_pages/

Let me know what you think. Thanks!

**Comment by kul3r4** [comment]
This is now solved with the last Ui update where "Edit on github" is immediately below the title.
