### ISSUE TITLE
Facebook comment on Google AMP

### ISSUE THREAD

**Issue by tungvn** [ampproject/amp-by-example#379]
I found [here](https://ampbyexample.com/components/amp-facebook/) all supporting for facebook, include FB post, video... but nothing for comment.

Please support facebook comment both :+1:

**Comment by kul3r4** [comment]
Hi @tungvn thanks for reviewing the sample.
I notice you opened an issue [here](https://github.com/ampproject/amphtml/issues/5219) which is the best place to keep the conversation, so I am gonna close this issue.
