### ISSUE TITLE
Please consider getting involved in AMP Ads at Prebid. 

### ISSUE THREAD

**Issue by mercuryyy** [ampproject/amp-by-example#381]
Prebid.org or github.com/prebid/Prebid.js/issues  is an open source header bidding solution that is currently adapted by all major ad exchanges and networks. 

There is an open ticket about AMP support using prebid ("https://github.com/prebid/Prebid.js/issues/362")
But i dont think it will get much attention with the involvement of someone from the AMP team. 

currently 1000's of publishers are using prebid.org mostly high traffic and very large publishers, implementing Prebid in AMP will probably result in 100's of millions more users visiting an AMP page instead of a non AMP due to some of us using Prebid changing to AMP.  

#MakeItFaster!

**Comment by sebastianbenz** [comment]
I'm sorry, but this is the wrong place for such a request.

**Comment by mercuryyy** [comment]
@sebastianbenz where is the right place?

**Comment by mercuryyy** [comment]
@sebastianbenz bump

**Comment by sebastianbenz** [comment]
Prebid.org looks like the best place to discuss these things (it's open source as well, isn't it). You could also file a feature request on ampproject/amphtml.
