### ISSUE TITLE
Link to docs from example

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp-by-example#394]
E.g. this page https://ampbyexample.com/components/amp-video/ should link to the main docs.

**Comment by adewale** [comment]
Good idea.

For amp-video should we link to: https://github.com/ampproject/amphtml/blob/master/builtins/amp-video.md or https://www.ampproject.org/docs/reference/components/amp-video

Once you've decided which URL to use we can do that in all component-specific examples.

**Comment by sebastianbenz** [comment]
Migrated all existing links. We should make sure that each sample also links to the official docs.

**Comment by kul3r4** [comment]
@sebastianbenz can we close this?

**Comment by sebastianbenz** [comment]
yes
