### ISSUE TITLE
amp-carousel extrange resize-blinks on Firefox 49.0.1

### ISSUE THREAD

**Issue by barruka** [ampproject/amp-by-example#395]
Checking this url: https://ampbyexample.com/components/amp-carousel/ on Firefox 49.0.1 you can see how images make a extrange resize and blinks on third example (layout="responsive" and autoplay).

On second example (type="slides") after hitting right/next button extrange resize blinks starts.

On first example (layout="fixed-height") it works perfectly.

**Comment by sebastianbenz** [comment]
This sounds like a problem with the AMP runtime. Can you please file a big [here](https://github.com/ampproject/amphtml/issues/new). Thanks!
