### ISSUE TITLE
Consider using JavaScript for the backend code as well

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#400]
Since AMP uses a client library written in JavaScript, it's expected that the vast majority of AMP developers will be familiar with JavaScript. The same can't be said about Go, which we've been using to write the backend code in.

It would be easier for AMP users to understand client-server examples (e.g. amp-form) if the server code was JavaScript as well (i.e. Node) - no need for a [context switch](http://www.johndcook.com/blog/2011/06/09/mental-context-switches-are-evil/).

Installation would also be simpler - just Node, no [Go SDK](https://github.com/ampproject/amp-by-example/pull/401).

**Comment by adewale** [comment]
Rewriting the entire back-end in Javascript seems like a lot of work with limited value.
Do you have a rough estimate of the amount of work that would be involved and the time it would take?

**Comment by sebastianbenz** [comment]
We considered this at the beginning for the same reasons, but went with Go as app engine deployment is easier (once you've got the tools installed). 

To be honest, I didn't expect that many samples would require custom backend logic - which was wrong. I probably would do it differently if starting over again. Migrating to node shouldn't be too much work (1-2 days max). I am not sure though whether it is really worth the effort...

**Comment by dandv** [comment]
How feasible would it be to use Node/Express for new backend code going forward, and keep the Go samples?

**Comment by jkingyens** [comment]
I don't think we should use a mix of Node and Go. Either we convert
everything and move to Node or keep Go. As far as deployment goes, we could
drop in a Dockerfile, which is language agnostic and cloud independent.
Docker has one-click installers on Mac, Windows and Linux.

**Comment by sebastianbenz** [comment]
+1 to not mixing PLs and easier deployment

I've been planning to refactor the Go backend in the near future to remove redundancies and to create a proper API for sample authors. If we want to switch to Node, this is the right time.

//cc @kul3r4

**Comment by kul3r4** [comment]
Closing this as we don't plan to move to Node anytime soon.
