### ISSUE TITLE
Resource not found when running locally, ic_play_circle_filled_white_24dp_1x

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#404]
After git clone, npm install and gulp, if I navigate to http://localhost:8000/components/amp-form/, I get a these errors:

```
ic_play_circle_filled_white_24dp_1x:1 GET http://localhost:8000/img/ic_play_circle_filled_white_24dp_1x 404 (Not Found)

error.js:75 task failed: amp-img#4#L amp-img#4: Failed to load: http://localhost:8000/img/ic_play_circle_filled_white_24dp_1x​​​Ed @ error.js:75

log.js:384 Uncaught Error: task failed: amp-img#4#L amp-img#4: Failed to load: http://localhost:8000/img/ic_play_circle_filled_white_24dp_1x​​​ _reported_
```

![image](https://cloud.githubusercontent.com/assets/33569/19209313/cb25dfda-8cbc-11e6-822e-64299362c81f.png)

Is this expected?

**Comment by sebastianbenz** [comment]
Not really - can you check if the image is in the dist folder?

**Comment by dandv** [comment]
Thanks for the fix. The issue occurs only on the very first navigation to http://localhost:8080/components/amp-form/. Subsequent page refreshes work.
