### ISSUE TITLE
Differences between amp-by-example and /amphtml/examples/

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#405]
Should the [examples directory in the main amphtml repo](https://github.com/ampproject/amphtml/tree/master/examples) be migrated here, or linked from here? Any reason they're split across two repos?

I was looking into `<amp-form>` and noticed that the documentation [points to their own "full example"](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#events) several times.

**Comment by adewale** [comment]
The examples in the main repo are written by the core eng team and serve as the initial rough verification that a feature works. The examples here are meant to show a wide range of developers how to take advantage of AMP for more complex scenarios that often combine multiple AMP components.

I prefer the solution proposed in #394 where we link to the official docs and/or the core eng team's examples in these examples.
