### ISSUE TITLE
flickering carousel

### ISSUE THREAD

**Issue by andorea** [ampproject/amp-by-example#419]
Hi,

the last carousel on the image galleries example page has a problem:
https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/
When I scroll to the second or third slide, the image is resized several times and flickers. Sometimes the resizing stops after a second, but sometimes it goes on and on. This happens both with Chrome and Firefox on Windows 10 and on Mac OS. There seems to be more flickering with activated developer tools (chrome and firefox), but even without developer tools there still is some flickering.
Finally, when the flickering stops, there is a white gap below the image that impairs the layout. The slide does not fill the container.

I planned to use such a slider for our website. Where can I address this problem?

Greetings,
 Andrea

**Comment by sebastianbenz** [comment]
This looks like an error in the AMP runtime. Please follow this [bug](https://github.com/ampproject/amphtml/issues/5544#issuecomment-253188625).

**Comment by sebastianbenz** [comment]
..and thanks for reporting!
