### ISSUE TITLE
Create an example that shows all AMP video types in both an amp-carousel and an amp-according

### ISSUE THREAD

**Issue by adewale** [ampproject/amp-by-example#42]
Use the list of AMP video types in #41 to build one example that shows both the carousel and the accordion on the same page. This will allow people to easily compare and contrast the UX of both components.

**Comment by kul3r4** [comment]
@adewale still trying to develop this example.
I am having problems displaying correctly amp-facebook and amp-instagram inside amp-carousel, bugs below:
https://github.com/ampproject/amphtml/issues/2661
https://github.com/ampproject/amphtml/issues/2662

**Comment by adewale** [comment]
Thanks for the update and for filing the bugs.
