### ISSUE TITLE
Uncaught Error: form target attribute is required: form​​​

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#426]
Encountered this error on the "Form Submission with Page Update" section of the AMP Form demo locally, because the XHR forms lack the [required](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#attributes) `target` attribute.

![image](https://cloud.githubusercontent.com/assets/33569/19399340/e95b6198-9205-11e6-96eb-406be0b1cf12.png)

**Comment by kul3r4** [comment]
@mkhatib @rudygalfi When using XHR forms, what's the point of specifying target? What can be an use case?

**Comment by mkhatib** [comment]
Yeah we're aware of this and have an [issue to track this](https://github.com/ampproject/amphtml/issues/5607), we'll update this ASAP.

Please update the samples currently yo have `target` attribute all the time.

**Comment by sebastianbenz** [comment]
Done.
