### ISSUE TITLE
JSON metadata not rendering correctly in code panel

### ISSUE THREAD

**Issue by jkingyens** [ampproject/amp-by-example#432]
If you view the live blog sample:

https://www.ampbyexample.com/samples_templates/live_blog/

If you scroll down to where the JSON meta-data is displayed in the code panel, the syntax is not being highlighted correctly and characters are missing/escaped (like quotes): 

![screen shot 2016-10-17 at 5 08 45 pm](https://cloud.githubusercontent.com/assets/1118200/19460005/6cf8a816-948c-11e6-88c6-ee667530d9e8.png)

**Comment by sebastianbenz** [comment]
The formatting got broken with your PR
<https://github.com/ampproject/amp-by-example/pull/412>. Would be great if
you could fix it. Syntaxhighlighting is something we can't fix right now.
The syntaxhighlighting happens at compile time.
