### ISSUE TITLE
Add markup to show page outline in search results

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#442]

**Comment by sebastianbenz** [comment]
@rowan-m any updates on this? Or could you provide some resources on how to do this?

**Comment by rowan-m** [comment]
https://developers.google.com/search/docs/data-types/breadcrumbs

So, what's needed is something like:
```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://ampbyexample.com/advanced/",
      "name": "Advanced"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://ampbyexample.com/advanced/video_carousels_with_amp-carousel/",
      "name": "Video Carousels with amp-carousel"
    }
  }
  }]
}
</script>
```

The problem I was having was working out where to extract the currently selected category and page to populate it in the metadata template.

**Comment by sebastianbenz** [comment]
Thanks. Implementing something like this should be easy now, for a sample
see templates/menu.html.
