### ISSUE TITLE
Search sample using amp-form

### ISSUE THREAD

**Issue by jasti** [ampproject/amp-by-example#445]
Would be great to populate dynamic results below the search field as a user begins to type in the search box.
![image](https://cloud.githubusercontent.com/assets/2366341/19629550/76570a3e-9945-11e6-8bcc-9cc858bdeae0.png)

Once the user clicks on a result, they can be sent to a non-AMP page.
@mkhatib is this possible?

CC  @rudygalfi

**Comment by jasti** [comment]
I guess it's this issue: https://github.com/ampproject/amphtml/issues/3403
Not sure of the status since forms has launched.

**Comment by sebastianbenz** [comment]
I don't think it's supported yet, but we definitely should create a sample once it's there.

**Comment by mkhatib** [comment]
@jasti yeah that issue and [this regarding a debounced-input event](https://github.com/ampproject/amphtml/issues/5702) - that would allow implementation of as-you-type kind of interactions. 

Currently the only support is when the user hit return in a search field. So this could be the sample to create for now and once we have the `debounced-input` event we can upgrade the sample to use that, what do you think?

**Comment by kul3r4** [comment]
[https://ampbyexample.com/advanced/autosuggest/preview/](https://ampbyexample.com/advanced/autosuggest/preview/) implements an interactive autosuggest form field
