### ISSUE TITLE
[amp-form] Add favorite sample

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#454]
We should add a favorite sample, now that [#4272](https://github.com/ampproject/amphtml/issues/4272) has been implemented. We should also explore the general possibilities of amp-form auto submit. How about creating two samples:
1. auto submit for different form components in amp-form sample
2. proper favorite sample in advanced

@dandv wdyt? do you want to take a stab at it?
@kul3r4, @mkhatib  FYI

**Comment by mkhatib** [comment]
I believe @dandv was already working on this. @dandv that PR @sebastianbenz links to still not deployed but should be in Canary in a week and prod in 2 weeks. Once that is in, do you have everything to implement this?

**Comment by dandv** [comment]
I'd love to take a stab at this, since it's close to the star rating extension I've been wanting to implement (#2691). Perhaps favoriting should be an extension too though?

**Comment by sebastianbenz** [comment]
You could implement both 😀. We could create a new advanced sample, something like: "Favorites & Stars with amp-form".

**Comment by kul3r4** [comment]
[https://ampbyexample.com/advanced/favorite_button/](https://ampbyexample.com/advanced/favorite_button/) implements this
