### ISSUE TITLE
Create an amp-app-banner example

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amp-by-example#464]
We currently do not have an [amp-app-banner](https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/amp-app-banner.md) example. Should we have one?

**Comment by sebastianbenz** [comment]
Of course!

**Comment by sebastianbenz** [comment]
I started a sample here
<https://github.com/sebastianbenz/amp-by-example/tree/amp-app-banner>, but
couldn't get it to working...feel free to take over.

**Comment by juliantoledo** [comment]
Cool, I will take a look :)

**Comment by sebastianbenz** [comment]
Done and deployed.
