### ISSUE TITLE
Make amp-form samples work via AMP Cache

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#466]
https://cdn.ampproject.org/c/s/ampbyexample.com/components/amp-form/ returns errors.

//cc @ithinkihaveacat

**Comment by ithinkihaveacat** [comment]
From https://cdn.ampproject.org/c/s/ampbyexample.com/components/amp-form/preview/:

![screen shot 2016-11-05 at 11 17 39](https://cloud.githubusercontent.com/assets/51244/20029642/92516e38-a349-11e6-92b0-18d0651ed627.png)
