### ISSUE TITLE
Shorten text in code sections

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#48]
Long texts in the sample files is often required (e.g. amp-carousel), but bloats the code sections. Let's automatically shorten text between html tags that is longer than 50 chars, e.g.

```
<p>
  This is a very very very very very very very very very veryvery very very long text
</p>
```

becomes:

```
<p>
  This is a very very very very very very very ...
</p>
```

**Comment by kul3r4** [comment]
@sebastianbenz This is now solved by the new layout. Can we close it?

**Comment by sebastianbenz** [comment]
thanks
