### ISSUE TITLE
Add Schema in all the examples

### ISSUE THREAD

**Issue by kaushikgandhi** [ampproject/amp-by-example#482]
Hi,
First of all I would like to thankyou for your wonderful contribution towards AMP, 

Even though all the amp validators will pass your page, but you will get the errors like this in webmaster tool 
![screen shot 2016-11-16 at 2 39 26 pm](https://cloud.githubusercontent.com/assets/2167564/20342276/d38363ce-ac0f-11e6-928c-551e9c966d7c.png)

Please add schemas in all the examples. Or else people will make mistakes who will follow you blindly.

**Comment by sebastianbenz** [comment]
Metadata is only required for articles that should appear in the Top Stories News Carousel (and this is what the search console error is about). Metadata is not required for AMPs to appear in the search results. 

We don't include metadata in the samples as the article markup doesn't fit the samples + some samples define their own metadata markup which makes things even more confusing.
