### ISSUE TITLE
Broken a4a banner for preview

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#483]
When opening https://ampbyexample.com/amp_for_ads_a4a/a4a_banner_ad/preview/, the banner does not load.
Inspecting the page, I found:
```
<a target="_blank" href="http://localhost:8000/amp_for_ads_a4a/a4a_banner_ad/">
     <amp-img src="http://localhost:8000/img/amp-300x250.jpg" width="300" height="250" alt="a4a image" class="-amp-element -amp-layout-fixed -amp-layout-size-defined -amp-layout amp-notsupported" id="AMP_1" style="width: 300px; height: 250px;">
  <img amp-img-id="AMP_1" alt="a4a image" class="-amp-fill-content -amp-replaced-content -amp-ghost" src="http://localhost:8000/img/amp-300x250.jpg"></amp-img></a>
```

In the gulpfile, the host comes from 
`args.a4aEmbedUrl = config.api.host + '/' + example.targetPath();`
couldn't find where it goes wrong, @sebastianbenz can you help?

**Comment by sebastianbenz** [comment]
My fault. Deployed to the api app engine without rebuild. Fixed by re-deploy.
