### ISSUE TITLE
The form page description is not consistent

### ISSUE THREAD

**Issue by winstonma** [ampproject/amp-by-example#485]
In [AMP Form](https://ampbyexample.com/components/amp-form/) page, it said `Use type="telephone" for input fields that should contain a telephone number.` but on the code it shows `type="tel"`.

Also when I use a mobile browser and highlight the telephone field it shows me text input keyboard but I would expect the numpad to be popped out. Lastly in the telephone field even I type in text it will let me submit. How could I validate the input is a valid phone number?

Thanks

**Comment by kul3r4** [comment]
Hi,
thanks for reporting the inconsistence between what the doc says (type="telephone") and what the code uses (type="tel"), I will update the page shortly.

Regarding the input, I just tried it and I got a numpad, it was also not possible to enter any text but just numbers. See the snapshot in the [link](https://www.dropbox.com/s/ga0l115xtbr69m2/Screenshot_20161117-163337.png?dl=0). 
Could you send a snapshot of the textpad that you are getting?

**Comment by winstonma** [comment]
Oh seems you are right. It will pop out the numpad.

I think last time I used a PC and enter the page. When I use a PC, I can type any english character and the submission is still successful.

**Comment by winstonma** [comment]
As this problem is not related to this example page, I will close this issue.

Just FYI I filed a issue on the [AMP HTML Page](https://github.com/ampproject/amphtml/issues/6345)

**Comment by winstonma** [comment]
@kul3r4 Seems the code is committed but not merged. Please take a look.
