### ISSUE TITLE
Add drawer menu to example pages

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#49]
We could implement a hamburger style drawer menu showing all examples and sections.

**Comment by kul3r4** [comment]
What would be left on the index page if we move all the example and sections on the menu? Should we add the menu only in the example pages?

**Comment by sebastianbenz** [comment]
The index page should stay the same. We can add the menu only to the examples pages

**Comment by juliantoledo** [comment]
fixed by #200
