### ISSUE TITLE
Is it possible to Load Facebook Comments in AMP sites 

### ISSUE THREAD

**Issue by ghostsurfer** [ampproject/amp-by-example#503]
I tried to load Facebook Comments in AMP sites. 

This is my Workflow: 
 
1. Write a Site with a simple Javascript to enter the right URL into the Facebook SDK:
```
<div id="si_fb_comments" class="fb-comments" data-href="" data-numposts="5"></div>
<script>

    (function () {
        var fb_hash = window.location.hash.substring(1)
        document.getElementById("si_fb_comments").dataset.href = fb_hash;
    })();

</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "https://connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.8&appId=341551949547724";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```

2. Load in PHP this file into a amp-iframe:
`<amp-iframe width="500"
	sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-top-navigation"
      height="281"
      layout="responsive"
      allowfullscreen
      frameborder="0"
	id="fb_comments"
      src="https://frame.example.de/fb_comments.html#https://example.de/post">
  </amp-iframe>`

but the problem in this solution is this error:

> Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.(…) VM47911 fTmIQU3LxvB.js?version=42:1 Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.(…)

**Comment by sebastianbenz** [comment]
It's currently not supported. Best thing is to chime in on this [issue](https://github.com/ampproject/amphtml/issues/5219) at ampproject/amphtml.
