### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by punit2502** [ampproject/amp-by-example#509]
Add a sandbox where user can try, validate & get a preview of  AMP code.

**Comment by sebastianbenz** [comment]
Yes! That would be really nice.

**Comment by dandv** [comment]
A step in that direction would be relaxing the CORS restriction so already established sandboxes (JSFiddle, JSBin etc.) can use ABE samples.

Here's an [amp-list sample](https://jsbin.com/maqunof/edit?html,console,output) that fails because of the CORS restriction.

**Comment by sebastianbenz** [comment]
Good point. That shouldn't be a problem.

**Comment by dandv** [comment]
Duplicate of #142?

**Comment by sebastianbenz** [comment]
@dandv you're right. Closing this issue.

Also: here is a first version https://amp-demo-1092.appspot.com/ [PR](https://github.com/ampproject/amphtml/pull/6613).
