### ISSUE TITLE
amp-sidebar not following link

### ISSUE THREAD

**Issue by Ridle** [ampproject/amp-by-example#521]
We have a AMP version of our website. And by example we have this page:
https://www.webton.be/wie-zijn-wij/?wpamp

When you show the menu you see several links, yet when you click these links nothing happens. Is this a bug or what are we doing wrong?

We did this completely like the example.
Please advice.

**Comment by sebastianbenz** [comment]
This looks like a bug in the amp runtime. I've filed an issue [here](https://github.com/ampproject/amphtml/issues/6585)

**Comment by cramforce** [comment]
AMP version was rolled back.

**Comment by Ridle** [comment]
Thank you for the fix, the links are working again
