### ISSUE TITLE
Use AMP for Amazon Ad's 

### ISSUE THREAD

**Issue by kazi-shahin** [ampproject/amp-by-example#532]
Could you please show an example, how can I use Amazon Ad's and compatible for AMP.

**Comment by sebastianbenz** [comment]
It would be nice to have a sample showing all supported ad networks. 

BTW there is an amazon sample in the official docs:

```
<amp-ad width=300 height=250
    type="a9"
    data-aax_size="300x250"
    data-aax_pubname="test123"
    data-aax_src="302">
</amp-ad>
```

https://www.ampproject.org/docs/reference/components/amp-ad

**Comment by kazi-shahin** [comment]
Thanks. But in 
"supported-ad-networks"
https://www.ampproject.org/docs/reference/components/amp-ad#supported-ad-networks 

"Amazon" is not listed. Any idea / suggestions?

**Comment by sebastianbenz** [comment]
A9 = Amazon

**Comment by kazi-shahin** [comment]
Wow. I was not aware of it. Thank you.

**Comment by kazi-shahin** [comment]
This is my generated ad script from Amazon. Could you please help me, how can I use this within AMP

=============================================
<script type="text/javascript">
    amzn_assoc_ad_type = "link_enhancement_widget";
    amzn_assoc_tracking_id = "XXXXXX";
    amzn_assoc_linkid = "XXXXXXXX";
    amzn_assoc_placement = "";
    amzn_assoc_marketplace = "amazon";
    amzn_assoc_region = "US";
</script>
<script src="//XXXXXXX"></script>

==============================================

**Comment by deepak0004** [comment]
Just wandering if you got the solution of how to convert the format of Amazon script you shared above to AMP?
