### ISSUE TITLE
CORS error on Form Submission with Page Update

### ISSUE THREAD

**Issue by uncompiled** [ampproject/amp-by-example#538]
I'm not sure if this example was intentionally designed this way to allow users to see both error and success states, but...

When trying the **Form Submission with Page Update** sample on https://www.ampbyexample.com/components/amp-form/, it results in:

`Error! Thanks for trying the amp-form demo with an error response.`

This message is caused by:

`Uncaught Error: Form submission failed:: Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: https://ampbyexample.com vs https://www.ampbyexample.com​​​`

The example works at https://ampbyexample.com/components/amp-form/, which makes sense since the origin matches.

**Comment by sebastianbenz** [comment]
Nope - not in intended. Thanks for reporting!
