### ISSUE TITLE
Enhance product sample by using amp-bind

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#557]
Enhance current product sample by using amp-bind:

- select the corresponding preview thumbnail while scrolling the carousel
- update the carousel image when choosing the color

Moreover, we could:

- make some fields dependent on selection, like showing the size only for some color

**Comment by kul3r4** [comment]
@sebastianbenz 
Regards: "update the carousel image when choosing the color", at the moment the color is implemented using amp-selector and the value for any option is a string describing the color, as 

`<amp-img option="green" selected="" src="/img/product1_60x40.jpg" width="60" height="40" ....`

If we want to select the corresponding color when we select an image from the carousel by using amp-bind, I would need to make the option a number, like:

`<amp-selector name="color_index" layout="container" [selected]="selectedSlide" on="select:AMP.setState(selectedSlide=event.targetOption)">
..
                <amp-img option="0" selected src="/img/product1_60x40.jpg" width="60" height="40"></amp-img>`

were `selectedSlide` is the variable that amp-bind sets and it's based on number.

Would it be ok if I change this and then I add in the backend the logic for mapping between numbers and a string describing the color?

**Comment by sebastianbenz** [comment]
A more realistic use case would be to have different image sets for different colors, e.g. two images for a red apple, which only shows if color red is selected etc. Is this possible?

**Comment by kul3r4** [comment]
I think so, I am trying this implementation currently.

**Comment by choumx** [comment]
Will this example cover @cramforce's e-commerce request in https://github.com/ampproject/amphtml/pull/7127#issuecomment-274645079?

If not, I'll create a new tracking issue that either @kul3r4 or I could implement.

**Comment by kul3r4** [comment]
Hi, I am following most of the suggestions.

From the list:
- an image gallery: Yes
- a color selector: Yes
- a size selector: Yes
- support for availability (some items are sold out): @cramforce Can you expand a bit more on this?
- support for varying prices and sales specific to colors: I was planning to have different sizes specific to colors. For example, for color red only size S would be available. For the price, I will add that as well.

**Comment by cramforce** [comment]
@kul3r4 Basically when you select a color, the size selector should disable the sizes that are not available in that color.

**Comment by kul3r4** [comment]
ok, got it. Yes, will include those in the sample.

**Comment by ericlindley-g** [comment]
I mentioned this in a separate meeting w/ @kul3r4 , but wanted to note for the group that we're calling out the e-commerce sample as an example for how to use the goToSlide method, so it will be worth keeping that up at least in the short term. Would it be possible to separate the e-commerce example that uses bind, so we can use that in parallel when reaching out to folks for Bind?

**Comment by kul3r4** [comment]
I was planning to keep the Product sample with Bind integration in a branch and deploy it somewhere, while keeping in master the version of Product which only uses goToSlide. Would that work?

**Comment by ericlindley-g** [comment]
Sounds great—thanks!
