### ISSUE TITLE
tabs sample using amp-selector and css

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#559]
We should be able to create a `tabs` sample using `amp-selector` and CSS (using adjacent selectors)

@camelburrito @chenshay

**Comment by sebastianbenz** [comment]
That'd be fantastic to have!

**Comment by sebastianbenz** [comment]
@aghassemi do you plan to work on this?

**Comment by camelburrito** [comment]
Sebastian

I can put a jsbin for it , will you be Able to take over from there? (Does
that work?)

**Comment by sebastianbenz** [comment]
@camelburrito why not create a PR instead? Shouldn't be more effort that creating a jsbin.

**Comment by sebastianbenz** [comment]
@camelburrito otherwise a JSBIN would work as well

**Comment by aghassemi** [comment]
Continuing the discussion from https://github.com/ampproject/amphtml/issues/7512#issuecomment-279561427 here.

@MadisonMiner Thanks for the snippet! The approach is right. We just need some `aria` rules and need to move the `content` outside of the `ul`.

Something along this lines:
https://jsbin.com/xelayuyoci/1/edit?html,output

**Comment by aghassemi** [comment]
@senthilp please take a look at https://jsbin.com/xelayuyoci/1/edit?html,output , you should be able to use the same approach (e.g. using `amp-selector` and adjacent sibling CSS selectors) to achieve the tab UI you had in mind for eBay.

**Comment by senthilp** [comment]
The jsbin implementation looks close to what we need. We will try it out. Cc @tcorley @rajkumarsrk

**Comment by aghassemi** [comment]
@MadisonMiner @sebaperez @kul3r4 Anyone interested in turning this JS bin to a PR for ABE? (If not, I will take it on next week). 

Thanks!

**Comment by tcorley** [comment]
@aghassemi I can start working on this during the weekend 👍

**Comment by aghassemi** [comment]
Thanks @tcorley! I like eBay's UI design for tabs, having the ABE sample look like yours would be great!

**Comment by devignerforhire** [comment]
The only catch with using adjacent selectors is that it makes vertical tabs somewhat trickier. I'm guessing I could just use amp-bind with a normal list to toggle the active state on the relevant content pane, though it makes it a lot less dynamic. If anyone has any ideas on how to achieve vertical tabs with amp i'd love to hear them.

**Comment by sebastianbenz** [comment]
Why would using amp-bind make it a lot less dynamic?

**Comment by devignerforhire** [comment]
@sebastianbenz well, because I'd need to add an amp-bind expression on each tab menu item and panel, where as with the tabs example on amp start the expression is set once on the amp-selector. Unless I'm missing something obvious that is :P

**Comment by devignerforhire** [comment]
Thanks for the example, that helps a lot :) 

+1 for adding it to the existing tabs example. The more examples, the better. While the docs are great, I definitely learn more seeing real examples. On a side-note, it could be a nice competition to run - submit your most creative uses of amp/components (via codepen or similar).

**Comment by sebastianbenz** [comment]
Found an even better way by combining two amp-selectors:

```
<amp-selector id="myTabs" class="tabs" on="select:myTabPanels.toggle(index=event.targetOption, value=true)">
    <div tabindex="0" role="tab" option=0 selected>Tab 1</div>
    <div tabindex="0" role="tab" option=1>Tab 2</div>
    <div tabindex="0" role="tab" option=2>Tab 3</div>
  </amp-selector>

  <amp-selector id="myTabPanels" class="tabPanels">
    <section role="tabpanel" option selected>
      Tab Content 1
    </section>
    <section role="tabpanel" option>
      Tab Content 2
    </section>
    <section role="tabpanel" option>
      Tab Content 3
    </section>
  </amp-selector>
```

https://jsbin.com/tosudebasi/1/edit?html,output

**Comment by devignerforhire** [comment]
Hi Sebastian,
I've only just got around to implementing this and was wondering whether it would be possible to match up the relevant tag based on a slug/attribute match, rather than the order of the tab content? The current approach of matching the tab nav item to the tab content position means I need to update the option each time new items are added. It's not the end of the world, but it would be cool if we could find an approach that doesn't require updating the option each time.
