### ISSUE TITLE
Runaway code panel indentation

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#560]
In the code panel of samples with a lot of code, I see the indentation level increasing until it wraps around:

[amp-form](https://ampbyexample.com/components/amp-form/) and 

![2017-01-27 15 55 48 683](https://cloud.githubusercontent.com/assets/33569/22391917/21c965b6-e4a9-11e6-9015-d32ea0b06277.gif)

**Comment by sebastianbenz** [comment]
That's bad.  All samples are run through an auto-formatter before publishing. That looks like a problem in the sample source which throws the formatter off (maybe some unclosed tags).

**Comment by sebastianbenz** [comment]
It seems like it is already fixed here: https://amp-by-example-staging.appspot.com/components/amp-form/

I remember fixing an unclosed div in #551 which might've caused this. 

BTW the playground is great for finding these errors as coderror highlights invalid tags.
