### ISSUE TITLE
AMP Playground doesn't carry over the ABE default styles

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#561]
While the playground does render AMP custom styling, the default styles from ABE are lost. While technically samples are rendered correctly, albeit starkly (e.g. [amp-form](https://amp-by-example-staging.appspot.com/playground/#url=https%3A%2F%2Famp-by-example-staging.appspot.com%2Fcomponents%2Famp-form%2Fsource%2F)), this causes some samples to look odd, e.g. in [amp-selector](https://amp-by-example-staging.appspot.com/playground/#url=https%3A%2F%2Famp-by-example-staging.appspot.com%2Fcomponents%2Famp-selector%2Fsource%2F), where `<li>`s inherit a line height of 0 from `amp-selector`, which isn't overridden later.

![image](https://cloud.githubusercontent.com/assets/33569/22392199/ab3844a0-e4ab-11e6-90e6-7f7bdcd4c5bd.png)

**Comment by sebastianbenz** [comment]
This is intentional - otherwise the sample source would be bloated by the additional css rules. Also, we'd need to find a way to remove unused rules from the default style. 

I prefer ensuring that samples look decent in the playground (one way to do this is to write samples standalone).

**Comment by sebastianbenz** [comment]
Closing as WAI
