### ISSUE TITLE
"a.checkValidity is not a function" in amp-selector sample

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#563]
If you select more than one option in the very last example (Option A, B, C and N/A) and click Submit, the following error will occur:

![image](https://cloud.githubusercontent.com/assets/33569/22393748/875443ec-e4c2-11e6-92fe-61ecd6de6dfe.png)

(The page will reload, so check "Preserve log")

**Comment by kul3r4** [comment]
This is related to [amphtml 6927 issue](https://github.com/ampproject/amphtml/issues/6927)

**Comment by sebastianbenz** [comment]
Closing as it is a runtime issue
