### ISSUE TITLE
Update "A4A" terminology

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amp-by-example#573]
The "AMP for Ads" (A4A) section of the site is about writing ad creatives in AMP, but the current terminology has led some users to think it's about Fast Fetch. The mention of "AMP Ads for AMP Pages" also contributes to this confusion. This should be updated to use the most current terminology and make clear that it's specifically about AMP creatives.

**Comment by sebastianbenz** [comment]
Thanks for reporting this. Could you please point us to the correct terminology?

**Comment by sebastianbenz** [comment]
@carlosfuertes can you take a look at this?

**Comment by taymonbeal** [comment]
Ad creatives written in AMP are now just "AMP ads". As far as I can tell, nothing on this site deals with the case of AMP ads on AMP pages (i.e., where Fast Fetch comes into play); the guidance for writing ad creatives in AMP works equally well no matter what kinds of pages those ads will ultimately appear on.

@jasti can say more.

**Comment by jasti** [comment]
@sebastianbenz -> Any place where we reference A4A in ABE could be changed to "AMP ads".
Examples:
https://ampbyexample.com/#amp_for_ads_a4a
https://ampbyexample.com/amp_for_ads_a4a/a4a_banner_ad/
https://ampbyexample.com/amp_for_ads_a4a/a4a_carousel/

Once we add a fast fetch example that @carlosfuertes is working on, we could appropriately name it.

**Comment by sebastianbenz** [comment]
@jasti is 'AMP Ads for AMP' still OK or should this be renamed to simply 'AMP Ads'?

**Comment by taymonbeal** [comment]
@sebastianbenz: Are you planning on writing specifically about the AMP-ads-on-AMP-pages case? The technology that provides benefit there is called Fast Fetch, but the details of how it works aren't especially relevant to an advertiser who just wants to write ad creatives in AMP HTML.

**Comment by jasti** [comment]
I think all of @sebastianbenz's example just have 'AMP ad' examples. (so yes, Sebastian). I think @carlosfuertes is going to provide a 'Fast Fetch' example.
