### ISSUE TITLE
Request: additional examples for amp-bind (amp-video[src] + XHR)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#574]
The initial example for amp-bind is great!

I have a request for two additional examples to include:

1. change amp-video[src] on tap (this would be like the example of changing amp-img[src] on tap, but would use amp-video instead)

2. Change content based on XHR triggered by tap
The example could be as simple as tapping a button to update text from "cat" to "rabbit" (or some other animal — whatever text is returned via XHR), but could alternately simulate tapping a "like" button (following up in a separate request for this specific example).

WDYT?

/to @kul3r4 
/cc @choumx

**Comment by choumx** [comment]
For reference, there are existing examples for these in the amphtml repository:
1. https://github.com/ampproject/amphtml/blob/master/examples/bind/basic.amp.html#L34
2. https://github.com/ampproject/amphtml/blob/master/examples/bind/xhr.amp.html#L27

**Comment by sebastianbenz** [comment]
Sgtm. Both are good candidates for the amp-bind sample.

**Comment by ericlindley-g** [comment]
Awesome—thanks! Do you have a sense for how soon these two examples in particular could go up?

**Comment by kul3r4** [comment]
Integration between `amp-bind` and `amp-video` is [here](https://ampbyexample.com/components/amp-bind/).

Capturing conversation with @sebastianbenz: when working on the form sample with bind, we could also verify if it's possible to add content to state via the submit button. Could you come up with a scenario?

**Comment by ericlindley-g** [comment]
@kul3r4 , are you looking for a scenario where the state is changed on form submission and response? One could be optimistically incrementing the count of "likes" after tapping on a <3 button, and then updating with the current value after the response comes in. (captured in [this issue](https://github.com/ampproject/amp-by-example/issues/575))

**Comment by kul3r4** [comment]
@choumx i gave this a try [here](https://github.com/kul3r4/amp-by-example/blob/amp-bind-form/src/20_Components/amp-bind.html#L131).
I wanted to optistimatically update the count in 
`<p> Number of likes: <span [text]="(likesNumber+1)">1</span></p>` 

and then, in case of error, decrementing it by 
`<form method="POST" action-xhr="<%host%>/components/amp-form/submit-form-xhr"  target="_top"
      on="submit-error:AMP.setState(likesNumber = likesNumber - 1)">`
but I get errors like:

> submit-error:AMP.setState(likesNumber = likesNumber - 1) ] Expected either [,] or [)]

I guess I can't decrement or increment yet inside AMP.setState,  right?

**Comment by choumx** [comment]
Yea, current `AMP.setState` only supports setting literal values with no operations. The PR you referenced adds this, so you can do:

```
AMP.setState({likesNumber: likesNumber + 1})
```

**Comment by kul3r4** [comment]
Thanks! I will put this work on pause until the new code goes into canary. @ericlindley-g FYI.

**Comment by kul3r4** [comment]
The like button has been implemented as part of #575
