### ISSUE TITLE
Request: "like" button example w/ amp-bind

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#575]
related to #574 

This example would use amp-bind to simulate a "like" button or similar. Here's the general use-case:

0. User sees content with associated heart icon (either solid non-red color or outline), along with count of total current "like"s
1. User taps heart icon, triggering XHR (UI is optimistically updated to success state: heart is filled with solid red color, "like" count is incremented—though I'm not sure if incrementing is possible before the XHR(?))
1.1 (success) When XHR returns response, UI stays the same with success
1.2 (failure) When XHR returns response, UI is updated to reflect failure: heart returns to initial state of non-red color or outline. Message appears indicating failure.

WDYT?

/cc @kul3r4  @choumx

**Comment by sebastianbenz** [comment]
Isn't amp-bind a bit over-engineered in this case? A simple checkbox with
auto-submit sounds link an easier approach. See also
https://github.com/ampproject/amp-by-example/issues/454

**Comment by ericlindley-g** [comment]
Good point — @sebastianbenz, (or @mkhatib) is it possible using just amp-form (not using amp-bind) to display an optimistic UI update, followed by an accurate update to the UI on XHR response (along with notification in the case of failure?)

**Comment by ericlindley-g** [comment]
Also forgot a key point of using amp-bind for this, which is to update a "like" count on the page as well (if possible). Edited above to reflect

**Comment by kul3r4** [comment]
This has been implemented in [https://ampbyexample.com/advanced/favorite_button/](https://ampbyexample.com/advanced/favorite_button/)
