### ISSUE TITLE
Change absolute links to relative in amp-form example

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-by-example#576]
It seems that the cache can handle relative links in `<amp-form>` just fine. (The `action` and `action-xhr` attributes do not need to be absolute.) Since relative URLs are easier for authors to generate and manipulate, I think it would be helpful if the links in the example were changed from absolute to relative.

Example:

* https://puddle-bee.gomix.me/
* https://cdn.ampproject.org/c/s/puddle-bee.gomix.me/

([source](https://gomix.com/#!/project/puddle-bee))

**Comment by kul3r4** [comment]
That would be fine for me.

**Comment by sebastianbenz** [comment]
+1 - any takers?
