### ISSUE TITLE
Request: example for index/total slide display for carousel using amp-bind

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#579]
This example would demonstrate the capability of amp-bind to display the current slide index (i.e. "3 of 5" or "3/5" of an image carousel. A good place for this example might be the advanced image gallery page. (Could also be in the e-commerce sample, but I don't want to overcomplicate that page)

Reference example is this [jsfiddle](http://jsfiddle.net/QTjET/11/) (but we'd want to style it nicely :)

Additionally it would be nice to have an example that uses [this paradigm](http://kenwheeler.github.io/slick/) of large/small or hollow/filled dots to represent the slide index

/cc @choumx @kul3r4 @sebastianbenz

**Comment by sebastianbenz** [comment]
These would be great and I agree, the adcanced image gallery is best place for this.

**Comment by choumx** [comment]
Kevin, our new eng res, could work on this. Rough example here: https://github.com/ampproject/amphtml/blob/master/examples/bind/carousels.amp.html

/cc @kmh287
