### ISSUE TITLE
Validation fails with timeout

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#58]
```
[15:24:52] Validating example components/amp-ad/index.html: PASS
undefined:1
Fatal Error: Timeout: did not get to load all resources on this page
^

SyntaxError: Unexpected token F
    at Object.parse (native)
    at ChildProcess.<anonymous> (/Users/sbenz/Documents/projects/amp-by-example-dev/tasks/validate-example.js:63:37)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

@jkingyens have you seen this before?

**Comment by jkingyens** [comment]
I haven't seen it but its due to slow page loading during validation. When the timeout error triggers there is no check for that and the callback assumes valid JSON from the AMP validator. I just have to add better error handling here. Will do tomorrow.

**Comment by jkingyens** [comment]
This looks like something that needs to be fixed in [amp validator](https://github.com/dorightdigital/amp-validator). We might want to investigate extracting the validator from ampproject/amphtml and running the validator as a standalone function.

**Comment by sebastianbenz** [comment]
Does the node amp-validator support setting a timeout?

**Comment by jkingyens** [comment]
No Amp Validator is just a command line interface with the only option to change formatting (JSON vs text). I made a fix in [PR78](https://github.com/ampproject/amp-by-example/pull/78) to at least detect this timeout from the CLI and emit a gulp task failure when this happens.

**Comment by jkingyens** [comment]
@sebastianbenz can I mark this as fixed for now since the error is handled more gracefully?
