### ISSUE TITLE
Add a "Edit on Github" Button below each sample heading

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#581]
Inspired by the polymer docs: https://www.polymer-project.org/1.0/docs/devguide/local-dom

@kul3r4 wdyt?

**Comment by kul3r4** [comment]
would this remove "view source" on the top right of each sample?

**Comment by sebastianbenz** [comment]
View source got replaced by the playground. Also: edit sends a different message: (hopefully) makes it more obvious that everyone can submit samples.

**Comment by kul3r4** [comment]
ok, the position sounds good. An alternative to "edit on github" would be "source code".
What about also adding [fork me on github ribbon](https://github.com/blog/273-github-ribbons) on the main page?Maybe is it possible to add it just using pure css.
