### ISSUE TITLE
Dog doesn't change into cat

### ISSUE THREAD

**Issue by cramforce** [ampproject/amp-by-example#586]
The image here doesn't switch for me https://ampbyexample.com/components/amp-bind/

**Comment by cramforce** [comment]
I suppose this is a (known?) AMP bug. The `<amp-img>` src changes, but not the underlying `img` tag.

**Comment by kul3r4** [comment]
Agree, by exploring the element, after clicking the on the button, the amp-img tag is:
`<amp-img src="/img/cat-looking-up-300x200.jpg" width="300" height="200" [src]="allAnimals[currentAnimal].url" class="-amp-element -amp-layout-fixed -amp-layout-size-defined -amp-layout" style="width: 300px; height: 200px;">
    <img class="-amp-fill-content -amp-replaced-content" src="/img/Border_Collie.jpg"></amp-img>`

**Comment by cramforce** [comment]
Filed https://github.com/ampproject/amphtml/issues/7296 to look into this.
