### ISSUE TITLE
amp-selector examples not working

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#589]
The thumbnails aren't being displayed — I observed this issue while it was in experimental, though it stopped being a problem. Now surfacing again. 

@sebastianbenz @camelburrito 

<img width="829" alt="screen shot 2017-02-02 at 9 46 06 am" src="https://cloud.githubusercontent.com/assets/16807766/22561295/73dd77e8-e92c-11e6-911a-530fb5e1f59a.png">

**Comment by sebastianbenz** [comment]
There is not much we can do...hopefully it's finally going to be released next Thursday.
