### ISSUE TITLE
validation warnings for news article template

### ISSUE THREAD

**Issue by tomo-t** [ampproject/amp-by-example#592]
https://ampbyexample.com/samples_templates/news_article/ is showing a warning for the amp ad component - can this be fixed?

**Comment by emestud** [comment]
The ads is not always loading for me in this page.
The amp-ad extension is not explicitly included in the page and not loading the proper amp-ad JS.

I have the AMP Dev Channel experiment enabled.

When the Initiator is "xhr-impl.js:298", my browser is trying to load https://cdn.ampproject.org/rtv/001482359659944/v0/amp-ad-0.1.js (error 404).

When I refresh, sometime the extension load is initiated by "extensions-impl.js:506" and loading successfully https://cdn.ampproject.org/rtv/001486066183733/v0/amp-ad-0.1.js (Pre-release)

My question is why "extensions-impl" and "xhr-impl" are not loading https://cdn.ampproject.org/v0/amp-ad-0.1.js

**Comment by kul3r4** [comment]
Related to #591

**Comment by kul3r4** [comment]
Solved by #591.
@tomo-t I can't see the warning anymore and I get "AMP validation successful." when using https://ampbyexample.com/samples_templates/news_article#development=1.
