### ISSUE TITLE
build out amp-form with more input examples

### ISSUE THREAD

**Issue by tomo-t** [ampproject/amp-by-example#609]
Hi there!

A question from Google Webmaster Forum to see if would be possible to build out the amp-form example to include different kinds of inputs (eg dropdowns, radio buttons etc).

https://productforums.google.com/d/msg/webmasters/GpWhrLkeGUY/gcUWqG-UBwAJ

**Comment by sebastianbenz** [comment]
https://ampbyexample.com/components/amp-form/ lists all available inputs (afaik). Please report any specific ones that are missing.

**Comment by tomo-t** [comment]
Thanks Sebastian - would it be possible to include some drop down boxes in the example template too?

**Comment by sebastianbenz** [comment]
@kul3r4 could can you take a look?

**Comment by kul3r4** [comment]
Will do.
