### ISSUE TITLE
Request: Include transition in CSS bind example

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#610]
Currently I believe that the amp-bind example demo's how the binding protocol can change the CSS class on interaction. This is great, but I think it would be good to show that CSS transitions are possible between states (if that is the case :)

I'm not sure what the best way to show this is, but it could be as simple as a block that changes color and moves from one side of the page to the other, over a duration of ≥ 1 second

WDYT?

/cc @kul3r4 @choumx @sebastianbenz

**Comment by sebastianbenz** [comment]
We're already doing this in the product sample. The selector button state changes are animated.

**Comment by ericlindley-g** [comment]
I see now: looks like just the box-shadow is animated? It's great that it's demo'ing that transitions are possible, but it's pretty subtle right now.

This isn't high-priority, but:
If we just look at the product page, I think a transition might help smooth out transitions where the entire carousel + thumbnails is swapped out when selecting different color options. A fade in/out between .1s and .3s might be nice for the entire carousel+thumbnails, to drive home the point that the transitions can be smooth.

Eventually, if we find a good use-case, it might be cool to have an interaction that is entirely based on amp-bind + CSS class changes.

**Comment by sebastianbenz** [comment]
Sounds good.

@kul3r4 can you take a look once you're done with the product sample?
