### ISSUE TITLE
Indentation for image gallery sample keeps growing even though elems are at same level

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-by-example#614]
On this page, there are multiple `amp-img` elements that are at the same level within an `amp-carousel`, but their indentation keeps growing:

https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/#image-galleries-with-previews

This makes it very hard to read the code sample since it introduces a ton of line wrapping.

cc @ericlindley-g

**Comment by sebastianbenz** [comment]
Thanks for reporting! This should be fixed as part of #612.
