### ISSUE TITLE
image-lightbox: set `alt` AND `title` on the images

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#618]
https://ampbyexample.com/components/amp-image-lightbox/ needs to add:

```
      alt="Picture of a dog"
      title="Picture of a dog, view in lightbox"
```

 to the image.

The `alt` is for the image and the `title` is for the fact that this a button that opens the image in the lightbox. Both are needed since when in the lightbox, `title` does not apply anymore.

**Comment by sebastianbenz** [comment]
What's the correct way to handle the sample with a separate image description: 

```
  <amp-img on="tap:lightbox1"
    role="button"
    tabindex="0"
    aria-describedby="imageDescription"
    src="/img/Border_Collie.jpg" width="300" height="246"></amp-img>
  <div id="imageDescription">
    This is a border collie.
  </div>
```

Are these needed there as well?
