### ISSUE TITLE
Pinterest widget example wrong height

### ISSUE THREAD

**Issue by goldquest** [ampproject/amp-by-example#626]
The example for the embed widget (https://ampbyexample.com/components/amp-pinterest/) has wrong dimensions set and thus only shows the top half of the widget.

In the embed preview of the pin, you can see the correct dimensions: https://developers.pinterest.com/tools/widget-builder/?type=pin&url=https%3A%2F%2Fde.pinterest.com%2Fpin%2F228065168607834583%2F

**Comment by sebastianbenz** [comment]
Thanks for reporting this. Seems like only the small size is supported - also the size isn't 100% correct.

 //cc @paul-matthews
