### ISSUE TITLE
Advanced carousels bind example: linked thumbnails updates w/ wrong number

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#631]
Was excited to see the slide index UI for the advanced carousels use-case!

Just noticed a bug, though: Tapping on the thumbnails immediately below the carousel works well, but when tapping on the second row of thumbnails, the number updates strangely (seems to concatenate the two numbers):

<img width="434" alt="screen shot 2017-02-17 at 8 36 58 am" src="https://cloud.githubusercontent.com/assets/16807766/23074132/bfe1cb1e-f4ec-11e6-93e4-f500c795c24e.png">

/to @kul3r4

**Comment by kul3r4** [comment]
Being able to debug the the variable easily would help here, will investigate.
@kmh287 FYI
