### ISSUE TITLE
amp-bind example non functional

### ISSUE THREAD

**Issue by MammouthQc** [ampproject/amp-by-example#634]
The [amp-bind component](https://ampbyexample.com/components/amp-bind/) doesn't work. There's and error in the console in "chunk.js:351" 
`Uncaught (in promise) TypeError: Cannot read property 'enqueue' of undefined`

**Comment by kul3r4** [comment]
Hi,
enable the dev-channel by clicking on the button on "Enable dev channel".

**Comment by kul3r4** [comment]
@MammouthQc were you able to run the sample?

**Comment by MammouthQc** [comment]
@kul3r4 Thanks it worked ! I still do have an error in the console, but the sample does run now.
