### ISSUE TITLE
Create an AMP page served from cache showing the difference between AMP and non-AMP ads

### ISSUE THREAD

**Issue by jasti** [ampproject/amp-by-example#635]
Create a discoverable card on the home page and link to a page similar to 
https://cdn.ampproject.org/c/s/storage.googleapis.com/cfuertes/A4AExample/amp_example.html?exp=a4a:-1

One important enhancement might be to somehow throttle the page speed to show the difference. When you refresh the sample page using 3g, you'll notice how much better the AMP ad is versus the regular one. I'm not sure how to properly demonstrate it on every page view. 
Maybe @cramforce @lannka have ideas.

**Comment by jasti** [comment]
CC @carlosfuertes

**Comment by dknecht** [comment]
We can take a shot at demo page.  It would be nice if we could expose something like the jank meter to show the time also.

**Comment by dknecht** [comment]
We can take a shot at demo page.  It would be nice if we could expose something like the jank meter to show the time also.   One idea is to post analytics of load to some where that live list could render

**Comment by dknecht** [comment]
@jasti  the example above doesn't seem to work on desktop browsers.
