### ISSUE TITLE
Failed to load resource: net::ERR_INVALID_RESPONSE on sw-toolbox

### ISSUE THREAD

**Issue by dandv** [ampproject/amp-by-example#636]
Loading https://ampbyexample.com/ displays this error in the Chrome console:

> A bad HTTP response code (404) was received when fetching the script.
/bower_components/sw-toolbox/sw-toolbox.js Failed to load resource: net::ERR_INVALID_RESPONSE
sw.js:17 Uncaught [object DOMException]
(anonymous) @ sw.js:17
log.js:140 1628 "[amp-install-serviceworker]" "ServiceWorker registration failed:" TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed

![image](https://cloud.githubusercontent.com/assets/33569/23097425/40ad3854-f5e8-11e6-9347-8d2b91a89a91.png)

**Comment by sebastianbenz** [comment]
This looks like `gulp bower` didn't run. Anyway, I removed bower (it's silly to use both bower and npm in the same project anyway).
