### ISSUE TITLE
Migrate to ampstart

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#646]
- [x] replace mdl with ampstart
- [x] migrate to new color scheme
- [x] integrate new logo
- [x] migrate to navbar
- [x] migrate to new footer
- [x] migrate to new hero design
- [x] migrate buttons
- [x] migrate forms & inputs
- [x] migrate playground
- [x] remove legacy styles from all samples
- [x] update screenshot in /img/abe_preview.png
- [x] migrate sample layout
- [x] migrate preview (adapt 'View annotated source' button)

//cc @kul3r4 @abeck000 @camelburrito

**Comment by kul3r4** [comment]
@sebastianbenz Which tasks will remove style from `h1,h2,h3...`?

**Comment by kul3r4** [comment]
the action 

> update screenshot in /img/abe_preview.png

was not performed, should we remove this snapshot?
