### ISSUE TITLE
amp-accordion example does'nt work!

### ISSUE THREAD

**Issue by dimanjy** [ampproject/amp-by-example#66]
Powered by AMP ⚡ HTML – Version 1456954860788
AMP validation had errors:
https://ampbyexample.com/components/amp-accordion/:5:2 The attribute 'custom-element' in tag 'amp-access extension .js script' is set to the invalid value 'amp-accordion'. (see https://www.ampproject.org/docs/reference/extended/amp-access.html)
https://ampbyexample.com/components/amp-accordion/:1570:12 The tag 'amp-accordion' is disallowed.
https://ampbyexample.com/components/amp-accordion/:1571:4 The attribute 'expanded' may not appear in tag 'section'.
https://ampbyexample.com/components/amp-accordion/:1653:2 The tag 'amp-accordion' is disallowed.

**Comment by kul3r4** [comment]
Hi, have you tried to:

- check the box under CDN experiments.

- enter the following line in the Javascript console:
AMP.toggleExperiment('amp-accordion')

as suggested in the left top corner of the page?

For the validation errors, as suggested here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md this tag is in experimentation so " no validation yet".

**Comment by dimanjy** [comment]
Thanks for the answer!
Yes, finally it works for me this way, but does it mean that I can't use it in production for my AMP site?
I came here from https://www.ampproject.org/docs/reference/extended/amp-accordion.html and it is marked as "Stable" there :\

**Comment by sebastianbenz** [comment]
You can't use it in production yet. Seems like the docs are out-of-sync. [This one](https://github.com/ampproject/amphtml/blob/56d25ef12aa30b1409f9103c9a54b13ca7e3cfec/extensions/amp-accordion/amp-accordion.md) still says it's experimental. You can check [here](https://github.com/ampproject/amphtml/releases) to see when it's in prod.
