### ISSUE TITLE
Why doesn't Google AMP Analytics adhere to tracking filters?

### ISSUE THREAD

**Issue by tborges** [ampproject/amp-by-example#665]
In Google Analytics I have filters setup to block my office IP from affecting the analytics traffic. However, when I use the below analytics code, my page views still get tracked.

`</amp-analytics>
<amp-analytics type="googleanalytics">
    <script type="application/json">
        {
        "vars": {
        "account": "UA-XXXXXXXX-X"
        },
        "triggers": {
        "trackPageview": {
        "on": "visible",
        "request": "pageview"
        }
        }
        }
    </script>
</amp-analytics>`

Please help
Thank you

**Comment by 1987yama3** [comment]
It seems that the IP address is anonymous because the "aip" parameter is measured as true. I saw the AMP code, but it seems that users can not deal with it now.

I create Issue to Github of amphtml. Let's wait for it to be handled.

Thank you.

**Comment by tborges** [comment]
Very nice! Thank you

**Comment by 1987yama3** [comment]
By excluding the tail of the excluded IP address specified by the filter to 0, it will be excluded.
for exampe: if your IP address is "100.101.102.103", then exclude IP address is "100.101.102.0".


However, IP addresses that should not be excluded are also excluded.
(In the above example, 100.101.102.0 to 100.101.102.255 are all excluded.)

If you have a lot of internal traffic and need to exclude, please try it.

**Comment by tborges** [comment]
All right it worked for me.  
Now when I visit the AMP pages my Google Analytics won't show it, fantastic.
