### ISSUE TITLE
Error in the document website

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amp-by-example#682]
Error on this webpage: https://ampbyexample.com/components/amp-social-share/

![zzzzzzzzz](https://cloud.githubusercontent.com/assets/17784082/23589895/08b36c56-01ce-11e7-9173-ad1c47e8f38b.png)

Correct code syntax should be this:

`<amp-social-share type="system" data-mode="replace"></amp-social-share>`

Also could someone expand on this section and say it only displays on Chrome or Android and not on other browsers etc.

**Comment by sebastianbenz** [comment]
Thanks for reporting this!

@ithinkihaveacat can you take a look?

**Comment by sebastianbenz** [comment]
This is already fixed.
