### ISSUE TITLE
Invalid example

### ISSUE THREAD

**Issue by derrickstaten** [ampproject/amp-by-example#689]
Invalid amp-bind example

paste [this line of code](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-bind.html#L104) into the [playground](https://ampbyexample.com/playground/).

![screen shot 2017-03-10 at 2 44 30 pm](https://cloud.githubusercontent.com/assets/5950251/23816148/18470b66-05a0-11e7-93a4-5da3a7309cd7.png)

it seems `amp-bind` is considerably more limited in functionality than the documentation indicates.

**Comment by derrickstaten** [comment]
seems like playground cannot work with experiments, even if I add:

`<meta name="amp-experiments-opt-in" content="AMP-BIND">`

I get the same error

**Comment by derrickstaten** [comment]
It seems experiments are not compatible with the iframe. I can get `AMP.toggleExperiment('amp-bind');` to work in my own pages. 

However, I cannot get the following to work, which is required to have normal users experience amp-bind functionality:
`<meta name="amp-experiments-opt-in" content="AMP-BIND">`
or
`<meta name="amp-experiments-opt-in" content="amp-bind">`

**Comment by derrickstaten** [comment]
https://github.com/ampproject/amphtml/tree/master/tools/experiments#enable-an-experiment-for-a-particular-document should be removed if it's not functional.

**Comment by derrickstaten** [comment]
actually, who cares, it's an experimental feature I can't use in production.

**Comment by sebastianbenz** [comment]
I created an issue for the playground (it should work btw for Chrome if you've enabled the experiment in the sample).

Apart from that: it's quite common for experimental features to not yet validate as the API is usually still experimental (experiments != beta).
