### ISSUE TITLE
Live blog example is missing amp-live-list markup

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#700]
https://ampbyexample.com/samples_templates/live_blog/preview/

<img width="896" alt="screen shot 2017-03-15 at 6 32 28 pm" src="https://cloud.githubusercontent.com/assets/16807766/23977825/c6493d22-09ad-11e7-9e4b-82248ccdec99.png">

/cc @kul3r4 @sebastianbenz

**Comment by kul3r4** [comment]
Thanks for reporting!
Actually the page is not showing the amp-live-list at all. The markup and content list are not created by the server template anymore, I am investigating.
