### ISSUE TITLE
amp-accordion keyboard accessibility

### ISSUE THREAD

**Issue by Malvoz** [ampproject/amp-by-example#709]
The amp-accordion component (as mentioned in: [https://github.com/ampproject/amp-by-example/pull/697#issuecomment-287491243](https://github.com/ampproject/amp-by-example/pull/697#issuecomment-287491243)) is not fully accessible in the way that you can not navigate the content of an amp-accordion using only your keyboard.

**Comment by sebastianbenz** [comment]
Sorry for making this not more explicit. Can you please file an issue directly for the AMP Runtime [here](https://github.com/ampproject/amphtml/issues/new). Thanks!
