### ISSUE TITLE
AMP Carousel

### ISSUE THREAD

**Issue by Nafeh** [ampproject/amp-by-example#710]
Am having issue with AMP carousel arrows, it disappear after load on mobile browser while it works fine on PC!
Any chance that i can make the arrows keep displaying on mobile?

Thanks in advance
Nafeh

**Comment by sebastianbenz** [comment]
This is the wrong place for asking generic AMP questions. Please ask these questions on [Stackoverflow](http://stackoverflow.com/questions/ask?tags=amp-html) using the `amp-html` tag. Thanks!

Feel free to link to your question from this thread.
