### ISSUE TITLE
Example for PaymentRequestAPI using iframe

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-by-example#713]
Something that illustrates what's enabled by https://github.com/ampproject/amphtml/issues/7623. Should also work through the Google Search viewer.

**Comment by sebastianbenz** [comment]
We should be able to reuse one of the existing samples: https://googlechrome.github.io/samples/paymentrequest/index.html

**Comment by sebastianbenz** [comment]
@afitz0 will look into this.

**Comment by rudygalfi** [comment]
Any updates on this one?

**Comment by sebastianbenz** [comment]
Afaik @afitz0 is already working on it.
