### ISSUE TITLE
Use IE11-compatible font in amp-font example

### ISSUE THREAD

**Issue by cvializ** [ampproject/amp-by-example#718]
IE11 fails to load the [`Tangerine_Regular.ttf`](https://github.com/ampproject/amp-by-example/blob/master/src/fonts/Tangerine_Regular.ttf) font used in the [amp-font page](https://ampbyexample.com/components/amp-font/) with this error: `CSS3114: @font-face failed OpenType embedding permission Check. Permission must be Installable.`

![Screenshot of Tangerine_Regular.tff failing to render in IE11](https://cloud.githubusercontent.com/assets/2363700/24307830/f1addef6-1082-11e7-83c9-576f85a3ab87.png)

I recommend we replace Tangerine_Regular with another font that loads in IE11 so that users see amp-font works correctly in that browser. I know [`ComicAMP.ttf`](https://github.com/ampproject/amphtml/blob/master/examples/fonts/ComicAMP.ttf) works.

**Comment by kul3r4** [comment]
Thanks for the suggestion, feel free to issue a pull request and will get it merged.
