### ISSUE TITLE
Clean up for product page demo

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amp-by-example#740]
I noticed a few issues with the product page demo (https://ampbyexample.com/samples_templates/product/preview/):

- [ ] amp-form-var-sub is listed as a required experiment, but this is now launched, so that can be removed. (Presumably amp-bind is still needed?)
- [ ] From initial load: Click yellow, click green: Green shows an unavailable price
- [ ] From initial load: Click "S" and the page jumps
- [ ] From initial load: Click "S" [page jump, per above] and then click yellow and the page jumps
- [ ] From initial load: Click "S", then "M", then yellow, and the price says unavailable.

cc @ericlindley-g

**Comment by kul3r4** [comment]
Thanks I am looking into those.
I also get [this error](https://github.com/ampproject/amphtml/issues/8653) from time to time.

**Comment by rudygalfi** [comment]
Thanks!

**Comment by kul3r4** [comment]
@rudygalfi I deployed a new version, would you like to verify?
Ensure that the [error](https://github.com/ampproject/amphtml/issues/8653) is not launched when you load the page, if it does, try to reload the page again.

**Comment by rudygalfi** [comment]
All looks good on the originally reported issues, thanks! I get many errors when I have `#development=1` on the URL, but I didn't see the one you called out.
