### ISSUE TITLE
bind product sample: Carousel disappears if click on second green image thumb as first interaction

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#748]
To repro:

1. Open [bind e-comm sample](https://ampbyexample.com/samples_templates/product/preview/) on desktop
2. Click on second thumbnail for green apple (before triggering any other interaction)

Outcome: Carousel disappears (display set to "none")

Note: triggering another color carousel first makes it so this issue doesn't happen. May be related to [existing issue](https://github.com/ampproject/amphtml/pull/8661)? 

/cc @sebastianbenz

**Comment by kul3r4** [comment]
@ericlindley-g thanks! I bet it's the usual issue of the null variables at default, I'll take a look.

**Comment by kul3r4** [comment]
@ericlindley-g , This if fixed by #747 and I deployed the new version. I also added a note about default variables in the documentation section in #749.

**Comment by ericlindley-g** [comment]
Perfect—thanks @kul3r4 !
