### ISSUE TITLE
A4A samples don't load when ABE is hit from cdn.ampproject.org

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#755]
1. Visit: https://ampbyexample-com.cdn.ampproject.org/c/s/ampbyexample.com/amp_ads/video_ad/preview/?exp=a4a:-1 
2. Note the ad does not load
3. Error is: `
Fetch API cannot load https://securepubads.g.doubleclick.net/gampad/ads?iu=%2F30497360%2Famp_by_e…pbyexample.com%2F&dtd=4&__amp_source_origin=https%3A%2F%2Fampbyexample.com. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ampbyexample-com.cdn.ampproject.org' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

If visit https://ampbyexample.com/amp_ads/video_ad/preview/ ad loads fine.

**Comment by sebastianbenz** [comment]
Can't reproduce this, the ad always loads for me. However, the video
doesn't show (without an error message though) if the page is loaded via
the cache.

**Comment by aghassemi** [comment]
huh, worked for me on other browsers. Had to remove service worker and that fixed it on Chrome for me.

Video not loading part is tracked under https://github.com/ampproject/amphtml/issues/8730
