### ISSUE TITLE
Feature Request - Perpetual Calendar

### ISSUE THREAD

**Issue by GraySquare** [ampproject/amp-by-example#758]
Is it a possibility to introduce perpetual calendar in amp with the following functionality:

1. Ability to set weekends
2. Ability to display HTML content on a particular date before displaying on the webpage, so that the HTML either shows up as Title tag or a link to a different page

**Comment by sebastianbenz** [comment]
Could you link to a sample?

**Comment by GraySquare** [comment]
Similar to http://wpshindig.com/ Event Calendar but with ability to define weekends and the title of the event when hovered over the date or something better

**Comment by sebastianbenz** [comment]
Thanks - that should definitely be possible using a similar approach as the [tabs samples](https://ampbyexample.com/advanced/tab_panels_with_amp-selector/).

**Comment by GraySquare** [comment]
Is there a quick and dirty sample available online to test?

**Comment by sebastianbenz** [comment]
Not that I'm aware of, but feel free to contribute one. 😀

**Comment by kul3r4** [comment]
@GraySquare are you planning to work on this?

**Comment by GraySquare** [comment]
Not as of now. The client no longer needs this functionality.
