### ISSUE TITLE
amp-call-tracking + amp-img sometime not showing

### ISSUE THREAD

**Issue by PECDB** [ampproject/amp-by-example#762]
I have set the amp-img on my mobile web to make the call as follow:
```
<p class="center">
    <amp-call-tracking config="https://www.onsumlock.com/calltracking.onsum">
    <a href="tel:97647811"><amp-img src="img/call.gif" width="300" height="107" alt="Lock1"></amp-img></a>
  </amp-call-tracking>

</p>
```
"https://www.onsumlock.com/calltracking.onsum"
```
{
    "phoneNumber": "97647811"

  }
```
I find the image (call.gif) some time can't display on phone, I think maybe the calltracking.onsum problem... i don't know how to config, Please help me, Thank You! 
http://www.onsumlock.com

**Comment by sebastianbenz** [comment]
Sorry for the late reply. If this is a problem/bug in the amp-call-tracking component, the best place to report this is [here](https://github.com/ampproject/amphtml/issues/new).
