### ISSUE TITLE
Documentation: Wrong custom element script include

### ISSUE THREAD

**Issue by ruborg** [ampproject/amp-by-example#763]
## Description

**Page**: https://ampbyexample.com/advanced/tab_panels_with_amp-selector/

**Issue**: 
Example lists this as import script: 
`<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>`

**Expected**:
`<script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>`

**Comment by sebastianbenz** [comment]
@ruborg thanks for reporting!
