### ISSUE TITLE
Docs: amp-accordion example code in wrong section of example

### ISSUE THREAD

**Issue by ruborg** [ampproject/amp-by-example#770]
### Problem: 
In `setup` section of example, it jumps straight into styling example with this block:

> Use section[expanded] and section:not([expanded]) to style the accordion header depending on whether it is expanded or not.
> 
> ```
> <style amp-custom>
> amp-accordion section[expanded] .show-more {
>   display: none;
> }
> amp-accordion section:not([expanded]) .show-less {
>   display: none;
> }
> .nested-accordion h4 {
>   font-size: 14px;
>   background-color: #ddd;
> }
> amp-accordion#hidden-header section[expanded] h4 {
>   border: none;
> }
> </style>
> ```

### Expected
The quoted block above should appear further down in the example, in the `Styling the Accordion` section

**Comment by sebastianbenz** [comment]
@ruborg thanks!
