### ISSUE TITLE
Problem with login when trying to simulate example from https://ampbyexample.com/samples_templates/comment_section/preview/

### ISSUE THREAD

**Issue by yourchoice** [ampproject/amp-by-example#772]
Hi, 

I try to simulate login/logout on my local, but not understand exactly what i must to do  after popup login is submitted.

I followed the example and if submit validate the login, then i redirect to a page login-done.html?url={redirecturl}#success=true . {redirecturl} is the opener url .

In this page (login-done.html?url={redirecturl}#success=true) I have added <script async src="https://cdn.ampproject.org/v0/amp-login-done-0.1.js"></script> .
But nothing happen after redirect and have these errors:

> amp-login-done-0.1.js:57 Postback failed:  Error: Timed out
>     at amp-login-done-0.1.js:55
> Uncaught (in promise) TypeError: Cannot set property 'onclick' of null
>     at Gc.l (amp-login-done-0.1.js:57)
> 

If I refresh the main page (opener) the amp-access working. I reffer to the section:

```
<section amp-access="NOT loggedIn" amp-access-hide role="button" tabindex="0">
	Please <a class="btn" on="tap:amp-access.login-sign-in">Login</a> to comment.
</section>
<section amp-access="loggedIn" amp-access-hide role="button" tabindex="0">
  <a class="btn" on="tap:amp-access.login-sign-out">Logout</a>
</section>
```

Of course, i can reload the opener and I get the "Logout" btn visible if login was successful, but in example seems that there is not a reload of the the main page and amp-access authorization  is called from popup. Login/Logout buttons are changed without to refresh the page.

I apreciate any help.

**Comment by sebastianbenz** [comment]
This is the wrong place for asking generic AMP questions. Please ask these questions on [Stackoverflow](http://stackoverflow.com/questions/ask?tags=amp-html) using the `amp-html` tag. Thanks!

**Comment by yourchoice** [comment]
I see that get timeout because "https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/build/all/v0/amp-login-done-dialog.js" not found 404.

I write here maybe exists a issue with this example.

**Comment by yourchoice** [comment]
Online, the sample https://ampbyexample.com/samples_templates/comment_section/preview/ working well.

Not understand when i implement on local I get these 2 errors

> amp-login-done-0.1.js:57 Postback failed: Error: Timed out
> at amp-login-done-0.1.js:55
> Uncaught (in promise) TypeError: Cannot set property 'onclick' of null
> at Gc.l (amp-login-done-0.1.js:57)

Is called this file https://raw.githubusercontent.com/ampproject/amphtml/1493083583453/build/all/v0/amp-login-done-dialog.js that  not found 404 .

**Comment by sebastianbenz** [comment]
The correct URL is:

 <input name="returnurl" type="hidden" value="
https://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=https%3A%2F%2Fampbyexample.com%2Fsamples_templates%2Fcomment_section%2Fpreview%2F
">

**Comment by yourchoice** [comment]
Thank You,

I thought that need to build my login-done html page with this script included <script async src="https://cdn.ampproject.org/v0/amp-login-done-0.1.js"></script> .

Now after login form submit, as response just redirect to the value from field "returnurl" and working.

For the logout action I need to redirect to the same url ?

**Comment by yourchoice** [comment]
Working and for logout with redirect to $_GET['return'].

Thank You
