### ISSUE TITLE
Add button show more to product sample

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#775]
Current [product sample](https://ampbyexample.com/samples_templates/product_page/preview/) shows only 4 related product.
We could add a button "Show more" which will fetch a longer list by using amp-list and changing the source by using amp-bind to show more products, some code [here](https://github.com/ampproject/amphtml/blob/18733f77f2f6562ebffab7cd7891bedf31223e63/test/fixtures/amp-bind-integrations.html#L133).
@ericlindley-g, @choumx  FYI

**Comment by kul3r4** [comment]
@kmh287 @choumx I tried to bind to the src of amp-list but I got:
`error.js:131 amp-bind: Binding to [src] on <AMP-LIST> is not allowed.​​​ `
How can I use it?

**Comment by choumx** [comment]
Sorry about that, this week's canary was delayed. It should be in dev channel by end of today.

**Comment by kul3r4** [comment]
Ok, I can see that amp-list with amp-bind works with version 1493637481331 which I got by building locally the library and trying examples/bind/list.html,  but it doesn't with 1493420395795 which is the prerelease version available online. When using 1493420395795 I get:
`amp-bind: Expression evaluation error in "product.relatedProductsSrc". "https://amp-by-example-staging.appspot.com/json/more_related_products.json" is not a valid result for [src].​​​ 
`

**Comment by kmh287** [comment]
@kul3r4 I'm unable to reproduce that locally. Could you post the code in either a gist or a PR?

**Comment by kul3r4** [comment]
Sorry I forgot to add it, [branch](https://github.com/ampproject/amp-by-example/tree/show-more)

**Comment by kmh287** [comment]
Hmm, this is for `Product_Page.html` right? Have you pushed a commit where you set `relatedProductsSrc` to that url?

**Comment by kul3r4** [comment]
Should be [here](https://github.com/ampproject/amp-by-example/blob/show-more/src/50_Samples_%2526_Templates/Product_Page.html#L667)

**Comment by kul3r4** [comment]
Thanks to @kmh287 I solved this by disabling the `web-worker` experiment `AMP.toggleExperiment('web-worker')`
@choumx FYI

**Comment by choumx** [comment]
@kmh287 I think this is because the web worker entry point `ww.js` is not canary-able, which means you'll need to wait until the change hits prod. I'm working on a change to fix this. Good catch!

**Comment by choumx** [comment]
Fixed!
