### ISSUE TITLE
SVG not being reflected while using in amp-list tag

### ISSUE THREAD

**Issue by kolinitin** [ampproject/amp-by-example#782]
When used outside of amp-list tag, it works fine. Code screenshot attached for reference.
<img width="901" alt="screen shot 2017-04-29 at 9 03 59 pm" src="https://cloud.githubusercontent.com/assets/18439781/25556731/8ab261cc-2d1f-11e7-897f-15b5455194c2.png">

**Comment by kul3r4** [comment]
This is related to [https://github.com/ampproject/amphtml/issues/8214](https://github.com/ampproject/amphtml/issues/8214). As this is not related to amp-by-example, I am closing this bug.
