### ISSUE TITLE
Error: Cannot find module 'pump'

### ISSUE THREAD

**Issue by bersling** [ampproject/amp-by-example#817]
When running gulp, I get the error `Error: Cannot find module 'pump'`. To me the error makes sense, since the package.json makes no mention of a `pump` module.

**Comment by sebastianbenz** [comment]
Hm. I can't reproduce this on OS X. Which OS are you on? Does adding pump as a dependency (`npm install pump`) fix it?

**Comment by bersling** [comment]
I’m on OS X. Yes, npm install pump fixes it.

So if I search the repository for the word “pump” I just find it in the gulpfile in playground as in "const pump = require('pump’);”, meaning it’s missing in the package.json, right?

Maybe you have pump installed globally?

**Comment by sebastianbenz** [comment]
Fixed. Thanks!

**Comment by htmlstream** [comment]
@sebastianbenz Adding pump as a dependency `npm install pum` is fixed in MacOS. Thanks!
