### ISSUE TITLE
Feature request - provide hints to google (and other caches) for quick instant access to content

### ISSUE THREAD

**Issue by QES** [ampproject/amp-by-example#826]
Hi,

Not sure if this is the correct location for this idea (apologies if not).

I like the way that the cdn.ampproject.org / amp.cloudflare.com when loaded from contains quick access swipeable pages.  However we see many occasions when google has links to single AMP pages without this quick access elements and I wondered if there should be a way to code **hints** for google/cloudflare for this.

I know that this has potential for abuse and is a complex issue but it also strikes me that as users get more aware of the swipe able ability of the content when searching for it that having these elements and making sure they are useful for the reader would be a helpful adjunct.

For example my site creates content around events for a single event there may be between say 4 articles and 10 articles but they have an order and they have a sequence, if you come to an article in that sequence it would be cool if the other items were quickly accessible via the swipe feature and that the order and selection was controllable (or at least hint able) by the site/developer.

As an example if you search for "Sports Mole Chelsea vs Watford" currently you get 3 articles in a swipable carousel as "Top Stories" so google is already doing this but there are a number of other single pages that are part of the same content and which could (from a users perspective) be included.

http://amp.sportsmole.co.uk/football/premier-league/chelsea-vs-watford_game_56217.html
would link first to (reaction)
http://amp.sportsmole.co.uk/football/chelsea/news/nevin-chelsea-played-barcelona-esque_298279.html
then to (match report)
http://amp.sportsmole.co.uk/football/chelsea/result/result-chelsea-edge-watford-in-seven-goal-thriller_298278.html
then to (live commentary)
http://amp.sportsmole.co.uk/football/chelsea/live-commentary/live-commentary-chelsea-vs-watford_298265.html
etc

being able to hint on each of these pages where in the sequence it appears and so if it was loaded from the amp cache the extra swipability is included would be an improvement for the user experience.

I would envision something in the header that provided this information in the same way that the amphtml does or in the schema.org elements to show and provide this hint info.

`<meta name="amp-article-hint" content="http://amp.sportsmole.co.uk/football/premier-league/chelsea-vs-watford_game_56217.html http://amp.sportsmole.co.uk/football/chelsea/news/nevin-chelsea-played-barcelona-esque_298279.html http://amp.sportsmole.co.uk/football/chelsea/result/result-chelsea-edge-watford-in-seven-goal-thriller_298278.html http://amp.sportsmole.co.uk/football/chelsea/live-commentary/live-commentary-chelsea-vs-watford_298265.html">
`
OR 

`<script type="application/ld+json">{
      "@context": "http://schema.org",
      "@type": "NewsArticle",
      "mainEntityOfPage": {
         "@type": "WebPage",
         "@id": "www.sportsmole.co.uk/"
      	 },
      "hint-recomended": "http://amp.sportsmole.co.uk/football/premier-league/chelsea-vs-watford_game_56217.html http://amp.sportsmole.co.uk/football/chelsea/news/nevin-chelsea-played-barcelona-esque_298279.html http://amp.sportsmole.co.uk/football/chelsea/result/result-chelsea-edge-watford-in-seven-goal-thriller_298278.html http://amp.sportsmole.co.uk/football/chelsea/live-commentary/live-commentary-chelsea-vs-watford_298265.html",
`

The syntax of both of these could be made more complex to allow better definition of position and where the current article sits in the stream of articles but I'm not sure how simple of complex people might find this useful.

Obviously this would only be useful if it was used by those people with amp caches as hints to help make the user experience better.

Thanks

**Comment by kul3r4** [comment]
Hi,
please take a look at the [developer support page](https://www.ampproject.org/support/developer/) to find an appropriate place for discussing your suggestion.
