### ISSUE TITLE
FR: thumbs up / down example

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#828]
Example of thumbs up / thumbs down — similar to "like" or "<3" mechanic, where a server call is sent to increment (w/ optimistic update and correction when the call fails), but there's some interdependence between the two buttons, so it's only possible for a single user to choose one or the other.

**Comment by kul3r4** [comment]
This is really similar to [https://ampbyexample.com/advanced/favorite_button/](https://ampbyexample.com/advanced/favorite_button/).
