### ISSUE TITLE
server-side sorting/filtering using binding to amp-list[src]

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#829]

**Comment by kul3r4** [comment]
I could see this in:
- [AMP for ecommerce page](https://ampbyexample.com/amp_for_e-commerce%3A_getting_started/)
- [amp-list example](https://ampbyexample.com/components/amp-list/)
other ideas?

**Comment by ericlindley-g** [comment]
Agreed — I think it's a perfect fit for the product category/browse/search-result page for the e-comm sample. For now amp-carousel doesn't support amp-list, so it might help if the items were shown more as a list or grid, rather than a set of carousels. WDYT?

[Here's an example](https://www.bhphotovideo.com/c/search?Ns=p_PRICE_2%7c0&ci=16158&N=4288586281) in the wild of what server-side sorting/filtering w/out page reload can look like for a product category/browse/search-result page.

Would also be nice to call out the general functionality in the amp-bind and amp-list pages (though depending on the amount of effort, you could either include an example inline, or just link to another example)


The general feature would also be useful for a blog or news publication category/search-results page, so it might be worth making an example for that as well at some point

**Comment by kul3r4** [comment]
@choumx I am working on a "sorting menu" like [this](https://www.bhphotovideo.com/c/search?setNs=p_OVER_ALL_RATE%7c1&Ns=p_OVER_ALL_RATE%7c1&ci=16158&srtclk=sort&N=4288586281): Once you click on a sort choice from the sorting list, that choice goes on top of the list.

I was trying to realize it in [here](https://jsbin.com/bixureyoju/edit?html,console,output) by using amp-bind to change the value for each option using a temp value to do the swap. It doesn't seem to work, could you take a look? If you click on the menu choice (the one with the border) it shows the other option. 
hight to low, low to high -> low to high, high to low 
low to high, high to low -> hight to low, high to low  both are "high to low"

Do you think there could be an easiest way to achieve this?

**Comment by kul3r4** [comment]
@choumx Apology, amp-selector would be a better fit here, please ignore my previous comment.

**Comment by ericlindley-g** [comment]
The example works great! 

To follow up on my request above: Is it possible to present the sort items in a list view, instead of in the carousel? I think it's great to show that changing the sort order is possible in the context of the carousel, but I think that presenting items in as a list, the format that users are used to seeing (and a format that merchants are used to using), will increase the likelihood that they will understand how this will be useful to them. What do you think?

**Comment by kul3r4** [comment]
Sounds great, I was confused as there is no carousel at the moment but it's just the display. Will move it into a list layout.

**Comment by kul3r4** [comment]
@ericlindley-g I deployed a [new version](https://amp-by-example-staging.appspot.com/samples_templates/product_browse_page/preview/), is this better?

**Comment by ericlindley-g** [comment]
Yes—it looks great! (and the search capability is awesome, too!)

Thanks for getting this in, and sorry I was unclear w/r/t the "carousel" when there wasn't actually one :P

It might be worth thinking a bit about how to make it work on desktop to fill up the space on the right, but at least for now the mobile view gives great examples to use in the blog post about amp-bind!

**Comment by kul3r4** [comment]
Ok, thanks

**Comment by kul3r4** [comment]
This is now deployed [here](https://ampbyexample.com/samples_templates/product_browse_page/preview/).
