### ISSUE TITLE
sample: binding to <select>

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#833]
Can be demo'd for filtering criteria (extra points if it uses amp-bind[src] :), but also can be used to swap out blocks of UI (similar to tabs example, but uses <select> dropdown + amp-bind instead of tapping on tabs

**Comment by sebastianbenz** [comment]
Have we got this already covered with @kul3r4's filter/sort sample?

**Comment by ericlindley-g** [comment]
Yep, I think that covers it—thanks!
