### ISSUE TITLE
Enhancements to product category page

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#838]
• search results without page reload via amp-list[src] binding
• use list instead of carousel for search results, to avoid gaps in UI
• Integrate sorting and filtering via amp-list[src] binding

**Comment by kul3r4** [comment]
Related to #829

**Comment by kul3r4** [comment]
@ericlindley-g I think we can close this, right?

**Comment by ericlindley-g** [comment]
Definitely — that page is thoroughly enhanced!
