### ISSUE TITLE
sample: paging for results using amp-list[src]

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#839]
Could be integrated into existing sample—the idea is that a set of results can be paginated without page reload, using amp-list[src]

**Comment by kul3r4** [comment]
@ericlindley-g  Can this be something similar to "Trending on eBay" section [here](https://www.ebay.co.uk/) where you click the dot and a new set of 3 items is loaded?

**Comment by ericlindley-g** [comment]
I was imagining something that appears in more of a list view, similar to the pattern for short live blog entries, or results from a search. Since the carousel already feels like pagination to some extent, I think a list view would make the interaction more clear.

[Here's an example](https://www.bhphotovideo.com/c/buy/?ci=16158&N=4288586281&pn=2) (if you scroll to the bottom of the list and go to the next page)

WDYT?

**Comment by Cheecherngho799** [comment]
Bank
