### ISSUE TITLE
sample: custom checkboxes

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#841]
ex.

![screen shot 2017-05-18 at 5 51 12 pm](https://cloud.githubusercontent.com/assets/16807766/26228937/9e1512be-3bf2-11e7-9352-e99731090553.png)

**Comment by cvializ** [comment]
The [star rating example](https://ampbyexample.com/advanced/star_rating/) is kind of like this. It's just dressed up radio buttons.

**Comment by kul3r4** [comment]
closing this as it's already addressed.
