### ISSUE TITLE
amp-font is actually not builtin (?)

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-by-example#849]
The [`amp-font` sample](https://ampbyexample.com/components/amp-font/) claims "amp-font is builtin element and is automatically imported via the AMP runtime." Is this true?

- https://www.ampproject.org/docs/reference/components/amp-font says it needs to be imported via `<script>`.
- The [sample itself](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-font.html#L17) includes the `<script>` tag.
- Opening the playground [on the `amp-font` sample source](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-font%2Fsource%2F) and removing the `<script>` results in a validation error.

**Comment by kul3r4** [comment]
Closed by #850
