### ISSUE TITLE
Playground throws a 404

### ISSUE THREAD

**Issue by Vetm** [ampproject/amp-by-example#851]
When you visit [https://ampbyexample.com/playground/](https://ampbyexample.com/playground/) the right side just shows `404 page not found`.

**Comment by kul3r4** [comment]
Hi, I was able to load the page correctly. 
Could you try it again? Which browser are you using?

**Comment by Yelrado** [comment]
I'm getting the same error. It resolves by using Firefox in incognito mode.

**Comment by kul3r4** [comment]
@Yelrado @Vetm Could you take a look at the solution provided in #798 and see if it fixes it?

**Comment by Vetm** [comment]
@kul3r4 @dandv 's solution fixed it. Very strange, because I never visited the playground or ampbyexample.com before two weeks ago.

Had this problem with Chrome 58 and Firefox 53 on Arch Linux. 

Sorry for the duplicate issue!
