### ISSUE TITLE
amp-accordion stopped working

### ISSUE THREAD

**Issue by DeyanTomovAngelov** [ampproject/amp-by-example#854]
Previously working accordion stopped working today without any changes to the code. The expanded sections are expanded but the rest do not expand and the expanded do not collapse.

Here is a sample code:
 
`<amp-accordion>
    <section expanded><h5 class="card-header"><a>Why it matters?<span class="ul-toggler">+</span></a></h5>
        <p> The processes and the right methodology help you get the most out of the current resources and be able to
            scale. </p></section>
    <section><h5 class="card-header"><a>Symptoms for gaps<span class="ul-toggler">+</span></a></h5>
        <ul class="card-ul">
            <li>You use an interpretation of scrum, but only conduct standup meetings and no other ceremonies.</li>
            <li>In spite of the overtime, you're not likely to complete the product on time.</li>
            <li>Adding engineers to the team does not work for you and has failed multiple times.</li>
            <li>You have a considerable amount of technical debt and it continues piling up.</li>
        </ul>
    </section>
    <section><h5 class="card-header"><a>How we help <span class="ul-toggler">+</span></a></h5>
        <ul class="card-ul">
            <li>Analyze your current processes and suggest ways to improve the productivity.</li>
            <li>Suggest the best methodology for your project and train you how to implement it.</li>
            <li>Help you do more with the current resources by analyzing and addressing specific gaps in the process.
            </li>
        </ul>
    </section>
</amp-accordion>
`

**Comment by kul3r4** [comment]
Hello,
I checked [https://ampbyexample.com/components/amp-accordion/](https://ampbyexample.com/components/amp-accordion/) and the accordion works correctly.

Thanks for sending the code, but here we can solve only issues related to ampbyexample.com.

For general question on AMP, please use the [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) website.
