### ISSUE TITLE
Preview tab for embedded sample taller than expected

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amp-by-example#860]
I'm adding an amp-list embedded example and I'm finding that the preview window is taller than I wanted and thus won't show the overflow for the amp-list.

![previewtab](https://user-images.githubusercontent.com/1012254/27335953-255f774c-559c-11e7-8881-3635227f5076.png)

Preview: https://bp-samples.firebaseapp.com/examples/amplist.basic.preview.html
Code: https://github.com/bpaduch/bp-samples/blob/master/examples/src/amplist.html

Is there a way so that I can restrict the height of the preview so that it's only as tall as the amp-list element?

**Comment by sebastianbenz** [comment]
Hm - that's tricky because the amp-list will automatically resize if there is enough space (e.g. at the bottom of the doc, which is always the case). It might work if we force the initial preview size e.g. via param.
