### ISSUE TITLE
AMP Cache example

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#87]
Create an example with AMP cache

**Comment by sebastianbenz** [comment]
Provide samples for: 

        * plain amp, 
        * cached http amp
        * cached https amp
        * cached amp with redirect
        * update ping (?)

**Comment by sebastianbenz** [comment]
* What happens if the document is not available
* What happens if the amp doc is invalid

//cc @adewale

**Comment by sebastianbenz** [comment]
Here are some examples links:

* redirect: `https://cdn.ampproject.org/c/s/ampbyexample.com/amp-img.html` (redirects to `https://ampbyexample.com/components/amp-img/`)
* 404: https://cdn.ampproject.org/c/s/ampbyexample.com/not-found

We should also upload an intentionally invalid amp example (via the static dir).

**Comment by sebastianbenz** [comment]
* Explain that get arguments are supported, e.g. ampbyexample.com/test/?format=amp
