### ISSUE TITLE
Fix Product Page errors

### ISSUE THREAD

**Issue by gurmukhp** [ampproject/amp-by-example#874]
When viewing the Product Page with #development=1, many errors are shown such as:

- width/height may not appear in div
- amp-img is missing role and tabindex
- default value of class does not match first expression result
- Clicking on a 2nd image in carousel errors 'Invalid slide value', although the slide still transitions.

https://ampbyexample.com/samples_templates/product_page/preview/#development=1

**Comment by kul3r4** [comment]
Thanks for reporting, taking a look
