### ISSUE TITLE
Sample for user prefs

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amp-by-example#889]
This sample should show the capability of configuring a page layout / behaviour based on user prefs. For example take a page which should show a list of 10 items. An user may choose to set a preference where every time he visits a page from this website the results paginates by showing the first 5 and then the others in the next page or he may choose to see all the results in the same page. This capability may also be a switch on the page, but I am referring to a setting related to a specific user which is persisted between visits.

This sample would need a logged user and the capability to store its prefs server side. Then, in order to change the page based on prefs we could use server side rendering. 
@sebastianbenz do you think that would be possible? When thinking about other AMP components, amp-bind is mostly client side unless amp-state could be configured server side providing defaults; at the same time I think prefs are not interactive changes on a page and it feels like that would be a bad use of amp-bind.

This could be applied to websites like Reddit.
@ericlindley-g if you can think other websites that may take advantage of this.

**Comment by sebastianbenz** [comment]
This should be fairly straightforward by combining amp-list and amp-form. You could either store the settings in a cookie (which might not work in ios if the page is served via the cache) or you store it server-side based on the client id.

**Comment by kul3r4** [comment]
Discussion on [amphtml project](https://github.com/ampproject/amphtml/issues/10453#issuecomment-316544227)

**Comment by sebastianbenz** [comment]
related to #980

**Comment by kul3r4** [comment]
@sebastianbenz @ericlindley-g @lswang1618 This is not possible at the moment, as documented in [previous comment](https://github.com/ampproject/amp-by-example/issues/889#issuecomment-317786007). An implementation based on amp-list will make the page very slow, so I don't think we should demo this.
