### ISSUE TITLE
Amp-app-banner example not showing button in ios 9 in chrome

### ISSUE THREAD

**Issue by muxin** [ampproject/amp-by-example#895]
In chrome IOS 9, https://ampbyexample.com/components/amp-app-banner/

The "View in app" button is not shown in the banner, possibly due to css issues.
<img src="https://user-images.githubusercontent.com/3897214/28190981-98599004-67e2-11e7-83fe-6700975796b5.png" width="300">
[ios 9.3 iphone6 chrome]

---
However, on ios 10, it's all good:
<img src="https://user-images.githubusercontent.com/3897214/28191014-c1d37a62-67e2-11e7-8df3-90848a94b440.png" width="300">
[ios 10.3 iphone6s chrome]

**Comment by muxin** [comment]
I'm looking into it, please assign it to me if possible.

**Comment by aghassemi** [comment]
8
