### ISSUE TITLE
Adding check validations in AMP FORM

### ISSUE THREAD

**Issue by heliosnarcissus** [ampproject/amp-by-example#901]
How do you validate the AMP FORM , the checkbox specifically, to know if user has checked atleast one of the boxes. Can you perform this condition validations using amp-bind?
Thanks

**Comment by kul3r4** [comment]
Hi, find a similar [question + answer on Stackoverflow](https://stackoverflow.com/questions/45199700/how-to-validate-checkboxes-in-an-amp-form/45219066#45219066)
