### ISSUE TITLE
Product Page - Add to cart is broken

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#914]
Looking at https://ampbyexample.com/samples_templates/product_page/preview/ 
`Add to card` is supposed to redirect the user however it looks like the XHR to `https://ampbyexample.com/samples_templates/product_page/add_to_cart?__amp_source_origin=https%3A%2F%2Fampbyexample.com` does not return a JSON response and therefore we get `Failed to parse response JSON: SyntaxError: Unexpected token < in JSON at position 0​​​` error` and user is not redirected.

**Comment by kul3r4** [comment]
Thanks for reporting, will work on that

**Comment by aghassemi** [comment]
@kul3r4 Thanks. On a related topic: one concern that has been raised recently is that having ClientId on the URL after redirect has the potential of session leaking if user accidentally copy/paste the Url and shares it. 

As part of the fix, could you have the server do a 301 redirect to a Url without the ClientId on the Url and maybe add a section to the page explaining the reasoning behind this?

**Comment by sebastianbenz** [comment]
Seems like https://ampbyexample.com/samples_templates/product_page/add_to_cart gets redirected to the sample page. 

@aghassemi the sample shouldn't leak the client id. We've implemented a second redirect which removes the client id.

**Comment by kul3r4** [comment]
Just sent a fix. Regarding the redirect, it is already in place:
when user click on add to cart we add the client id on the url
`w.Header().Set("AMP-Redirect-To", GetHost(r)+"/shopping_cart/?clientid="+clientId)`
then, we redirect to an URL without the clientid

    func gotToShoppingCart(w http.ResponseWriter, r *http.Request, page Page) {
        // remove the clientid from the URL to avoid accidental sharing
        clientId := r.URL.Query().Get("clientid")
        if clientId != "" {
            redirectToShoppingCart(w, r, page, clientId)
        } else {
            renderShoppingCart(w, r, page, clientId)
        }
    }
