### ISSUE TITLE
AMP By Example - AMP Video Ad - Playground code invalid

### ISSUE THREAD

**Issue by ascherchen** [ampproject/amp-by-example#920]
When looking at https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Famp-ads%2Fadvanced_ads%2Fvideo_ad%2Fsource%2F we should try and provide a validated AMP template for video ad sample - see attachment
![awcp9fwhhan](https://user-images.githubusercontent.com/23347829/29336017-6a74ebcc-81c1-11e7-9a16-000463728c59.png)

**Comment by ascherchen** [comment]
additionally, the click URL https://ampbyexample.com/amp_ads/video_ad/ is not a valid one (goes to 404 page)

**Comment by sebastianbenz** [comment]
The ad is valid, but the playground currently doesn't support A4A (we're
working on fixing that). Where did you find this link:
https://ampbyexample.com/amp_ads/video_ad/?

**Comment by ascherchen** [comment]
That link https://ampbyexample.com/amp_ads/video_ad/  is directly
referenced into the code
https://ampbyexample.com/amp-ads/advanced_ads/video_ad/

Alissa Scherchen
Partner Technology Manager

If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.

**Comment by kul3r4** [comment]
@ascherchen ads now work on playground, closing this.
