### ISSUE TITLE
importing css file or calling other html page in index.html page

### ISSUE THREAD

**Issue by alok97097** [ampproject/amp-by-example#922]
I tire to import css file like <style amp-custom> {{> css/main.css}} </script>
and header.html and footer.html in my index.html page
{{> header.html}} but it display the code as it is {{> header.html}} html page. how can i import other html page in my index.html page

**Comment by kul3r4** [comment]
Hi,
are you trying to copy from [templates/index.html](https://github.com/ampproject/amp-by-example/blob/1266ab0fcff1126d7c2d9d71a4084638001ec33d/templates/index.html)?
We use templates to generate pages, this means that when you see code like:
`
<style amp-custom>
      {{> css/ampstart.css}}
      {{> css/shared.css }}
      .abe-sample-card {
        background: #f9f7f7;
        min-width: 240px;
        width: 0;
        max-width: 380px;
        flex: 1 1 240px;
      }
....
`
it means that the page will include content from css/ampstart.css and css/shared.css, but this require the template to render the page, which is done in one of the gulp task. If you checkout the project and build it, you will see that the content inside the `div` directory contains all the code.

Take a look at [Templates.js](https://github.com/ampproject/amp-by-example/blob/1266ab0fcff1126d7c2d9d71a4084638001ec33d/lib/Templates.js) to see how we achieve this.
