### ISSUE TITLE
Does AMP supports form wizard ? 

### ISSUE THREAD

**Issue by anandAmitBabul** [ampproject/amp-by-example#924]
I want to implement a form wizard on a site . I have developed it in AMP but didn't got any reference or example of form wizard . Is it possible to do a form wizard using AMP . Any reference will be helpful .

**Comment by kul3r4** [comment]
Hi,
this is a project of AMP samples, for any general questions please use [stackoverflow](https://stackoverflow.com/questions/tagged/amp-html) website.
