### ISSUE TITLE
Hard Forms

### ISSUE THREAD

**Issue by airarm** [ampproject/amp-by-example#932]
Why did you complicate everything with forms? Implementing a simple POST query is very difficult. We need an action-xhr, https, Allow-Origin-Header, I'm tired of it all

**Comment by airarm** [comment]
I fucked off the form validation script.

**Comment by kul3r4** [comment]
Hi, thanks for your feedback.
This website hosts a set of samples for AMP, for any general feedback or if you want to engage a discussion with the AMP team you can use other [channels](https://www.ampproject.org/support/developer/).
