### ISSUE TITLE
sample: add amp-position-observer samples

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#944]
good starting list here:
https://codepen.io/collection/nMJYrv/

**Comment by sebastianbenz** [comment]
I wondering what would be the best way to structure these samples. Single sample vs multiple ones?

**Comment by kul3r4** [comment]
Is [visual effects section]https://ampbyexample.com/#visual_effects doing this? Can we close this issue? 
@aghassemi

**Comment by aghassemi** [comment]
Yep, fairly well covered in that section.
