### ISSUE TITLE
Amp-sidebar open effect Chrome

### ISSUE THREAD

**Issue by diegodeodati** [ampproject/amp-by-example#947]
Hi on my side when i try to open the sidebar into chrome into my android device i can't see the slide-in effect.

This is the piece of code involved:

		
		#sidebar-left{
		background: #090807;
		padding: 0 23px 0 20px;
		border-right: solid 2px #e8e8e8;
		width: 240px;
		height:100%;
		}
		
		#sidebar-left li:first-child{
		display: block;
		text-decoration: none;
		line-height: 45px;
		border-top: none;
		color: #fff;
		font-weight: bold;
		}
		
		#sidebar-left li{
		display: block;
		text-decoration: none;
		line-height: 45px;
		border-top: solid 1px #e8e8e8;
		color: #fff;
		font-weight: bold;
		}	
		
		#sidebar-left a{
		color: #fff;		
		font-weight: bold;
		}
		
		#sidebar-left ul ul{
		margin-bottom:0px;
		}
		
		#sidebar-left ul ul li:first-child{
		border-top: solid 1px #e8e8e8;
		}
		
		#sidebar-left ul ul li{
		padding-left: 10px;
		}
		
		amp-user-notification {
		background: #111111;
		height: auto;
		line-height: 20px;
		color: #eeeeee;
		text-align: center;
		padding: 3px 0;
		display: block;
	border-top: 1px solid;
		}	

		amp-user-notification a {
		color: #ffffff;
		display: inline-block;
		border-radius: 3px;
		text-decoration: none;
		padding: 0 6px;
		margin-left: 8px;
		}
		
		amp-user-notification button {
    color: #ffffff;
    display: inline-block;
    border-radius: 3px;
    text-decoration: none;
    padding: 0 6px;
    margin-left: 8px;
}
		
		amp-user-notification .cb-policy {
		background: #0033bb;
		}
		
		amp-user-notification .cb-enable {
    background: #2cabe2;
	cursor:pointer;
}
		
    </style>
    <script type="application/ld+json">{ "@context": "http://schema.org", "@type": "NewsArticle", "headline": "Capodanno Residenza Castelverde 2018", "author": "Discolight", "datePublished": "29 October, 2017", "image": { "@type": "imageObject", "url": "http://www.discolight.it/capodanno/images/capodanno_residenza_castelverde/capodanno-residenza-castelverde-1.jpg", "height": "400", "width": "300" }, "publisher": { "@type": "Organization", "name": "Discolight", "logo": { "@type": "imageObject", "url": "http://www.discolight.it/serate/templates/newhorizon/images/event.png" } } }
    </script>
    <style amp-boilerplate>
        body {
            -webkit-animation: -amp-start 3s steps(1, end) 0s 1 normal both;
            -moz-animation: -amp-start 3s steps(1, end) 0s 1 normal both;
            -ms-animation: -amp-start 3s steps(1, end) 0s 1 normal both;
            animation: -amp-start 3s steps(1, end) 0s 1 normal both
        }
        @-webkit-keyframes -amp-start {
            from {
                visibility: hidden
            }
            to {
                visibility: visible
            }
        }
        @-moz-keyframes -amp-start {
            from {
                visibility: hidden
            }
            to {
                visibility: visible
            }
        }
        @-ms-keyframes -amp-start {
            from {
                visibility: hidden
            }
            to {
                visibility: visible
            }
        }
        @-o-keyframes -amp-start {
            from {
                visibility: hidden
            }
            to {
                visibility: visible
            }
        }
        @keyframes -amp-start {
            from {
                visibility: hidden
            }
            to {
                visibility: visible
            }
        }
    </style>
    <noscript>
        <style amp-boilerplate>
            body {
                -webkit-animation: none;
                -moz-animation: none;
                -ms-animation: none;
                animation: none
            }
        </style>
    </noscript>
</head>

<body>
    <amp-sidebar id="sidebar-left" layout="nodisplay" side="left">
        <nav toolbar="(min-width: 80%)" toolbar-target="target-element-left">
            <ul>
MORE OR LESS 20 links...
            </ul>
        </nav>
    </amp-sidebar>

**Comment by sebastianbenz** [comment]
can you please file this as a bug for [ampproject/amphtml](https://github.com/ampproject/amphtml/issues/new). Thanks!
