### ISSUE TITLE
Facing issue with AMP Carousel

### ISSUE THREAD

**Issue by tlstechtesting** [ampproject/amp-by-example#950]
We are facing issue with the Carousel. Works correctly when used separately, but creates some issue while used with other AMP scripts. Image is not changing on clicking the forward navigation, it only works on double clicking the navigation. The same issue is with autoplay.

**Comment by kul3r4** [comment]
Hi,
ampbyexample is a website hosting samples, if you think there is a bug with the AMP library feel free to open an issue on [https://github.com/ampproject/amphtml](https://github.com/ampproject/amphtml), and if possible, please also provide a sample URL.

**Comment by tlstechtesting** [comment]
Ok Sure, thank you
