### ISSUE TITLE
Product Category Page example looks broken

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-by-example#953]
Viewing [https://ampbyexample.com/introduction/amp_for_e-commerce_getting_started/#product-category-page](https://ampbyexample.com/introduction/amp_for_e-commerce_getting_started/#product-category-page) in Chrome 61 on my Mac, the example looks broken.  The image carousel is too small, with text that extends past the bottom of the image and gets cut off - and the whole example fills only a small upper portion of the phone template.

![screen shot 2017-10-03 at 3 26 15 pm](https://user-images.githubusercontent.com/29419498/31144718-87c80e98-a84f-11e7-9fc9-9260ab786e16.png)

**Comment by morsssss** [comment]
Actually... I still see this issue...

**Comment by sebastianbenz** [comment]
I just deployed a new version, should be live now.
