### ISSUE TITLE
On home page, "Internationalization" can overflow its container

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-by-example#974]
At just the wrong browser size, "Internationalization" can overflow its container on the home page - as, sadly, there's nowhere to break a one-word title.

Here's a screenshot on Chrome 61/Mac!

<img width="291" alt="screen shot 2017-10-10 at 2 27 53 pm" src="https://user-images.githubusercontent.com/29419498/31403674-cf3c1a9e-adc7-11e7-81f7-e1d9867ea17a.png">

**Comment by sebastianbenz** [comment]
Hm. One option would be to simply truncate titles if they overflow...

**Comment by morsssss** [comment]
I just discovered that there's a soft hyphen htmlentity:   &shy;

https://codepen.io/benmorss/pen/dVKyyx

For that matter, if I use "hyphens:auto", Chrome actually knows how to break "internationalization" with a hyphen.

**Comment by kul3r4** [comment]
Would it work with [long word](https://en.wikipedia.org/wiki/Lopadotemachoselachogaleokranioleipsanodrimhypotrimmatosilphioparaomelitokatakechymenokichlepikossyphophattoperisteralektryonoptekephalliokigklopeleiolagoiosiraiobaphetraganopterygon)?

**Comment by sebastianbenz** [comment]
@kul3r4 yes, if you can correctly place the soft hyphens...
