### ISSUE TITLE
amp-form <input placeholder=""> & <label> - IE 11 & Edge

### ISSUE THREAD

**Issue by Polylike** [ampproject/amp-by-example#976]
Hello,

IE 11 and Edge dont show the placeholder on input but shows the hidden label

![image](https://user-images.githubusercontent.com/16958775/31513572-0b397186-af8f-11e7-9968-2a3526a2b731.png)

Chrome, FF, Opera ...
![image](https://user-images.githubusercontent.com/16958775/31513599-218821da-af8f-11e7-94b8-6f6d3de021fa.png)

Best,
Daniel

**Comment by kul3r4** [comment]
which sample are you referring to? If this is not a sample on AMPByExample please close this issue and use [AMP support channels](https://www.ampproject.org/support/developer/) for general questions
