### ISSUE TITLE
Dynamic data tools

### ISSUE THREAD

**Issue by lswang1618** [ampproject/amp-by-example#979]
Show all the different ways of fetching fresh data:

- data fetch for amp-bind/amp-state on page load (https://github.com/ampproject/amphtml/pull/8574)
- amp-bind + amp-list (https://github.com/ampproject/amphtml/pull/10610)
- update-cache-request
- clarify batching of amp-list calls 
- highlight that you can mix dynamic and cached product details

**Comment by sebastianbenz** [comment]
Thanks for the suggestions! Few comments:

1) We have a sample [here](https://ampbyexample.com/introduction/amp_for_e-commerce_getting_started/#dynamic-content). Have you got specific use cases in mind for this?
2) Which use case did you have in mind? We have two samples for this, the [show more](https://ampbyexample.com/samples_templates/product_page/preview/) and the [filter](https://ampbyexample.com/samples_templates/product_browse_page/preview/).
3) Good point
4) This is mentioned [here](https://ampbyexample.com/introduction/amp_for_e-commerce_getting_started/#dynamic-content) as well. Anything that is missing?
5) Can you elaborate?

**Comment by lswang1618** [comment]
Thanks Sebastian! I missed some of these :D 

I think it might be worth it to just have a dedicated sample that organizes these different techniques by use-case. That way we can point partners to one place for guidance. Thoughts?

**Comment by sebastianbenz** [comment]
We could introduce a new top-level category for these sample, e.g. 'Dynamic AMP'. This way we can keep samples smaller which makes it easier to understand the code/markup.

**Comment by kul3r4** [comment]
@lswang1618 For the "update-cache-request" I don't think a sample is needed, there is no code involved and it's documented in [update-cache](https://developers.google.com/amp/cache/update-cache)

**Comment by kul3r4** [comment]
blocked by [https://github.com/ampproject/amphtml/issues/11882](https://github.com/ampproject/amphtml/issues/11882)

**Comment by kul3r4** [comment]
@lswang1618 Let me know if you have any feedback about these samples.
