### ISSUE TITLE
sample: progressive selector 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amp-by-example#981]
For instance:
**Select State**

(depending on selected value of state)
**Select City**

**Comment by sebastianbenz** [comment]
//cc @morsssss who has been looking into this

**Comment by morsssss** [comment]
I have been working on a sample on and off, yes... sounds like I should get it together! 😀

I've been working on a version that makes a new request each time the first select is updated, and another that loads all the data on page load.

**Comment by lswang1618** [comment]
Somewhat related, can we also include an example of form fields that appear based on earlier selections? i.e. https://screenshot.googleplex.com/VpVHSmOeZWg

**Comment by kul3r4** [comment]
This has been implemented in [https://ampbyexample.com/advanced/linked_dropdowns/](https://ampbyexample.com/advanced/linked_dropdowns/)
