### ISSUE TITLE
AMP can involve interactivity without resorting to an iframe

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-by-example#984]
https://ampbyexample.com/advanced/how_to_create_interactive_amp_pages/

Our "How to create interactive AMP pages?" guide, referenced from the menu on the home page, tells people to embed interactive content in iframes.  Of course, this works, but perhaps we should make this guide focus on \<amp-bind\>, \<amp-list\>, and their ilk, with a reference to the iframe technique if desired.  But let's let people know that interactivity is possible within AMP!

**Comment by kul3r4** [comment]
Thanks! good you noticed, this is an old sample and definitively needs some updates.
@sebastianbenz We could move this under the new section "Dynamic AMP" and update the doc stating that `amp-iframe` is a valid solution when interactivity cannot be implement by using `amp-bind`. WDYT?

**Comment by sebastianbenz** [comment]
sgtm
