### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by lswang1618** [ampproject/amp-by-example#988]
Including
 - log-in pop-up, if possible, that brings saved customer information, i.e. shipping info, email
 - promo codes
 - gift card entry
 - summary, with estimated shipping, address validation (https://www.usps.com/business/web-tools-apis/welcome.htm)
 - match billing to shipping address check-box
 - payments form (note that the merchant can just specify the right endpoint to then process payment themselves)

ex. https://screenshot.googleplex.com/r87Ps1NFsDT, https://screenshot.googleplex.com/P3EMbRHCSWh, 
https://screenshot.googleplex.com/qF9B2dkH0tH, https://screenshot.googleplex.com/GRa5FAygzJL

**Comment by sebastianbenz** [comment]
Done in #1010
