### ISSUE TITLE
Amp Live List Update Issue

### ISSUE THREAD

**Issue by nrjames** [ampproject/amp-by-example#995]
I've implemented AMP Live list on a website, but I've noticed that the content doesn't update as it should. This particular use of the AMP live list should be polling the page on the sever every 15 seconds and updating the content in the page if the recently polled page differs.

If I visit the amp page directly, the live list works. But if I visit the amp cached page on a mobile device through a google search or by emulating a mobile device in the chrome browser, the page doesn't update.

I've done some research and discovered today that Google's own example of this doesn't work either. The example uses football scores which change when the scores change in the origin document.

If you visit the page directly through this link : https://ampbyexample.com/components/amp-live-list/ - the football score example works and updates.

Mobile visit or mobile emulated visit doesn't work as it should : If you visit the page on a mobile by doing a google search for "amp live list" and clicking on the amp result (actually view the amp cached version), the scores don't update.

Is this a known bug or is it just me having this issue?

**Comment by kul3r4** [comment]
Hi @nrjames, if you think there is a bug in the library, please open an issue on [amphtml](https://github.com/ampproject/amphtml) so that engineers could take a look. Please also provide the URL of your website where you encountered the problem.
